### ISSUE TITLE
Manageable Usage doesn't work

### ISSUE THREAD

**Issue by ziaq** [zfcsoftware/puppeteer-real-browser#1]
The first method with actual browser opening works fine, but the second method with headless: true doesn't work. I try the example from the documentation and it just opens two browsers, one with two blank pages, the other with one blank page

**Comment by zfcsoftware** [comment]
@ziaq  Which operating system do you use? 
I will look into the issue and update shortly.

**Comment by ziaq** [comment]
> @ziaq Which operating system do you use? I will look into the issue and update shortly.

Windows 11

**Comment by dobahoan2792000** [comment]
I have the same problem like him, I'm using win 11 and when I run manageable usage, It stop at "const page = await browser.newPage()"

**Comment by MiguelRomaniw** [comment]
I tried to use the second version of your code to be able to manage pupteer better, but it always gives an error in newPage and opens 2 tabs in the browser, and both are inaccessible

**Comment by zfcsoftware** [comment]
@ziaq @dobahoan2792000 @MiguelRomaniw 
The bookshelf has been updated. Please try again with the updated documentation. Tests in Windows environment did not show any problems.

**Comment by MiguelRomaniw** [comment]
@zfcsoftware 


Yes, it works, this was the way I was using it

Another thing that is happening, for some reason, the puppeteer loses connection with the page and gives an error, I will try to reproduce the error to show you


This error occurs in either of the two use cases

**Comment by zfcsoftware** [comment]
> @zfcsoftware
> 
> Yes, it works, this was the way I was using it
> 
> Another thing that is happening, for some reason, the puppeteer loses connection with the page and gives an error, I will try to reproduce the error to show you
> 
> This error occurs in either of the two use cases

I'm glad it works, I haven't had this kind of problem. If you encounter the problem again, I can examine it if you can show it with a video. Thank you.
