### ISSUE TITLE
HELP/SUGGESTION: Multi - Threading

### ISSUE THREAD

**Issue by MarioCodarin** [zfcsoftware/puppeteer-real-browser#10]
Hello how you would deal with multi-threading? There are some good libraries like crawlee and puppeteer-cluster but I can't see the way to integrate them with puppeteer-real-browser

**Comment by zfcsoftware** [comment]
Hello,
libraries like puppeteer-cluster will just need to change the library it uses inside. I'll look into the puppeteer-cluster library and try to create a fork. 

The repo's low star rating and lack of interest discourages me from making such improvements. When the repository is deployed, I will provide such improvements. thanks.
