### ISSUE TITLE
Update Feature

### ISSUE THREAD

**Issue by SattyaP** [zfcsoftware/puppeteer-real-browser#100]
To the creator 👀
I would like to thank you for helping me with my work with your library.

I expect the condition feature when the captcha has been clicked but wants to be clicked again to be auto so that it does not cause errors.

Thank you 🤩

**Comment by zfcsoftware** [comment]
It should now be able to continuously resolve multiple Captchas anywhere on the page. Can you post the error you are getting, the operating system?

**Comment by SattyaP** [comment]
The error I mean is the combination of the library with my logic, I mean there is no error with your library, it's just that when it clicks the first time it can then sometimes it needs to be clicked again it doesn't do anything.

> It should now be able to continuously resolve multiple Captchas anywhere on the page. Can you post the error you are getting, the operating system?

**Comment by zfcsoftware** [comment]
The library will click even if a continuous captcha is generated. There is no limitation. It clicks continuously. Your request should already be working right now. If you cannot run the operating system, if you add sample code, I can reactivate and examine this problem again. Thank you.
