### ISSUE TITLE
Is it possible to solve this captcha?

### ISSUE THREAD

**Issue by Shuma24** [zfcsoftware/puppeteer-real-browser#102]
Hi everyone, is there any way to solve such captcha, what library or api can be used with puppeteer-real-browser to solve such captcha?
![Знімок екрана 2024-07-27 165820](https://github.com/user-attachments/assets/3261ff79-cd03-4b8c-a216-48c255a8fd83)
![Знімок екрана 2024-07-27 165824](https://github.com/user-attachments/assets/62ca8555-7fec-4aaf-a506-d423137e08fd)

**Comment by zfcsoftware** [comment]
Datadome captcha. You can use Capsolver. I'm closing it as it has nothing to do with the library.

**Comment by Shuma24** [comment]
Okay, thanks!
