### ISSUE TITLE
No longer able to pass turnstile with forced-open shadow root

### ISSUE THREAD

**Issue by psx18** [zfcsoftware/puppeteer-real-browser#103]
I need to click buttons inside a closed shadow root. Previously (pre click patch), I was able to use the following workaround:

```
await page.evaluateOnNewDocument(`
          Element.prototype._attachShadow = Element.prototype.attachShadow;
          Element.prototype.attachShadow = function () {
             return this._attachShadow( { mode: "open" } );
          };
        `);
```

Now this code causes the Cloudflare turnstile to fail, e.g. at https://thewebscraping.club/cloudflare-turnstile-tester/

**Comment by zfcsoftware** [comment]
This code has nothing to do with the library. You can ask Stackoberflow. The library will resolve all Turnstile captchas when turnstile: true is set. It has a built-in module, I suggest you use it. I'm closing it as it has nothing to do with the library.

**Comment by psx18** [comment]
I meant the library does not resolve the turnstile when trying to access a closed shadow root.

E.g.
```

    const args = {
        headless: 'false',
        args: [],
        skipTarget: [],
        fingerprint: true,
        turnstile: true,
        connectOption: {},
        tf: true
    };


    const {browser, page, setTarget} = await connect(args);
    await page.evaluateOnNewDocument(`
          Element.prototype._as = Element.prototype.attachShadow;
          Element.prototype.attachShadow = function () {
             return this._as( { mode: "open" } );
          };
        `);
    await page.goto('https://thewebscraping.club/cloudflare-turnstile-tester/');

```

This does not pass the turnstile

**Comment by psx18** [comment]
> This code has nothing to do with the library. You can ask Stackoberflow. The library will resolve all Turnstile captchas when turnstile: true is set. It has a built-in module, I suggest you use it. I'm closing it as it has nothing to do with the library.

So what I meant is that the library does not resolve the turnstile after the latest update, when trying to access a closed shadow root in this manner.

E.g.:
```

    const args = {
        headless: 'false',
        args: [],
        skipTarget: [],
        fingerprint: true,
        turnstile: true,
        connectOption: {},
        tf: true
    };


    const {browser, page, setTarget} = await connect(args);
    await page.evaluateOnNewDocument(`
          Element.prototype._as = Element.prototype.attachShadow;
          Element.prototype.attachShadow = function () {
             return this._as( { mode: "open" } );
          };
        `);
    await page.goto('https://thewebscraping.club/cloudflare-turnstile-tester/');
```

**Comment by zfcsoftware** [comment]
> > This code has nothing to do with the library. You can ask Stackoberflow. The library will resolve all Turnstile captchas when turnstile: true is set. It has a built-in module, I suggest you use it. I'm closing it as it has nothing to do with the library.
> 
> So what I meant is that the library no longer resolves the turnstile after the latest update, when trying to access a closed shadow root in this manner.
> 
> E.g.:
> 
> ```
> 
>     const args = {
>         headless: 'false',
>         args: [],
>         skipTarget: [],
>         fingerprint: true,
>         turnstile: true,
>         connectOption: {},
>         tf: true
>     };
> 
> 
>     const {browser, page, setTarget} = await connect(args);
>     await page.evaluateOnNewDocument(`
>           Element.prototype._as = Element.prototype.attachShadow;
>           Element.prototype.attachShadow = function () {
>              return this._as( { mode: "open" } );
>           };
>         `);
>     await page.goto('https://thewebscraping.club/cloudflare-turnstile-tester/');
> ```

I don't understand why you are trying to solve it this way. The library already has a feature to solve all Turnstile captchas when turstile: true is set. You can use that.

**Comment by psx18** [comment]
That code isn't for solving captchas, it's needed in order to click elements that are inside a closed shadow root. I don't know any other way to do so. 

(I've been using this library for some time, and it's worked for this use case until just recently)

**Comment by zfcsoftware** [comment]
> That code isn't for solving captchas, it's needed in order to click elements (other than the captcha) that are inside a closed shadow root. I don't know any other way to do so.
> 
> (I've been using this library for some time, and it's worked for this use case until just recently)

Sorry for the misunderstanding. You can run Javascript in the Chrome plugin.
https://github.com/zfcsoftware/puppeteer-real-browser/blob/main/src/module/extension/script.js

**Comment by psx18** [comment]
Thanks, I'll try that
