### ISSUE TITLE
Extracting tar content of undefined failed, the file appears to be corrupt

### ISSUE THREAD

**Issue by XLordalX** [zfcsoftware/puppeteer-real-browser#105]
Getting this error when instaling this package.

`error https://github.com/zfcsoftware/puppeteer-afp/tree/master: Extracting tar content of undefined failed, the file appears to be corrupt: "Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?"`

Downgrading the version, installing, upgrading and then installing again resolves the issue.

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.
