### ISSUE TITLE
Open modal/sidebar in dextools.io close unexpected

### ISSUE THREAD

**Issue by tx-tomcat** [zfcsoftware/puppeteer-real-browser#106]
Here is URL : `https://www.dextools.io/app/en/user/account`
The code is:
`
 await page.goto('https://www.dextools.io/app/en/user/account');
 const button = await page.waitForSelector("::-p-xpath(//html/body/app-root/div/div/main/app-register/app-layout/div/div/div[2]/div[1]/div[2]/button)")
`
Connect wallet modal show up, then disappear immediately.
Working fine with another webpage(opensea...)

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.
