### ISSUE TITLE
Not able to capture screenshots.

### ISSUE THREAD

**Issue by tusharmctrl** [zfcsoftware/puppeteer-real-browser#109]
I am using Dockerfile - everything runs perfectly fine. 
But there is one part in my code where i have to take a screenshot of a page.
![image](https://github.com/user-attachments/assets/5d0453f8-ad5a-4c15-baa3-69725b5f4c3f)
It throws an error like this - what am i doing wrong?

**Comment by zfcsoftware** [comment]
You may have tried to retrieve the page before it loaded or when the page was closed. There is no code to reproduce the error, so I'm closing it. You need to make sure the page is loaded, open and not redirected somewhere.
