### ISSUE TITLE
Question related Puppeteer-real-browser 

### ISSUE THREAD

**Issue by Biswajit96** [zfcsoftware/puppeteer-real-browser#11]
1. FingerPrint 
which one is best ?
		"fingerprint-generator": "^2.1.30",
		"fingerprint-injector": "^2.1.30",
		or 
		puppeteer-afp
2. Extra-plugins 
dose Puppeteer-real-browser need puppeteer-extra & puppeteer-extra-plugin-stealth or its can mask all parameters its self without extra plugins ?

3. Puppeteer Version and Cluster tool 
my bot using "puppeteer": "^21.5.0" with  Puppeteer Cluster Puppeteer-real-browser work fine with any version or need any specific version ?

thank you in advance :)

**Comment by Biswajit96** [comment]
> Hello, puppeteer-real-browser creates a real browser and does not need any fingerprint plugin. You can go through bot detection tools without using any plugins. https://fingerprint.com/demo/ Fingerprint plugins are to avoid getting caught by sites like this that detect if it is the same browser. I recommend using puppeteer-afp. I haven't checked Puppeteer Cluster, sorry. I will check it out. Thank you

thank you so much for your attention.  i really appreciated your help.

**Comment by Biswajit96** [comment]
Good evening sir,
when my developer try to implement real browser in our project.
my developer say puppeteer real browser uses deprecated option for puppeteer so we can't use args , but without args can't changing proxy and other settings.
Please advice.

**Comment by zfcsoftware** [comment]
> Good evening sir, when my developer try to implement real browser in our project. my developer say puppeteer real browser uses deprecated option for puppeteer so we can't use args , but without args can't changing proxy and other settings. (browserWSEndpoint, is no longer supported) Please advice. thanks in advance.

Hi, I just tested it and I didn't have any problem using a proxy. The problem may be caused by your code. You can check the video below. Please provide video about the problem you are having.


https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/efbb7e13-06e9-4b01-9b4f-af7db5f4e32b

**Comment by mubaidr** [comment]
Thanks for this awesome library, here is related error: 

![Screenshot_20240208_155752](https://github.com/zfcsoftware/puppeteer-real-browser/assets/2222702/ee05fbf7-4e69-46be-aa7b-f472f533ea5d)

**Comment by zfcsoftware** [comment]
> Thanks for this awesome library, here is related error:
> 
> ![Screenshot_20240208_155752](https://private-user-images.githubusercontent.com/2222702/303303045-ee05fbf7-4e69-46be-aa7b-f472f533ea5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTA5NjUsIm5iZiI6MTcwNzM5MDY2NSwicGF0aCI6Ii8yMjIyNzAyLzMwMzMwMzA0NS1lZTA1ZmJmNy00ZTY5LTQ2YmUtYWE3Yi1mNDcyZjUzM2VhNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMTExMTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTYyZWU3NDllYzE2OWM3YzZkNDE3MTJhOWY2Yjg2NDMwNDdhYzBjZmYwMjU4ZmUxODllZDdhMDQ0NjUzYWIzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.35kehLllzWnKr6cQPAzB2vgiWHYk-SONLGFQCZando4)

This error seems to be Typescript specific. Can you try the Typescript version @CrispyyBaconx created? I didn't encounter an error when using Commanjs. Thank you for using the library.
https://github.com/zfcsoftware/puppeteer-real-browser/tree/Type-Script

**Comment by CrispyyBaconx** [comment]
> Thanks for this awesome library, here is related error:
> 
> ![Screenshot_20240208_155752](https://private-user-images.githubusercontent.com/2222702/303303045-ee05fbf7-4e69-46be-aa7b-f472f533ea5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MzIzOTksIm5iZiI6MTcwNzQzMjA5OSwicGF0aCI6Ii8yMjIyNzAyLzMwMzMwMzA0NS1lZTA1ZmJmNy00ZTY5LTQ2YmUtYWE3Yi1mNDcyZjUzM2VhNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMjI0MTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDYwOGZjNjcyMmUzMTQ0ZDdjMWQ1NDZhNDM4MTgzMmUzMDNiYzBkY2RjZWZlZDZlZTY0M2UxMjUyYTU1NzU4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sgk_5m_0MUiorDq5WIwKFme51Y5XUJXYHXvbvuu2_Dc)

The puppeteer.launch function doesn't take browserWSEndpoint as an arg according to their docs (https://pptr.dev/api/puppeteer.puppeteerlaunchoptions)

The way you are currently using it by launching it is creating two browser instances since you are launching Chrome with the library and also launching a puppeteer instance of Chrome. The Websocket Endpoint is used to control an already launched instance of Chrome. Use puppeteer.connect in that case.

**Comment by mubaidr** [comment]
> > Thanks for this awesome library, here is related error:
> > ![Screenshot_20240208_155752](https://private-user-images.githubusercontent.com/2222702/303303045-ee05fbf7-4e69-46be-aa7b-f472f533ea5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MzIzOTksIm5iZiI6MTcwNzQzMjA5OSwicGF0aCI6Ii8yMjIyNzAyLzMwMzMwMzA0NS1lZTA1ZmJmNy00ZTY5LTQ2YmUtYWE3Yi1mNDcyZjUzM2VhNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMjI0MTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDYwOGZjNjcyMmUzMTQ0ZDdjMWQ1NDZhNDM4MTgzMmUzMDNiYzBkY2RjZWZlZDZlZTY0M2UxMjUyYTU1NzU4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sgk_5m_0MUiorDq5WIwKFme51Y5XUJXYHXvbvuu2_Dc)
> 
> The puppeteer.launch function doesn't take browserWSEndpoint as an arg according to their docs (https://pptr.dev/api/puppeteer.puppeteerlaunchoptions)
> 
> The way you are currently using it by launching it is creating two browser instances since you are launching Chrome with the library and also launching a puppeteer instance of Chrome. The Websocket Endpoint is used to control an already launched instance of Chrome. Use puppeteer.connect in that case.

Exactly, but in that case, we cannot pass args when using connect option.

**Comment by marcusdiy** [comment]
Hello. Did you manage to make browser.newPage work again? Can you share a snippet? Thanks

**Comment by mubaidr** [comment]
> Hello. Did you manage to make browser.newPage work again? Can you share a snippet? Thanks

You may use my fork of this repo. Which allows passing args, potentially solving this issue.

**Comment by marcusdiy** [comment]
@mubaidr yes, i tried. Same problem. await browser.newPage() never resolves

```
console.log('Try to open new tab');
let page2 = await browser.newPage();
console.log('New page opened, try an alert!');
await page2.evaluate(() => { alert(33) })
await page2.goto('https://nopecha.com/demo/cloudflare#1');
```

**Comment by zfcsoftware** [comment]
This issue has been resolved please try the latest version of the library. If the problem persists you can start a new discussion.
