### ISSUE TITLE
Always error with 'Timed out after waiting 30000ms' and other issues

### ISSUE THREAD

**Issue by chooyanglee** [zfcsoftware/puppeteer-real-browser#110]
Consider this code:

```
'use strict';

import { connect } from 'puppeteer-real-browser'; // v1.2.31

let globalBrowser = null;

try {

    const { browser, page } = await connect({
        headless: false,
        //ignoreHTTPSErrors: true,
        args: [
            '--ignore-certificate-errors',
            '--disable-dev-profile',
            '--no-sandbox',
        ],
        fingerprint: false,
        turnstile: true,
    });

    // we set the global browser with this browser in order to be able to close it from the catch
    globalBrowser = browser;

    await page.setCacheEnabled(false);

    // cf protected endpoint
    const theUrl = 'https://clubtek.pt/campanha/destaques-verao/GRELHAD-ORBEGOZ.2200W.BARBEC.-BCT3950-112238';

    await page.goto(theUrl, {
        timeout: 50000,
        waitUntil: 'domcontentloaded'
    });

    await page.waitForResponse(async (response) => {
        // cf does a few hops and we want to make sure we are in the requested page
        if (await response.url() == theUrl && await response.status() == 200) {

            // set a timeout to allow for the full DOM to build
            setTimeout(async () => {
                let dom = await page.content();
                console.log('dom.length: [' + dom.length + ']');
            }, 2000);
        }
    });

    await browser.close();
}
catch (err) {
    if (globalBrowser) await globalBrowser.close();
    console.log('main catch: [' + err.message + ']');
}
```

**Question 1**

The code always end up in the catch with 'Timed out after waiting 30000ms' where are the 30000ms specified? I get the DOM correctly.

**Question 2**

Since the browser is defined inside the try it will be out of scope inside the catch, is my approach above sound with the globalBrowser?

**Question 3**

On the [const { browser, page }] I have also seen it reversed in the wild [const { page, browser }] does it matter?

**Question 4**

All I want to do is to get the DOM, is my approach/code pattern above correct? Or, is there a better way?

**Comment by SattyaP** [comment]
Same with me, just using goto alone it always gives a timeout error of 30000 even though the dom has been loaded properly

Any suggest for solve this problem 

Thanks

**Comment by SattyaP** [comment]
This my code

```js

import {
    connect
} from "puppeteer-real-browser";

connect({
        headless: "auto",
        args: [],
        customConfig: {},
        skipTarget: [],
        fingerprint: false,
        turnstile: true,
        connectOption: {},
        fpconfig: {},
        proxy: null,
    })
    .then(async (response) => {
        const {
            browser,
            page
        } = response;
        await page.goto("https://pixelscan.net/", {
            waitUntil: ["domcontentloaded", "networkidle2"],
            timeout: 120000,
        });

        console.log("Page loaded successfully");
        console.log("Opening a new tab...");
        await page.evaluate(() => {
            const a = document.createElement("a");
            a.href = "https://pixelscan.net/";
            a.target = "_blank";

            document.body.appendChild(a);

            a.click();
        });
    })
    .catch((error) => {
        console.log(error.message);
    });

```

I did not change any form of your library but when the page is loaded properly it does not read the code below it but waits for 120000 even though the page is loaded properly.

**Comment by chooyanglee** [comment]
You need to use ```await page.waitForNavigation()``` after page.goto and maybe have a delay after that to get the final page (after cloudflare).

**Comment by Zvih** [comment]
This is a crucial issue. When you modify the targetFilter, Puppeteer targets are interfered with. The target that receives false from targetFilter gets stuck forever, and page.goto in this case overwhelms the timeout.

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.

**Comment by Pexeus** [comment]
@zfcsoftware GOAT

**Comment by marianalopezeikilis** [comment]
@mdervisaygan, I'm having the same problem with 1.3.12, are u you is that resolved?
