### ISSUE TITLE
Hi, why everyone is using Puppeteer but not Playwright

### ISSUE THREAD

**Issue by meotimdihia** [zfcsoftware/puppeteer-real-browser#112]
I think Playwright is a new and better package. But someone could explain why Puppeteer is more popular for scraping.

**Comment by zfcsoftware** [comment]
I think the community support is greater. Also, some things I could do with Puppeteer were very difficult to do with Playwright. That's why I use Puppeteer. Since there is no problem, I'll close the topic.
