### ISSUE TITLE
Corrupted viewport and Dev Console.

### ISSUE THREAD

**Issue by Zvih** [zfcsoftware/puppeteer-real-browser#121]
<img width="917" alt="image" src="https://github.com/user-attachments/assets/e9d70d5a-f042-4479-be54-b8c40e6454ec">

It works great with solving WAF, CAPTCHA, etc., but on the opened page, I encountered some weird web page rendering. It seems the viewport is broken.

Also, there is no possibility to use the Dev Console (F12).

What I'm doing wrong?

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.
