### ISSUE TITLE
`goto` always timed out when using `userDataDir` and after the 2nd goto.

### ISSUE THREAD

**Issue by meotimdihia** [zfcsoftware/puppeteer-real-browser#122]
I can't find out the real reason but `userDataDir` did it:
Also, this problem is not real consistently. Sometimes, it works but once it fails then it will always fail. You should try to run the script several times.
`TimeoutError: Navigation timeout of 30000 ms exceeded`
```ts
import { connect } from "puppeteer-real-browser"

async function main() {
  const path = "/tmp/puppeteer-real-browser/" + process.pid
  const selector = "#chapterlist ul li"
  const url = "https://hivetoon.com/manga/juvenile-offender/"

  const { browser, page } = await connect({
    headless: false,
    customConfig: {
      userDataDir: path
    },
    args: [],
    skipTarget: [],
    fingerprint: false,
    turnstile: true,
    connectOption: {},
    fpconfig: {}
  })

  await page.goto(url)
  await page.waitForSelector(selector)
  await browser.close()

  const { browser: browser2, page: page2 } = await connect({
    headless: false,
    customConfig: {
      userDataDir: path
    },
    args: [],
    skipTarget: [],
    fingerprint: false,
    turnstile: true,
    connectOption: {},
    fpconfig: {}
  })
  await page2.goto(url) // Timeout <---------- TimeoutError: Navigation timeout of 30000 ms exceeded
  await page2.waitForSelector(selector)
  await browser2.close()
}

main()
  .catch(console.error)
  .finally(async () => {
    console.log("Done")
  })

```

- puppeteer-real-browser: 1.2.32
- macOS

**Comment by kyungseopk1m** [comment]
This issue was very troublesome for me. 
It would proceed normally, but occasionally the error would occur again. 
So, I added the following code before the page.goto and was able to resolve the problem:
`page.setDefaultNavigationTimeout(0);`

**Comment by meotimdihia** [comment]
@kyungseopk1m what if the option `setDefaultNavigationTimeout(0)` made `goto` load forever?

**Comment by kyungseopk1m** [comment]
@meotimdihia If the page doesn’t load within a few minutes, it might never load. 
However, the reason I entered the code that way is because I manage the page, and I know it will definitely load. 
In cases different from mine, you could set it to 10 minutes, like `page.setDefaultNavigationTimeout(10 * 60 * 1000)`, 
which should resolve the issue.

**Comment by meotimdihia** [comment]
@kyungseopk1m I tried to add the code: ` await page2.setDefaultNavigationTimeout(0)` but it didn't work.

**Comment by kyungseopk1m** [comment]
@meotimdihia Is there a reason you’re setting the `selector "num"` option instead of using the `waitUntil: 'networkidle0' or 'networkidle2` option? 
My guess is that the timeout is occurring because the communication hasn’t been completed.

**Comment by meotimdihia** [comment]
@kyungseopk1m I tried all `waitUlti` options but it is always a timeout.
the code is necessary to reproduce the bug too:

```ts
  await page.waitForSelector(selector)
```
If we remove them then the problem won't happen.

So both `userDataDir` and `waitForSelector` did it.

P/S: I updated the issue.

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/puppeteer-real-browser/blob/3237722fa3e3bcbc95c9aaaae8f87f75fea195fd/src/test.js#L48
Temporary solution

**Comment by meotimdihia** [comment]
@zfcsoftware Yes, I am using this solution - removing await in goto.

Hopefully, you can fix it in the next patches.

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.
