### ISSUE TITLE
Headless question

### ISSUE THREAD

**Issue by roimee6** [zfcsoftware/puppeteer-real-browser#123]
Do you have any idea how to make headless mode accessible? 

Because with headless, my computer's performance is very, very, very expensive!

(for Windows )

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.

**Comment by roimee6** [comment]
https://streamable.com/5cdr8i?src=player-page-share

It still doesn't seem to work for me!

**Comment by zfcsoftware** [comment]
> https://streamable.com/5cdr8i?src=player-page-share
> 
> It still doesn't seem to work for me!

The library promises not to be caught only in headless false. You can run it in other headless modes, but it may not pass as in the video. You can try adding stealth plugin by editing the library files. As you downgrade headless mode a lot of issues arise.

**Comment by roimee6** [comment]
ok, I didn't understand then, sorry

**Comment by NabiKAZ** [comment]
Does anyone know a solution or library for headless: true?

**Comment by RubberArchind** [comment]
> Does anyone know a solution or library for headless: true?

AFAIK it's pretty much impossible to bypass cloudflare with headless:true

**Comment by NabiKAZ** [comment]
My concern was more because I was using a Linux terminal, which was solved with xvfb.
But on Windows, this window still bothers me. I tried running it in minimized window mode, but this time the Cloudflare captcha wouldn't solve.

**Comment by RubberArchind** [comment]
how is your config?

also have you install xvfb as npm package?

**Comment by RubberArchind** [comment]
if disableXvfb set to true, will it worked?

**Comment by NabiKAZ** [comment]
I don't think disableXvfb has any effect on Windows, but I tried it and it didn't work.

Maybe I should clarify my problem once again:

My problem is with the window opening in Windows OS, there must be a way to prevent this window from being displayed.

I minimized the Chrome window, but it failed to read the captcha. So programs like NirCmd or AutoHotKey to run in minimized mode don't help.

But when I tried to quickly move the opened Chrome window to a new Desktop (WinKey+Tab). This worked for me.

So maybe one solution is to open Chrome in a new Desktop using Windows functions. But it might be complicated to implement.

**Comment by RubberArchind** [comment]
You can use bash script then, or you might want to try this

[https://www.npmjs.com/package/win-control](https://www.npmjs.com/package/win-control)

i think it's should be do the trick

**Comment by NabiKAZ** [comment]
Thanks, Before I saw your answer. I was working on [node-window-manager](https://github.com/sentialx/node-window-manager).
Of course I also tried [win-control](https://github.com/nosolosoftware/win-control) but it seemed to have problems with nodejs 22 at the beginning of the installation and I didn't continue with it. Because apparently it does the same thing with windows as node-window-manager.

## Solution 1:
My trick is to find the chrome window by HWND based on the page title and move it to another desktop using [VirtualDesktop](https://github.com/MScholtes/VirtualDesktop). Code like this:

```javascript
import { connect } from "puppeteer-real-browser"
import { windowManager } from 'node-window-manager';

const { browser, page } = await connect({ headless: false });

// Open the page
await page.goto('https://www.nic.ir/Login', { waitUntil: "domcontentloaded" });

// The main title of the page requested
const title = 'ورود به سامانه – ایرنیک - Google Chrome';

// Move the window based on the title using node-window-manager
setTimeout(() => {
    const windows = windowManager.getWindows();
    const chromeWin = windows.find(win => win.getTitle() === title);
    if (chromeWin) {
        const hwnd = chromeWin.id;
        console.log('Found Chrome HWND:', hwnd);
        exec(`C:/Users/Nabi/Downloads/VirtualDesktop11.exe /GetDesktop:*last* /MoveWindowHandle:${hwnd}`);
    } else {
        console.log('Chrome window not found');
    }
}, 3000);
```

## Solution 2:
Then I found out that VirtualDesktop itself can detect windows by title. So I improved the previous code. This code constantly checks the window title and moves it whenever it is found.

```javascript
import { connect } from "puppeteer-real-browser"
import { exec } from 'child_process';
import util from 'util';
const execAsync = util.promisify(exec);

const { browser, page } = await connect({ headless: false });

// Open the page
await page.goto('https://www.nic.ir/Login', { waitUntil: "domcontentloaded" });

// The main title of the page requested
const title = 'ورود به سامانه – ایرنیک - Google Chrome';

// Move the window based on the title using VirtualDesktop
const titleModified = title[0] + "^^" + title.slice(1);
const interval = setInterval(async () => {
    try {
        await execAsync(`C:/Users/Nabi/Downloads/VirtualDesktop11.exe /GetDesktop:*last* /MoveWindowHandle:"${titleModified}"`);
    } catch (out) {
        if (!out.stderr.includes('Error while processing')) {
            clearInterval(interval);
            console.log('Window moved successfully');
        }
    }
}, 100);
```

But both of these methods are not always interesting because we always have to give it the title and also there is a delay until the page loads and the title is visible, at which time the window will be visible.

## Solution 3:
The next trick is to move the current and active window to another desktop immediately after the chrome window opens:

```javascript
import { connect } from "puppeteer-real-browser"
import { exec } from 'child_process';

const { browser, page } = await connect({ headless: false });

// Moves the window based on the currently active window.
exec(`C:/Users/Nabi/Downloads/VirtualDesktop11.exe /GetDesktop:*last* /MOVEACTIVEWINDOW`);

// Open the page
await page.goto('https://www.nic.ir/Login', { waitUntil: "domcontentloaded" });
```

This has no delay and the window moves very quickly so we don't see it. But if there is a delay between the window opening and the command being executed, or if the focus moves away from the window, I'm not sure what happens. It always worked for me, though, and I think this is a better solution.

**Comment by RubberArchind** [comment]
i found a simpler solution (this worked for me) just add this to the args

`args: ["--start-maximized","--window-position=-99999,-99999"],`

and you will never see the window

**Comment by NabiKAZ** [comment]
> i found a simpler solution (this worked for me) just add this to the args
> 
> `args: ["--start-maximized","--window-position=-99999,-99999"],`
> 
> and you will never see the window

Wow, that worked. That was a clever trick (:

**Comment by RubberArchind** [comment]
Just a side note, that args won't worked on linux. That's why i didn't suggest it to you earlier.

And when i try that on windows boom it's worked 😁

**Comment by NabiKAZ** [comment]
So as a summary to simulate `headless=true` while `headless=false`:

For Linux: `npm i xvfb`
For Windows: `args: ["--start-maximized","--window-position=-99999,-99999"],`

This way the window will never be visible.
