### ISSUE TITLE
Potentially being detected

### ISSUE THREAD

**Issue by fnnq** [zfcsoftware/puppeteer-real-browser#124]
I may be doing something wrong, I'm not 100% sure, if I am I apologise.

Basically I am trying to automate following on the website kick.com. I am able to access the site fine, watch streams but upon trying to login I get a error "The browser is not supported." on every other legitimate browser I am able to login and follow fine, what I tried to do is login with cookies and it appears to work but upon following I get the same "The browser is not supported." 

They also have cloudflare but I think this is a client side detection.

Any help or information is greatly appreciated, thanks.

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.
