### ISSUE TITLE
Docker no longer works with the latest update

### ISSUE THREAD

**Issue by bsantos09** [zfcsoftware/puppeteer-real-browser#125]
When updating to the latest version of puppeteer-real-browser the dockerfile no longer works.
I found this out when installing the package in my own project and building my own docker image. It seems to be an issue with puppeteer and the version of chrome it requires to run. 
Steps to reproduce:
1. Run `npm install` to update the package-lock.json
2. Build dockerfile
3. Run dockerfile

Logs:

Launching the browser...
Error: Could not find Chrome (ver. 127.0.6533.72). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /root/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.
