### ISSUE TITLE
Loading extension via args: [] does not work

### ISSUE THREAD

**Issue by vootsman** [zfcsoftware/puppeteer-real-browser#126]
Trying to load an extension via args: [] doesn't work.

example:

```
const  { page, browser} = await connect({

    headless: 'no',

    args: [		`--disable-extensions-except=${this.extensionPath}`,
      			`--load-extension=${this.extensionPath}`],

    customConfig: {},

    skipTarget: [],

    fingerprint: false,

    turnstile: true,

    connectOption: {},

    fpconfig: {},



})

```

Looking into it, it appears the the way the turnstile extension is injected over writes this.  

I made a work around by adding my extension to this line:

chromium.js, line 71:
```
const EXTENSION_PATH = `${dirPath}/extension/,${process.cwd()}/my extension/`;

```

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.
