### ISSUE TITLE
This is not working please try this URL 

### ISSUE THREAD

**Issue by heeropunjabi** [zfcsoftware/puppeteer-real-browser#127]
<img width="1767" alt="image" src="https://github.com/user-attachments/assets/f767bbb0-b13c-4bb1-b69e-4c3b93aeb4c6">

URL --> https://deviceandbrowserinfo.com/are_you_a_bot

**Comment by heeropunjabi** [comment]
@EgglezosK That URL checks whether you r using Chrome Dev Protocol or not, based on that it detect u r bot or not.

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.
