### ISSUE TITLE
New update doesnt work with turnstile button captcha

### ISSUE THREAD

**Issue by PTBKoo** [zfcsoftware/puppeteer-real-browser#129]
Hey, noticed it will no longer click the captcha if it a turnstile button, updated to 1.2.33 but no luck. Heres a quick video:

https://github.com/user-attachments/assets/fc201671-a4db-41c7-be9c-c2a97665eb80

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.

**Comment by DivMode** [comment]
Thanks for the quick update.

I am have the same issue after updating to 1.3 but did notice the page itself was smaller than the browser after updating to 1.3 so it does look a little zoomed in in the video. 

I also noticed a nice speed increase. 

https://github.com/user-attachments/assets/a9e958a6-26bb-4c73-9a15-45b17392c179

**Comment by PTBKoo** [comment]
Thanks for the quick update.

I am have the same issue after updating to 1.3 but did notice the page itself was smaller than the browser after updating to 1.3 so it does look a little zoomed in in the video.

I also noticed a nice speed increase.

**Comment by DivMode** [comment]
It wasnt working because it looks like the latest version of cloudflare turnstile was updated to remove cf-turnstile-response input next to the shadow dom.

<img width="351" alt="Screenshot 2024-08-28 at 12 33 24 AM" src="https://github.com/user-attachments/assets/05bddad2-9927-4fc7-bded-761173edabf2">
<img width="494" alt="Screenshot 2024-08-28 at 12 32 54 AM" src="https://github.com/user-attachments/assets/4d1d3184-3075-44ad-a9a9-c8bd01792739">

**Comment by zfcsoftware** [comment]
I applied a fix, please try again with the latest version.

https://github.com/user-attachments/assets/77d3ae4c-afa8-4c7a-bd18-7ecb076d91df

**Comment by PTBKoo** [comment]
Works great, thanks for the quick fix!

**Comment by PTBKoo** [comment]
Wow it looks like they already patched it, been trying to figure out a solution myself all night but having some trouble. Tried using xpath and couple of different things but no luck with that either.

It looks like they removed the style attribute on the parent div of the shadow dom making it difficult to access the cloudflare box to get the bounding box. 

I also cant access the main-wrapper class since its in the closed shadow dom unless theres a way to access elements in a shadow dom.

Any help would be appreciated.

Thanks!

<img width="468" alt="Screenshot 2024-08-31 at 12 39 10 AM" src="https://github.com/user-attachments/assets/d6db271f-bd70-4057-b185-7e5f3345c72e">

**Comment by zfcsoftware** [comment]
> Wow it looks like they already patched it, been trying to figure out a solution myself all night but having some trouble. Tried using xpath and couple of different things but no luck with that either.
> 
> It looks like they removed the style attribute on the parent div of the shadow dom making it difficult to access the cloudflare box to get the bounding box.
> 
> I also cant access the main-wrapper class since its in the closed shadow dom unless theres a way to access elements in a shadow dom.
> 
> Any help would be appreciated.
> 
> Thanks!
> 
> <img alt="Screenshot 2024-08-31 at 12 39 10 AM" width="468" src="https://private-user-images.githubusercontent.com/29348754/363410686-d6db271f-bd70-4057-b185-7e5f3345c72e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMTA0MDYsIm5iZiI6MTcyNTExMDEwNiwicGF0aCI6Ii8yOTM0ODc1NC8zNjM0MTA2ODYtZDZkYjI3MWYtYmQ3MC00MDU3LWIxODUtN2U1ZjMzNDVjNzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEzMTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YjI0ZTRhYWE2MWNiMTk1MTFjYTc0Y2MzMDhlNzJhNmRlZWE5YmU2NDEyZjE4YTM4ZTI5MjI5MGNkZmYwZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RMJbRC4lMeM8R9b--dgsW9agLyEYa3ODe9w2cxtz2ss">

fixed

**Comment by PTBKoo** [comment]
Beautifully done, works great! Thank you for this amazing library.
