### ISSUE TITLE
Doesn't work with multiple tabs

### ISSUE THREAD

**Issue by marcusdiy** [zfcsoftware/puppeteer-real-browser#13]
I was wondering was is different about this project. I get that it helps to bootstrap the real browser and connect to it.
But what i dont get is why you launch 2 browser, first one that is hidden and the next one that is being used.
Doesn't launching a single browser directly and connect to it have the same effect with much less overhead?

**Comment by zfcsoftware** [comment]
Hello, the purpose of the second recommended usage is to be able to perform tasks such as installing Chrome extensions. When starting Chromium and providing the command to load a Chrome extension into flags, it does not install the extension. This situation applies only during the initial use. By default, a Chromium instance is launched and connected with Puppeteer without allowing for loading Chrome extensions when connecting with .connect. Therefore, those who do not require actions like installing extensions may prefer the default usage. However, for tasks such as installing Chrome extensions or specifying args, there is a need for the second usage.

**Comment by marcusdiy** [comment]
In your example you dont refer to extensions as it seems to be the main point now? there is no example too...
Btw doesn't the --load-extension= argument allow the installing of extensions? Sorry, I'm no expert just want to understand.
Maybe there is some caveat that I'm missing?

**Comment by zfcsoftware** [comment]
> In your examples you dont refer to extensions as it seems to be the main point now? there is no example too... Btw doesn't the --load-extension= argument allow the installing of extensions? Sorry, I'm no expert just want to understand. Maybe there is some caveat that I'm missing?

The primary browser is not launched with puppeteer. We are launching it with Chromium. I tried to install an extension on Chromium via command line for a few hours, but it didn't work or I couldn't succeed, and I didn't have time to investigate this deeply. Therefore, I presented 2 usages. The first one starts Chromium and connects with puppeteer.connect to return the browser and page variables. Only 1 browser opens in this method. However, the Chrome extension cannot be loaded in this case.
The other one starts a chromium and returns the connection port. The rest of the process is up to the user. Just like when starting a normal puppeteer with .launch, you can use whatever you were using in that usage here as well.
https://stackoverflow.com/questions/67049065/puppeteer-unable-to-load-chrome-extension-in-browser
The reason why instructions for loading extensions are not provided in the second usage is that its usage is exactly the same as puppeteer's entirely. You can smoothly load the extension just like in the link provided above. However, a total of 2 browsers are run in this case.
Since it did not receive much attention by receiving stars from packages, I cannot dedicate much time to development. In the future, I plan to solve problems such as loading extensions and create a structure where all processes can be done with a single browser instance.

**Comment by marcusdiy** [comment]
Hmm strange, did you try passing the path of the extention or the .crx? Because the later seems to be more problematic.
I can launch chrome via nodes spawn, providing the extention folder path, it works with headless too.

**Comment by zfcsoftware** [comment]
> Hmm strange, did you try passing the path of the extention or the .crx? Because the later seems to be more problematic. I can launch chrome via nodes spawn, providing the extention folder path, it works with headless too.

crx, klasör çeşitlerini denedim. Ancak denediğim sırada kütüphane Chromium örneğini chromium kütüphanesi ile başlatıyordu. şu an @sparticuz/chromium ile başlatıyor. Belki bu tarayıcı örneğinde eklenti yüklenebiliyordur.

Kodunuzu ve mümkünse kullanım şeklinizi video ile ekleyebilirseniz kütüphaneyi en kısa zamanda güncelleyebilirim.

**Comment by zfcsoftware** [comment]
> Hmm strange, did you try passing the path of the extention or the .crx? Because the later seems to be more problematic. I can launch chrome via nodes spawn, providing the extention folder path, it works with headless too.

I tried different folder types in crx. However, when I tried, the Chromium library example was starting with chromium library. Now I am starting with @sparticuz/chromium. Maybe extensions can be loaded in this browser example.
If you can add your code and usage method with a video, I can update the library as soon as possible.

**Comment by zfcsoftware** [comment]
> It goes something like this ![puppeteer-load-extention](https://private-user-images.githubusercontent.com/42746781/306452105-b78e9e65-4f04-4cef-8d0a-0d54c5341253.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NzU3MDQsIm5iZiI6MTcwODQ3NTQwNCwicGF0aCI6Ii80Mjc0Njc4MS8zMDY0NTIxMDUtYjc4ZTllNjUtNGYwNC00Y2VmLThkMGEtMGQ1NGM1MzQxMjUzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAwMzAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMjJlNmI5OGYyM2ViZGFhY2MwMzA0YmRmYTE4NDM0OGFkOTA1YzMxM2JkNzU3OTNjNDRhZGNkNjdmNmIxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._lDLUnmq4_8MvGR2zIWH_nrP2oj90ccfUnseebnwOMk)
Thank you for your contributions. I will update the library soon.

**Comment by marcusdiy** [comment]
no problem

**Comment by marcusdiy** [comment]
You are welcome, the fact of using two browsers was just looking a bit strange to me...maybe there are other advantages that Im missing. Anyway .crx installation probably can be automated too becouse its just a zip at the end.

**Comment by marcusdiy** [comment]
Btw there is something worth investigating, while my basic script works with extentions it seems to fail cloudflare baypass...where you method works. Maybe missing some flag? Will double check.

**Comment by marcusdiy** [comment]
At the end it seems to be boiling down to this. Wich is amazing... i cant still figure out why it works tho
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/42746781/020fb1a3-60e6-4587-906f-e0b286313057)

**Comment by marcusdiy** [comment]
Got a guess. Using your script if I call `await browser.newPage()` it wont work. But why?
Maybe its because its being filtered by targetFilter as so its kinda disconnected from puppeteer?

**Comment by zfcsoftware** [comment]
> Got a guess. Using your script if I call `await browser.newPage()` it wont work. But why? Maybe its because its being filtered by targetFilter as so its kinda disconnected from puppeteer? And thats why its not being detected by cloudflare too... so maybe there is a need for a way to connect and disconnect

targetfilter prevents this. But I will definitely try to find a solution, I have updated the library. Thank you for your contributions.

**Comment by marcusdiy** [comment]
Yes, thanks for the update. Here a test case.
I'm thinking about switching to python 😂 

```
import { connect } from 'puppeteer-real-browser'
import puppeteer from 'puppeteer-extra';
import StealthPlugin from 'puppeteer-extra-plugin-stealth'

puppeteer.use(StealthPlugin())
function sleep(ms) { return new Promise(res => setTimeout(res, ms)) }

connect({
    headless: 'auto', args: [], customConfig: {}, skipTarget: [],
    fingerprint: true, turnstile: true, connectOption: {},
    // proxy:{ host:'',  port:'', username:'', password:'' }
}).then(async response => {
    const { browser, page } = response
    await page.goto('https://nopecha.com/demo/cloudflare');
    await page.evaluate(() => { document.body.style.background = '#d9ffe7' });
    console.log('Now a new tab should appear');
    let page2 = await browser.newPage();
    console.log('...and it should goto cloudflare test page, but it won\'t');
    await page2.goto('https://nopecha.com/demo/cloudflare');
}).catch(error => {
    console.log(error.message)
})
```

**Comment by zfcsoftware** [comment]
> Yes, thanks for the update. Here a test case.
> 
> ```
> import { connect } from 'puppeteer-real-browser'
> import puppeteer from 'puppeteer-extra';
> import StealthPlugin from 'puppeteer-extra-plugin-stealth'
> 
> puppeteer.use(StealthPlugin())
> function sleep(ms) { return new Promise(res => setTimeout(res, ms)) }
> 
> connect({
>     headless: 'auto', args: [], customConfig: {}, skipTarget: [],
>     fingerprint: true, turnstile: true, connectOption: {},
>     // proxy:{ host:'',  port:'', username:'', password:'' }
> }).then(async response => {
>     const { browser, page } = response
>     await page.goto('https://nopecha.com/demo/cloudflare');
>     await page.evaluate(() => { document.body.style.background = '#d9ffe7' });
>     console.log('Now a new tab should appear');
>     let page2 = await browser.newPage();
>     console.log('...and it should goto cloudflare test page, but it won\'t');
>     await page2.goto('https://nopecha.com/demo/cloudflare');
> }).catch(error => {
>     console.log(error.message)
> })
> ```
I'll post an update soon

**Comment by zfcsoftware** [comment]
> let page2 = await browser.newPage();
>     console.log('...and it should goto cloudflare test page, but it won\'t');
>     await page2.goto('https://nopecha.com/demo/cloudflare');

I have released an update, could you please try and use it as it is in the readme file?

**Comment by marcusdiy** [comment]
Sure thing

**Comment by marcusdiy** [comment]
Works, great success 👍 
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/42746781/4bb50870-fbff-4582-9bfd-881bb866c77f)
