### ISSUE TITLE
How to set up 2 concurrent browsers?

### ISSUE THREAD

**Issue by KoenVerhoof4** [zfcsoftware/puppeteer-real-browser#131]
I need one browser with and one without proxy, Is this possible using prb?
When I try to open 2 instances I get errors trying to perform commands on my secondly opened browser.

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.

**Comment by theshitcoder** [comment]
I am on version 1.4.0 .. I have 2 processes executing this same code:
```
const connectOptions = {
    headless: false,
    args: [],
    customConfig: {},
    turnstile: true,
    connectOption: {},
    disableXvfb: false,
    ignoreAllFlags: false
};

var { browser, page } = await connect(connectOptions);

await page.goto(url);

await browser.close();
```

I often (not always) get this error **_Navigating frame was detached_** .. which tells me one of the processes closes the browser where the other process is still navigating.. any advice?

**Comment by RubberArchind** [comment]
try to set a random user data dir

**Comment by theshitcoder** [comment]
```javascript
  const os = require("os");
  const path = require("path");
  const { randomUUID } = require("crypto");

  // Generate a random user data directory for each worker
  const userDataDir = path.join(os.tmpdir(), `puppeteer_user_data_${randomUUID()}`);
  fs.mkdirSync(userDataDir, { recursive: true });

  const connectOptions = {
      headless: false,
      args: [],
      customConfig: {
          userDataDir: userDataDir
      },
      turnstile: true,
      connectOption: {},
      disableXvfb: false,
      ignoreAllFlags: false
  };
            
``` 

still get similar errors .. TargetCloseError: Protocol error (Page.navigate): Target closed
