### ISSUE TITLE
bet365 detect your browser

### ISSUE THREAD

**Issue by Hartyshow26** [zfcsoftware/puppeteer-real-browser#137]
Hi,

I don't know if you can do something about that because it's a quite specific problem but the website https://www.bet365.com/ detects that the browser you launch is automated and have a system that block every requests done. It also happens with a real browser if you open the dev tool and refresh the page : no information is loaded.

Is there something we can do about that detection ? Maybe some suggestions ? 

Have a great day

**Comment by zfcsoftware** [comment]
This website uses things like country blocking. This is probably why you were blocked. Honestly, I tested it with Datadome and it didn't catch it. Since it's not from the library, I'm turning it off. Try using a good proxy.
