### ISSUE TITLE
Support for using sandbox

### ISSUE THREAD

**Issue by aumeshm** [zfcsoftware/puppeteer-real-browser#142]
Right now, puppeteer real browser only uses the `--no-sandbox` flag. There should be a setting so we can set the real browser to use sandbox vs `--no-sandbox`

**Comment by zfcsoftware** [comment]
ignoreAllFlags: true https://github.com/GoogleChrome/chrome-launcher?tab=readme-ov-file#api You can turn it off by adding the defaultFlags here again. However, I cannot turn it off to avoid problems when running with Docker. You can follow the steps I forwarded to turn it off.
it doesn't just use the ol flag. It uses many flags. You can visit the link for details.

**Comment by aumeshm** [comment]
@zfcsoftware losing the default flags just to turn off --no-sandbox may be undesirable. What are the implications here of turning off all flags, seeing that's the only way to turn off --no-sandbox right now.

Is it worth to have a param: `enableSandbox`?

**Comment by zfcsoftware** [comment]
> @zfcsoftware losing the default flags just to turn off --no-sandbox may be undesirable. What are the implications here of turning off all flags, seeing that's the only way to turn off --no-sandbox right now.
> 
> Is it worth to have a param: `enableSandbox`?


When running with Docker, the browser cannot start if --no-sandbox is not used. I can't remove it for compatibility reasons. I've added the default arguments below. You can add the following arguments to the args value using ignoreAllFlags.

```
[
  '--disable-extensions',
  '--disable-component-extensions-with-background-pages',
  '--disable-background-networking',
  '--disable-client-side-phishing-detection',
  '--disable-sync',
  '--metrics-recording-only',
  '--disable-default-apps',
  '--mute-audio',
  '--no-default-browser-check',
  '--no-first-run',
  '--disable-backgrounding-occluded-windows',
  '--disable-renderer-backgrounding',
  '--disable-background-timer-throttling',
  '--disable-ipc-flooding-protection',
  '--password-store=basic',
  '--use-mock-keychain',
  '--force-fieldtrials=*BackgroundTracing/default/',
  '--disable-hang-monitor',
  '--disable-prompt-on-repost',
  '--disable-domain-reliability',
  '--propagate-iph-for-testing',
  '--start-maximized',
  '--disable-features=Translate,OptimizationHints,MediaRouter,DialMediaRouteProvider,CalculateNativeWinOcclusion,InterestFeedContentSuggestions,CertificateTransparencyComponentUpdater,AutofillServerCommunication,PrivacySandboxSettings4,AutomationControlled',
  '--no-sandbox'
]
```

**Comment by aumeshm** [comment]
fair enough thank you!

**Comment by zhu659zhu** [comment]
I think 'enableSandbox' option (default false) is better.
If users enable this option, they should understand what will happen.
