### ISSUE TITLE
I'm being detected.

### ISSUE THREAD

**Issue by aguyinmontreal** [zfcsoftware/puppeteer-real-browser#145]
I'm getting detected, and I’m not sure why. My regular browser on the same computer doesn’t trigger anything, but when I use Puppeteer, it does. The only test I pass on my normal browser but fail on Puppeteer is this one: https://fingerprint.com/products/bot-detection/

What is this test looking for that others aren’t?

**Comment by aguyinmontreal** [comment]
@zfcsoftware Would you be able to test it on a Windows computer?

To make sure, I took the exact same code that's shown on your video and ran in on my computer. See below:

![exampleForZFCsoftware (1)](https://github.com/user-attachments/assets/647d5b03-dfc3-46f9-9d8e-2ea1e2ccdb74)

**Comment by aguyinmontreal** [comment]
@zfcsoftware And it's also detected on my second Windows computer

**Comment by aguyinmontreal** [comment]
@zfcsoftware I confirm it's a Windows issue. It's doing the same on a Windows VPS which is on a remote server.

**Comment by zfcsoftware** [comment]
This issue has been fixed. Please test again with the latest version 1.3.5. If the problem persists, I can activate it again if you can post a comment on this topic.

**Comment by aguyinmontreal** [comment]
@zfcsoftware Thank you so much for the fix! Would you be able to explain a little bit what exactly was being detected? Thanks

**Comment by zfcsoftware** [comment]
> @zfcsoftware Thank you so much for the fix! Would you be able to explain a little bit what exactly was being detected? Thanks

You're welcome. The component-update flag was being detected.
https://github.com/zfcsoftware/puppeteer-real-browser/blob/80206e9f246acbe310f3e800340fc7093ee7458f/lib/cjs/index.js#L34
