### ISSUE TITLE
Unsupported `--no-sandbox` flag

### ISSUE THREAD

**Issue by rtritto** [zfcsoftware/puppeteer-real-browser#147]
On browser window there is this message:

```console
You are using an unsupported command-line flag: --no-sandbox. Stabillity and security will suffer.
```

### Info
OS: Windows
Chrome: 125

**Comment by zfcsoftware** [comment]
ignoreAllFlags: true https://github.com/GoogleChrome/chrome-launcher?tab=readme-ov-file#api You can turn it off by adding the defaultFlags here again. However, I cannot turn it off to avoid problems when running with Docker. You can follow the steps I forwarded to turn it off.

**Comment by rtritto** [comment]
The `--no-sandbox` flag should be used **only** with _headless_ mode: https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md#headless

Change:
```diff
chromeFlags: [
-  "--no-sandbox"
+  ...headless==='new' ? ['--no-sandbox'] : []
]
