### ISSUE TITLE
undesired mouse click after cloudflare captcha solved

### ISSUE THREAD

**Issue by crossSiteKikyo** [zfcsoftware/puppeteer-real-browser#149]
[mouse clicked after captcha solved.webm](https://github.com/user-attachments/assets/4aa5262e-e895-450a-84ee-19e77e442a38)

turnstile: true setting, often mouse clicked after cloudflare captcha solved. 
Mouse click same coordiante as the captcha checkbox.

**Comment by Tomsonx232** [comment]
I am seeing this behavior on my crawler too. After captcha is solved it keeps clicking which can be problematic if I'm trying to put in a password after the captcha is solved

**Comment by Tomsonx232** [comment]
here is an example of what I explained in my last comment 
[click-example.webm](https://github.com/user-attachments/assets/134f7290-e67d-4d95-8a57-5e839ba22d3b)

**Comment by crossSiteKikyo** [comment]
it works well. thanks for fix!
