### ISSUE TITLE
Issues with iframes

### ISSUE THREAD

**Issue by aumeshm** [zfcsoftware/puppeteer-real-browser#154]
I have been having a few issues with iframes. Namely, I am able to get the iframe but not able to query anything within it. I even get issues trying to the the iframe.content(). I have looked at many guides, such as https://www.webshare.io/academy-article/puppeteer-iframe#:~:text=Switching%20to%20an%20iFrame,contentFrame()%3B%20await%20page

but have had no luck. Wondering if there's an issue with chrome or puppeteer-core that you may know about.

**Comment by zfcsoftware** [comment]
I can open it again if you can provide information by adding a code where the error can be repeated for testing. Unfortunately, it is not possible to examine an error that I cannot reproduce. There is no known problem. There is no iframe in the https://example.com/ link used in the example on the relevant site. It is normal to get an error.
![image](https://github.com/user-attachments/assets/da4553fe-6046-4a22-87d0-47d0bea13ed4)

**Comment by aumeshm** [comment]
Could we leave this open just for discussion.

I am able to get the iframe element but none of the content underneath it. I was wondering if anyone else was running into iframe issues, and if so what the resolution was. When not using puppeter-real-browser, I did not have issues with iframes.

**Comment by aumeshm** [comment]
Here is the code I used with replaced variable names.

`const frameElementHandle = await page.waitForSelector('#ifrm');
      if (!frameElementHandle) {
        throw new Error('Frame handle missing');
      }
      const frame = await frameElementHandle.contentFrame();
      if (!frame) {
        throw new Error('Frame not found');
      }

      const selectElement = await frame.evaluateHandle(() =>
        document.querySelector('#SelectId'),
      );`

**Comment by aumeshm** [comment]
@zfcsoftware I think this is a real issue, I just tried the same code with only puppeteer-extra-stealth and puppeteer-fingerprint-injector (which runs on chromium) and it worked great.

would love for this to open up to discussion incase anyone else has run into this problem and has fixed it. Contemplating whether it was some of the flags under --args causing this.

**Comment by aumeshm** [comment]
Some additional details. I ran in sandbox, and i added the `IsolateSandboxedIframes` to the disable-features flag. Unfortunately, this did not fix anything.

**Comment by aumeshm** [comment]
Have not been able to repro on a website like "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe", but I am definitely having issues when testing on site (that requires access). Unable to wrap my heard around what settings can cause issues for this package specifically.

**Comment by rtritto** [comment]
Should new page be returned?

Change (draft):
```diff
 browser.on('targetcreated', async target => {
     if (target.type() === 'page') {
-         let newPage = await target.page();
-         pageControllerConfig.page = newPage
-         newPage = await pageController(pageControllerConfig);
+         pageControllerConfig.page = await target.page()
+         const newPage = await pageController(pageControllerConfig)
+         return newPage
```

**Comment by aumeshm** [comment]
@zfcsoftware I think this should be re-opened.

**Comment by zfcsoftware** [comment]
Probably this problem was caused by a low version of puppeteer-core. Recently rebrowser supported higher versions of puppeteer--core. The library has also been updated. This issue should be resolved. If it persists, please provide a code block where I can reproduce the error. Thanks for your feedback.

**Comment by DjSt3rios** [comment]
I also noticed problems with IFrame, and you can use this script below to test it yourself @zfcsoftware 
Note that this works in normal puppeteer.

`import {connect} from "puppeteer-real-browser";

async function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function run() {
    const { page, browser } = await connect({
        headless: 'auto',
        args: ['--disable-search-engine-choice-screen'],
        customConfig: {},
        skipTarget: [],
        fingerprint: false,
        turnstile: true,
        disableXvfb: true,
        connectOption: {
            defaultViewport: null
        },
    });

    await page.goto('https://www.dezlearn.com/nested-iframes-example/', { waitUntil: 'domcontentloaded' });
    const firstIFrame = await page.waitForSelector('iframe', { timeout: 5000 }).catch(() => null);
    await sleep(1000);
    if(!firstIFrame) {
        console.log('IFrame not found');
        await browser.close();
        return;
    }
    const firstIFrameContent = await firstIFrame.contentFrame();
    const secondFrame = firstIFrameContent.childFrames()[0];
    if(!secondFrame) {
        console.log('Second IFrame not found');
        await browser.close();
        return;
    }
    // We search for the button in the second frame
    console.log('Looking for button...');
    const button = await secondFrame.$('button').catch(() => null);
    console.log('This line does not appear');
    if(!button) {
        console.log('Button in second iframe not found!');
        await browser.close();
        return;
    }
    await button.click();
    console.log('It worked!');
    await browser.close();
}


await run();`

**Comment by Omar4GH** [comment]
Facing the same problem too even after updating the library, 
Any element inside an iFrame cannot be accessed or found at all.

**Comment by nikolaosvasileiadis88** [comment]
I have the same issue with iframes

**Comment by nopmal** [comment]
Having the same issue. real-browser isn't solving a turnstile, I believe because its inside of an iframe. Is there any update @zfcsoftware ?

**Comment by nwebson** [comment]
I just fixed the issues with iframes in new version of [rebrowser-patches](https://github.com/rebrowser/rebrowser-patches).
Please use the latest version and `REBROWSER_PATCHES_RUNTIME_FIX_MODE=addBinding`.

**Comment by aumeshm** [comment]
@nwebson You posted this just in time, was in the middle of migrating some stuff to rebrowser :). Thank you. Will lyk if I run into issues here.

**Comment by zfcsoftware** [comment]
This problem should be solved with the new rebrowser update. If the problem persists, please report it here.

**Comment by zfcsoftware** [comment]
> @nwebson You posted this just in time, was in the middle of migrating some stuff to rebrowser :). Thank you. Will lyk if I run into issues here.

If rebrowser solves your problem, I recommend using rebrowser before this library. If you are facing some detection issues like mouse bugs and chromium being used, this library is ideal. Rebrowser gives you more flexibility.

**Comment by nopmal** [comment]
> Having the same issue. real-browser isn't solving a turnstile, I believe because its inside of an iframe. Is there any update @zfcsoftware ?

Still having same issue after updating, it doesn't solve turnstile automatically on 4chan, which is inside an iframe. It works fine on other websitse & the test cases pass.

Reproduction code:
```
import { connect } from "puppeteer-real-browser";

(async() => {
    const { browser, page } = await connect({
        headless: false,
        args: [],
        customConfig: {},
        turnstile: true,
        connectOption: {},
        disableXvfb: false,
        ignoreAllFlags: false
    })
  
    //Goto anime board
    await page.goto('https://boards.4chan.org/a/')

    //Click the `Create Thread` button at top of screen
    await page.evaluate(() => document.getElementsByTagName('a')[90].click())

    //Click `Get Captcha`
    await page.evaluate(() => document.getElementById('t-load').click())

    //The turnstile is now loaded, but not automatically solved :(
})();
```

Any ideas? thx

**Comment by nwebson** [comment]
@nopmal thanks for pointing out this case, was really useful for my research.

@zfcsoftware I would try to do something like that:
```
# current code
const elements = await page.$$('[name="cf-turnstile-response"]');

# my suggestion
for (const frame of page.frames()) {
  const elements = await frame.$$('[name="cf-turnstile-response"]');
}
```

**Comment by Avsy** [comment]
Has anyone found a solution with iframe?
