### ISSUE TITLE
After Turnstile is turned on, small QR codes on non-waf websites will also be automatically clicked by mistake

### ISSUE THREAD

**Issue by CarbonPool** [zfcsoftware/puppeteer-real-browser#155]

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/puppeteer-real-browser/blob/b88c01342628070280abb4e9f6c6a2922ea4fed4/lib/cjs/module/turnstile.js#L12
If it does not meet these conditions, it will not click. I can activate it again when you provide a code that can be regenerated. I did not have a problem this way.

**Comment by CarbonPool** [comment]
One way is to add a list of URL rule parameters, and the URLs in these parameters are not checked.

**Comment by romland** [comment]
This is a closed issue, but I dare say that this check is a pretty big weak spot.

I had a similar problem in that it would find plenty of DIVs that matched the condition, and click and follow a link in said DIV. I want to check for turnstile on all pages, whether I know it's there or not.

In page-context I added a loose check for `iframe`
```javascript
... document.querySelectorAll('div iframe') ...
```
In both places.

I have no idea if this is optimal or whether this will catch all of them but my cursory testing seems okay. Maybe the `iframe` is not always there?
