### ISSUE TITLE
Async call not wait puppeteer.type method

### ISSUE THREAD

**Issue by KiPSOFT** [zfcsoftware/puppeteer-real-browser#158]
Hi,

Async puppetter.type method doesn't wait to finish this call. For example, this code only press 3 or 2 characters and press the Tab key. How's the problem?

<img width="456" alt="image" src="https://github.com/user-attachments/assets/a358b322-123c-489f-a8a8-15423ed5ecf9">

**Comment by zfcsoftware** [comment]
I have bots that work with similar usages. When I test it, type works fine for me. You can try to put 100 ms wait between them.

**Comment by KiPSOFT** [comment]
I tried many different solution but doesnt work. I try to page.type instead of page.keyboard.type this very well work. But some time I getting same issue. I'm using Macos v14 and chrome 128.
