### ISSUE TITLE
The test does not start

### ISSUE THREAD

**Issue by pichardonuba** [zfcsoftware/puppeteer-real-browser#16]
SO: Ubuntu 22.04.3 LTS
installed xvfb

I clone the repository, run **npm i** and **node ./src/test** and it doesn't work, no console errors. Thank you

**Comment by zfcsoftware** [comment]
Hi, are you using ubundu desktop or just console? Do you get a timeout error when you wait? Have you tried to install npm with puppeteer-real-browser and run the example in the readme file?

**Comment by pichardonuba** [comment]
Hi,
are you using ubundu desktop or just console?
**Desktop**
Do you get a timeout error when you wait?
**10 minutes waiting and no response**
Have you tried to install npm with puppeteer-real-browser and run the example in the readme file?
Yes,

```
import { connect } from 'puppeteer-real-browser'

connect({
    headless: 'auto',
    args: [],
    customConfig: {},
    skipTarget: [],
    fingerprint: true,
    turnstile: true,
    connectOption: {},
    tf: true,

})
.then(async response => {
    console.log('response', response);
    const {browser, page} = response
    await page.goto('www.google.com')
    
})
.catch(error=>{
    console.log(error.message)
})
```
it does not work

Screenshot:
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/41807742/c9981f65-41e3-4668-a309-3eccefb63c1f)

Thank you.

**Comment by zfcsoftware** [comment]
> Hi, are you using ubundu desktop or just console? **Desktop** Do you get a timeout error when you wait? **10 minutes waiting and no response** Have you tried to install npm with puppeteer-real-browser and run the example in the readme file? **Yes,**
> 
> ```
> import { connect } from 'puppeteer-real-browser'
> 
> connect({
>     headless: 'auto',
>     args: [],
>     customConfig: {},
>     skipTarget: [],
>     fingerprint: true,
>     turnstile: true,
>     connectOption: {},
>     tf: true,
> 
> })
> .then(async response => {
>     console.log('response', response);
>     const {browser, page} = response
>     await page.goto('www.google.com')
>     
> })
> .catch(error=>{
>     console.log(error.message)
> })
> ```
> 
> it does not work
> 
> Screenshot: ![image](https://private-user-images.githubusercontent.com/41807742/308316478-c9981f65-41e3-4668-a309-3eccefb63c1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNjQ5NDgsIm5iZiI6MTcwOTA2NDY0OCwicGF0aCI6Ii80MTgwNzc0Mi8zMDgzMTY0NzgtYzk5ODFmNjUtNDFlMy00NjY4LWEzMDktM2VjY2VmYjYzYzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDIwMTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyOGExYTQzM2IyZTM5Y2MxNThlMzJkODRlNTNjMDI5YjNmYTgyMjVkZjEyMmIxZGEwMjBkMmUwNzkwMzBiNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bWILjRTZTNFLByQTzRNPbriITdjvth051b39-9YqhjM)
> 
> Thank you.
xvfb creates a virtual screen so the browser will not be visible. using this code you can take 1 screenshot per second from the page and see how it works. 
```
import { connect } from 'puppeteer-real-browser'

connect({
    headless: 'auto',
    args: [],
    customConfig: {},
    skipTarget: [],
    fingerprint: true,
    turnstile: true,
    connectOption: {},
    tf: true,

})
    .then(async response => {
        // console.log('response', response);
        const { browser, page } = response
        setInterval(() => {
            page.screenshot({ path: 'example.png' });
        }, 1000);
        await page.goto('https://www.google.com')

    })
    .catch(error => {
        console.log(error.message)
    })
```
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/fea1e505-8c55-4148-9fb6-060c8722309f)

**Comment by pichardonuba** [comment]
Thanks, I also tried that code and it doesn't work. There is no output in the console or screenshots. I have tried different codes and there is never any output in the console even putting logs in the .then and the .catch

**package.json**
```
{
  "name": "puppeteer-real-browser",
  "version": "1.2.5",
  "description": "This package is designed to bypass puppeteer's bot-detecting captchas such as Cloudflare. It acts like a real browser and can be managed with puppeteer.",
  "type": "module",
  "exports": "./src/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "cf-bypass",
    "cloudflare-bypass",
    "puppeteer-fingerprint",
    "puppeteer-cloudflare",
    "puppeteer-real-browser",
    "undetectable-puppeteer",
    "undetect",
    "undetectable",
    "puppeteer-undetectable",
    "puppeteer-undetect",
    "puppeteer-undetectable-bypass",
    "puppeteer-undetect-bypass",
    "puppeteer-undetectable-cloudflare",
    "puppeteer-undetect-cloudflare",
    "puppeteer-undetectable-cf",
    "puppeteer-undetect-cf",
    "puppeteer-undetectable-cf-bypass"
  ],
  "author": "zfc-software",
  "license": "ISC",
  "dependencies": {
    "@sparticuz/chromium": "^119.0.2",
    "axios": "^1.6.7",
    "chrome-launcher": "^1.1.0",
    "chrome-remote-interface": "^0.33.0",
    "cli-color": "^2.0.3",
    "puppeteer": "^21.11.0",
    "puppeteer-afp": "^1.0.5",
    "puppeteer-extra": "^3.3.6",
    "puppeteer-real-browser": "^1.2.5",
    "xvfb": "^0.4.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/zfcsoftware/puppeteer-real-browser"
  },
  "readme": "README.md",
  "homepage": "https://github.com/zfcsoftware/puppeteer-real-browser"
}
```

**Comment by zfcsoftware** [comment]
> Thanks, I also tried that code and it doesn't work. There is no output in the console or screenshots. I have tried different codes and there is never any output in the console even putting logs in the .then and the .catch
> 
> **package.json**
> 
> ```
> {
>   "name": "puppeteer-real-browser",
>   "version": "1.2.5",
>   "description": "This package is designed to bypass puppeteer's bot-detecting captchas such as Cloudflare. It acts like a real browser and can be managed with puppeteer.",
>   "type": "module",
>   "exports": "./src/index.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "keywords": [
>     "cf-bypass",
>     "cloudflare-bypass",
>     "puppeteer-fingerprint",
>     "puppeteer-cloudflare",
>     "puppeteer-real-browser",
>     "undetectable-puppeteer",
>     "undetect",
>     "undetectable",
>     "puppeteer-undetectable",
>     "puppeteer-undetect",
>     "puppeteer-undetectable-bypass",
>     "puppeteer-undetect-bypass",
>     "puppeteer-undetectable-cloudflare",
>     "puppeteer-undetect-cloudflare",
>     "puppeteer-undetectable-cf",
>     "puppeteer-undetect-cf",
>     "puppeteer-undetectable-cf-bypass"
>   ],
>   "author": "zfc-software",
>   "license": "ISC",
>   "dependencies": {
>     "@sparticuz/chromium": "^119.0.2",
>     "axios": "^1.6.7",
>     "chrome-launcher": "^1.1.0",
>     "chrome-remote-interface": "^0.33.0",
>     "cli-color": "^2.0.3",
>     "puppeteer": "^21.11.0",
>     "puppeteer-afp": "^1.0.5",
>     "puppeteer-extra": "^3.3.6",
>     "puppeteer-real-browser": "^1.2.5",
>     "xvfb": "^0.4.0"
>   },
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/zfcsoftware/puppeteer-real-browser"
>   },
>   "readme": "README.md",
>   "homepage": "https://github.com/zfcsoftware/puppeteer-real-browser"
> }
> ```

Can you add a video? Can you add a video of your code and your execution
