### ISSUE TITLE
browserWSEndpoint issue

### ISSUE THREAD

**Issue by roborock** [zfcsoftware/puppeteer-real-browser#161]
can we  define  "browserWSEndpoint " param to connect property 

my purpose use  remote ws endpoint

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/puppeteer-real-browser/blob/4997873f81c7622cdea93256eb13c644da053657/lib/cjs/index.js#L56
For this you need to edit the library. You can create a fork and return the link above and use it.
