### ISSUE TITLE
Context connection errors

### ISSUE THREAD

**Issue by bernatvadell** [zfcsoftware/puppeteer-real-browser#162]
Hi,

I'm trying out the library, and I've found some "random" but fairly frequent errors.

```
file:///app/node_modules/.pnpm/puppeteer-core-patch@1.0.1/node_modules/puppeteer-core-patch/lib/esm/puppeteer/cdp/FrameManager.js:429
                .then(({ executionContextId }) => {
                         ^

TypeError: Cannot destructure property 'executionContextId' of 'undefined' as it is undefined.
    at file:///app/node_modules/.pnpm/puppeteer-core-patch@1.0.1/node_modules/puppeteer-core-patch/lib/esm/puppeteer/cdp/FrameManager.js:429:26
    at async Promise.all (index 0)
    at async #createIsolatedWorld (file:///app/node_modules/.pnpm/puppeteer-core-patch@1.0.1/node_modules/puppeteer-core-patch/lib/esm/puppeteer/cdp/FrameManager.js:415:9)
    at async Promise.all (index 4)
    at async FrameManager.initialize (file:///app/node_modules/.pnpm/puppeteer-core-patch@1.0.1/node_modules/puppeteer-core-patch/lib/esm/puppeteer/cdp/FrameManager.js:170:13)
```

```
Page.createIsolatedWorld timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
```

```
net::ERR_ABORTED at https://xxxx.yyy
```

```
net::ERR_INSUFFICIENT_RESOURCES at https://xxxx.yyy
```

```
Navigation timeout of 30000 ms exceeded
```

any ideas?

**Comment by thucvu97** [comment]
hi @bernatvadell What is the code you are using that causes the above error?

**Comment by bernatvadell** [comment]
Hi!

This is my code (although errors are generated randomly):

```
const response = await context.page.goto(instruction.params.url, {
          waitUntil: "load",
        });

produces:
file:///app/node_modules/.pnpm/puppeteer-core-patch@1.0.1/node_modules/puppeteer-core-patch/lib/esm/puppeteer/cdp/FrameManager.js:429
                .then(({ executionContextId }) => {
                         ^

TypeError: Cannot destructure property 'executionContextId' of 'undefined' as it is undefined.
    at file:///app/node_modules/.pnpm/puppeteer-core-patch@1.0.1/node_modules/puppeteer-core-patch/lib/esm/puppeteer/cdp/FrameManager.js:429:26
    at async Promise.all (index 0)
    at async #createIsolatedWorld (file:///app/node_modules/.pnpm/puppeteer-core-patch@1.0.1/node_modules/puppeteer-core-patch/lib/esm/puppeteer/cdp/FrameManager.js:415:9)
    at async Promise.all (index 4)
    at async FrameManager.initialize (file:///app/node_modules/.pnpm/puppeteer-core-patch@1.0.1/node_modules/puppeteer-core-patch/lib/esm/puppeteer/cdp/FrameManager.js:170:13)

or

TimeoutError: Navigation timeout of 30000 ms exceeded
```

**Comment by vootsman** [comment]
I also started getting the same error (didn't occur with the previous version)

file://...../node_modules/puppeteer-core-patch/lib/esm/puppeteer/cdp/FrameManager.js:429
                .then(({ executionContextId }) => {
                         ^

TypeError: Cannot destructure property 'executionContextId' of 'undefined' as it is undefined.

**Comment by thucvu97** [comment]
@vootsman 
Because the new version has updated the ppt patch, many errors occur. Please share the code where the above error occurs to make it easier to check.

**Comment by Zvih** [comment]
@zfcsoftware I encountered this issue with headless: false, and it's a bit random when you move with goTo to other page. That's why I removed the library from the project for now. However, you did great job.
The other value for the headless parameter (true, new etc.) was mentioned to quickly reproduce the issue

**Comment by bernatvadell** [comment]
yes, we are using headless to false

**Comment by petar-ps** [comment]
Tried with alpine, tried with dockerfile provides here on github, the same results. It does not work...
Basic page.goto does not work

**Comment by petar-ps** [comment]
I get this error on Docker if try to use `defaultViewport `or `page.setViewport`. 
On windows everything is fine.

Btw turnstile bypass does not work on Docker but it works on Windows i dont know why.

**Comment by bernatvadell** [comment]
I have reviewed a few things that could affect resource consumption:

- An xvfb session is initialized every time I create a browser instance.
- The "pageController" function creates as many "disconnected" events as pages are created.

**Comment by attilanyers** [comment]
I got the same error, with headless: true after trying to restore browser state from another session. What is the proper way to save the whole state and reload it? I save cookies, localStorage and sessionStorage

**Comment by vootsman** [comment]
> @vootsman Because the new version has updated the ppt patch, many errors occur. Please share the code where the above error occurs to make it easier to check.

I use the connect method to create a page, but I actually do the actual using of the browser by hand, so it sometimes works for hours, other times it crashes sooner (with the above error)

**Comment by zfcsoftware** [comment]
Can you try again with the latest version?

**Comment by vootsman** [comment]
> Can you try again with the latest version?

I've been using for ~30 minutes with no crashes, so I'll call it success for now

**Comment by Zvih** [comment]
It seems issue gone, at least for now. Great work
