### ISSUE TITLE
Using existing profile

### ISSUE THREAD

**Issue by TovioNieminen** [zfcsoftware/puppeteer-real-browser#165]
As you can see in my code, I wroute `/` instead `\\`

```
customConfig:{
    chromePath:"C:/Program Files/Google/Chrome/Application/chrome.exe",
    userDataDir: "C:/Users/Administrator/AppData/Local/Google/Chrome/User Data/Profile 15",
}
```
But the puppeteer browser is opened without my existing profile
I wanna open a browser with existing profile which has several chrome extensions.

**Comment by zfcsoftware** [comment]
https://github.com/GoogleChrome/chrome-launcher
The library uses this repository for the profile structure. puppeteer-real-browser has no effect on the profile system. I suggest you open the issue in this repository.  I'll close it as it's not related to this library, thanks for your feedback.

**Comment by younes-zeboudj** [comment]
I have the same issue where history is not saved when I used `--user-data-dir`

**Comment by younes-zeboudj** [comment]
for some reason, the library `chrome-launcher` is ignoring the flag `--user-data-dir`, using the library's `userDataDir` argument fixes the issue, I had to modify the `puppeteer-real-browser` package code to mitigate the issue
