### ISSUE TITLE
recaptcha plugin not working in new version of puppeteer-real-browser?

### ISSUE THREAD

**Issue by Roichue** [zfcsoftware/puppeteer-real-browser#166]
I add the recaptcha plugin to the plugins section, but when I use page.solveRecaptchas();, I unexpectedly receive the Error: TimeoutError: Waiting failed: 10000ms exceeded error.

Or sometimes it doesn't give an error but it doesn't solve the captcha. The same code was fine in older versions.

There was no such problem in the old version when we integrated it directly into the index.js file. But now I need to switch to the new version and there is a problem.

```
const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha');

const { page, browser } = await connect({
        tf: false, 
        turnstile: true,
        args: [
          '--aggressive-cache-discard',
          '--disable-cache',
          '--lang=en-US',
          '--intl.accept_languages=en-US',    
        ],
        headless: 'auto', 
        customConfig: {},
        skipTarget: [],
        fingerprint: true,
        turnstile: true,
        connectOption: {},
        plugins: [
          RecaptchaPlugin({
            provider: {
              id: '2captcha',
              token: apiKey,
            },
            visualFeedback: true,
            throwOnError: true
          })
        ]
      });```

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/puppeteer-real-browser/issues/32#issuecomment-2338933954
If the problem persists, simply report it here.
