### ISSUE TITLE
Turnstile bypass does not work on Docker

### ISSUE THREAD

**Issue by petar-ps** [zfcsoftware/puppeteer-real-browser#167]
It seems that cloudflare turnsitle bypass is not working on Docker. It just does not check it.
Working on windows.
1.3.9 version with headless:false
Example site freebitcoin:
![image](https://github.com/user-attachments/assets/90922c8e-4738-4b4a-a2b0-c6e962216be5)

**Comment by zfcsoftware** [comment]
It works, but the site has increased the width of the div containing the Cloudflare Captcha. For this reason, it clicks in the wrong place. Since the solving system cannot be integrated into every css changing site, you need to update it.
For example, for the password reset page, you can make the width of the div covering the Turnstile 300px as below.
`document.querySelector("#forgot_password_cf_turnstile > div").setAttribute('style','width:300px')`

![image](https://github.com/user-attachments/assets/2d330a93-7548-4be8-9a42-fad39fcf0e03)

**Comment by petar-ps** [comment]
So

> It works, but the site has increased the width of the div containing the Cloudflare Captcha. For this reason, it clicks in the wrong place. Since the solving system cannot be integrated into every css changing site, you need to update it. For example, for the password reset page, you can make the width of the div covering the Turnstile 300px as below. `document.querySelector("#forgot_password_cf_turnstile > div").setAttribute('style','width:300px')`
> 
> ![image](https://private-user-images.githubusercontent.com/123484092/365372988-2d330a93-7548-4be8-9a42-fad39fcf0e03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MzI0NTcsIm5iZiI6MTcyNTczMjE1NywicGF0aCI6Ii8xMjM0ODQwOTIvMzY1MzcyOTg4LTJkMzMwYTkzLTc1NDgtNGJlOC05YTQyLWZhZDM5ZmNmMGUwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QxODAyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTNjZDUxM2QxZTBkNzIxNzRlMzBiMGVmY2NlYjExMWRhNjY2OWZhYjg0M2VkYWIxMWQzZGZhNzkzOTQ2MDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xs5YHjPBdmrNKsg64Yhv_VsdzBH9DppC3XBmPwZZSBY)

Sorry but this is not the issue. On windows machine is working.
I added the "fix" but its the same. Its not working

**Comment by zfcsoftware** [comment]
> So
> 
> > It works, but the site has increased the width of the div containing the Cloudflare Captcha. For this reason, it clicks in the wrong place. Since the solving system cannot be integrated into every css changing site, you need to update it. For example, for the password reset page, you can make the width of the div covering the Turnstile 300px as below. `document.querySelector("#forgot_password_cf_turnstile > div").setAttribute('style','width:300px')`
> > ![image](https://private-user-images.githubusercontent.com/123484092/365372988-2d330a93-7548-4be8-9a42-fad39fcf0e03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MzI0NTcsIm5iZiI6MTcyNTczMjE1NywicGF0aCI6Ii8xMjM0ODQwOTIvMzY1MzcyOTg4LTJkMzMwYTkzLTc1NDgtNGJlOC05YTQyLWZhZDM5ZmNmMGUwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QxODAyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTNjZDUxM2QxZTBkNzIxNzRlMzBiMGVmY2NlYjExMWRhNjY2OWZhYjg0M2VkYWIxMWQzZGZhNzkzOTQ2MDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xs5YHjPBdmrNKsg64Yhv_VsdzBH9DppC3XBmPwZZSBY)
> 
> Sorry but this is not the issue. On windows machine is working. I added the "fix" but its the same. Its not working on Docker

Can you provide a code example that can reproduce this error?

**Comment by petar-ps** [comment]
Just login with any email and password and and load the home page. It wont check the captcha
