### ISSUE TITLE
Using fingerprints is actually worse than using a normal browser?

### ISSUE THREAD

**Issue by marcusdiy** [zfcsoftware/puppeteer-real-browser#17]
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/42746781/0056b82a-2f2e-4a4f-a7b8-0ede95d47a11)

Thanks for the work you are doing. Just trying to help with some testing. Anyway creeper.js doesnt pass.
The fingerprint should try to give realistic numbers. Just inspect the lies detected 😉

For example its bad to just use Math.random() to specify the amount of ram.
```
`Object.defineProperty(navigator, 'deviceMemory', {get: () => Math.floor(Math.random() * 8) + 4, });`
```

Better give some realistic values
```
function randomEl(array) { let ridx = parseInt(array.length * Math.random()); return array[ridx]; }
randomEl([4,8,16,32])
```

**Comment by zfcsoftware** [comment]
Thank you for your contributions. I updated it, can you check again?

**Comment by zfcsoftware** [comment]
> creeper.js

![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/02fc3b84-725e-4a6e-96f9-6499b10f91ef)
Sites like these can also call our own browser fake. For example, when I tested my own browser, it gave me bad scores. 
Gmail login
cloudflare captcha
I think it's a better control to work in places like this.

**Comment by bernatixer** [comment]
I still get this on creepjs, is there any changes you did to pass it?
