### ISSUE TITLE
quick question:  "--disable-features=IsolateOrigins,site-per-process"

### ISSUE THREAD

**Issue by aguyinmontreal** [zfcsoftware/puppeteer-real-browser#170]
Is there a specific reason why `IsolateOrigins` and `site-per-process` are not disabled in puppeteer-real-browser?

Thanks!

**Comment by zfcsoftware** [comment]
Hello, the library is detected when such flags are added. Since it becomes very difficult to detect when the runtime is turned off, bot detection systems now try to proceed through the added flags. When those flags were added, they were not added because the tests failed.
