### ISSUE TITLE
Run in Raspbian

### ISSUE THREAD

**Issue by matigarowel** [zfcsoftware/puppeteer-real-browser#172]
How to setup it on raspbian OS? I already run this command **sudo apt-get install xvfb**

**Comment by BRAVO68WEB** [comment]
@matigarowel How did you manage to run it?

I am using RPI 5

OS Info
```
Distributor ID: Ubuntu
Description:    Ubuntu 24.10
Release:        24.10
Codename:       oracular
```

OS Edition : Ubuntu Server 24.10
