### ISSUE TITLE
Can't get window instance after page load

### ISSUE THREAD

**Issue by pwnz22** [zfcsoftware/puppeteer-real-browser#173]
Hey!

I'm trying to get the `window` instance after page `page.waitForNavigation` but the window is `undefined`. 

```
PAGE_PUPPETEER_OPTS = {
  networkIdle2Timeout: 5000,
  waitUntil: 'networkidle0',
  timeout: 3000000,
};
await page.waitForNavigation({ waitUntil: 'domcontentloaded' });
// await page.waitForFunction(() => window.__NUXT__ !== undefined);
// await page.waitForSelector('#__nuxt');
const windowObject = await page.evaluate(() => {
  return window.__NUXT__;
});

console.log(windowObject);
```
result is `undefined` or catching `timeout`

**Comment by nwebson** [comment]
Please follow https://github.com/rebrowser/rebrowser-patches/issues/13 - it's exactly the same issue.
I'm gonna post a solution for this issue probably this week.

**Comment by jarmo-fi** [comment]
Also page.evaluateOnNewDocument code is never executed. I wonder if it is related problem and will get fixed with fix for page.evaluate() or is it separate issue?

**Comment by nwebson** [comment]
@jarmo-fi evaluateOnNewDocument works fine in rebrowser-patches, so it might be something related to puppeteer-real-browser
cc @zfcsoftware

**Comment by jarmo-fi** [comment]
@nwebson tested rebrowser and looks like it indeed works, but only with env variable
REBROWSER_PATCHES_RUNTIME_FIX_MODE=enableDisable
So this could be also isolation problem.
cc @zfcsoftware

**Comment by nwebson** [comment]
@jarmo-fi Could you please share your code so I can tested it locally?

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/puppeteer-real-browser/tree/access-window
https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#i-cannot-access-functions-in-window-object-what-should-i-do

Hi, I added a branch for this. You can access it using the example there. If I find a better method in the future, I will add it.

**Comment by jarmo-fi** [comment]
@zfcsoftware for me the suggested solution does not work as I need to be able to call a function (which I have injected earlier) in the page. 

So for function calling there is no way currently in puppeteer-real-browser? As said, this works fine with  std puppeteer + rebrowser-puppeteer with environment variable REBROWSER_PATCHES_RUNTIME_FIX_MODE=enableDisable.
Maybe something similar could be implemented to puppeteer-real-browser too? I'd prefer to use puppeteer-real-browser as it can access cloudflare sites while rebrowser cannot.

Also I tried to use puppeteer-real-browser side-by-side with rebrowser-puppeteer for my different usecases, but looks like puppeteer-real-browser somehow takes over and the evaluate does not work even when puppeteer is later started by rebrowser

@nwebson my code is way too complicated (and private) to be copied here. But what exact code part you are looking for? In short I launch rebrowser-puppeteer normally and all the evaluate and evaluateOnNewDocument functions work the same as in normal puppeteer. But only if REBROWSER_PATCHES_RUNTIME_FIX_MODE=enableDisable and set before app is launched

**Comment by pwnz22** [comment]
> https://github.com/zfcsoftware/puppeteer-real-browser/tree/access-window https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#i-cannot-access-functions-in-window-object-what-should-i-do
> 
> Hi, I added a branch for this. You can access it using the example there. If I find a better method in the future, I will add it.

Sorry, but i dont understand this use case. What javascript i must add to access it? In my page i also have javascript that is nuxt in script tag. I have access to it in Devtools like so:
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/99dfdce0-e101-4353-9808-0d813df86c02">
but not when using puppeteer-real-browser

**Comment by zfcsoftware** [comment]
> @zfcsoftware for me the suggested solution does not work as I need to be able to call a function (which I have injected earlier) in the page.
> 
> So for function calling there is no way currently in puppeteer-real-browser? As said, this works fine with std puppeteer + rebrowser-puppeteer with environment variable REBROWSER_PATCHES_RUNTIME_FIX_MODE=enableDisable. Maybe something similar could be implemented to puppeteer-real-browser too? I'd prefer to use puppeteer-real-browser as it can access cloudflare sites while rebrowser cannot.
> 
> Also I tried to use puppeteer-real-browser side-by-side with rebrowser-puppeteer for my different usecases, but looks like puppeteer-real-browser somehow takes over and the evaluate does not work even when puppeteer is later started by rebrowser
> 
> @nwebson my code is way too complicated (and private) to be copied here. But what exact code part you are looking for? In short I launch rebrowser-puppeteer normally and all the evaluate and evaluateOnNewDocument functions work the same as in normal puppeteer. But only if REBROWSER_PATCHES_RUNTIME_FIX_MODE=enableDisable and set before app is launched



> > https://github.com/zfcsoftware/puppeteer-real-browser/tree/access-window https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#i-cannot-access-functions-in-window-object-what-should-i-do
> > Hi, I added a branch for this. You can access it using the example there. If I find a better method in the future, I will add it.
> 
> @zfcsoftware Sorry, but i dont understand this use case. What javascript i must add to access it? In my page i also have javascript that is nuxt in script tag. I have access to it in Devtools like so: <img alt="image" width="1051" src="https://private-user-images.githubusercontent.com/13133678/369683328-99dfdce0-e101-4353-9808-0d813df86c02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODU0ODcsIm5iZiI6MTcyNzA4NTE4NywicGF0aCI6Ii8xMzEzMzY3OC8zNjk2ODMzMjgtOTlkZmRjZTAtZTEwMS00MzUzLTk4MDgtMGQ4MTNkZjg2YzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA5NTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxNTVlNjZiODQyOWY2MDZhNmQyMWY1NTU1Njg1NTA2M2VlOTU3NDhhMzljMzg3MTZhNGUyZTY1NmNkZjI4ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.enEL0CAnfytj2zfofwMJDi-nLYzoKQKpN6vIDjK9K_A"> but not when using puppeteer-real-browser

I added a new test, please check it. It is possible to access the whole window object with the related method.

https://github.com/zfcsoftware/puppeteer-real-browser/blob/access-window/success2.js
https://github.com/user-attachments/assets/b31df979-d783-4a33-a4f8-331f0345db41

**Comment by jarmo-fi** [comment]
> @zfcsoftware I added a new test, please check it. It is possible to access the whole window object with the related method.
> 
> https://github.com/zfcsoftware/puppeteer-real-browser/blob/access-window/success2.js
> 

Your code seems to inject function to the page to store some value to field. And the field + value is then accessible using evaluate function. But I still do not see how to call a JS function in page from node. I am not looking to get any values from the page but specifically I have to call JS function several times in a row AFTER the page have loaded and the Cloudflare tests are passed.

And as I said, this works fine in normal puppeteer and in rebrowser-puppeteer with REBROWSER_PATCHES_RUNTIME_FIX_MODE=enableDisable env variable.

Any possibility to get such REBROWSER_PATCHES_RUNTIME_FIX_MODE=enableDisable functionality to the puppeteer-real-browser? This would be great as then it could be used as real replacement for puppeteer

Attached are my samples
One for puppeteer - tests pass + console logging works
One for rebrowser-puppeteer - no console logging, but tests pass if I start it like this:
export REBROWSER_PATCHES_RUNTIME_FIX_MODE="enableDisable"; node functiontest-rebrowser.js 
And one for puppeteer-real-browser - tests fail + no console logging

It would be really great to get this working. As we can see it should be possible the same way as rebrowser does it.
[tests.zip](https://github.com/user-attachments/files/17101710/tests.zip)

**Comment by zfcsoftware** [comment]
> REBROWSER_PATCHES_RUNTIME_FIX_MODE

REBROWSER_PATCHES_RUNTIME_FIX_MODE I'll update REBROWSER_PATCHES_RUNTIME_FIX_MODE to changeable, I think that should solve your problem.

**Comment by pwnz22** [comment]
I get it, now it's working. Thanks)

**Comment by jarmo-fi** [comment]
> > REBROWSER_PATCHES_RUNTIME_FIX_MODE
> 
> REBROWSER_PATCHES_RUNTIME_FIX_MODE I'll update REBROWSER_PATCHES_RUNTIME_FIX_MODE to changeable, I think that should solve your problem.

@zfcsoftware Yes, I think so. Please let us know when this code change is in place. Looks like very small change to set the environment variable REBROWSER_PATCHES_RUNTIME_FIX_MODE only if it is not already set

**Comment by pwnz22** [comment]
@zfcsoftware when i use `createCDPSession` with proxy i'm getting `Error: net::ERR_INVALID_AUTH_CREDENTIALS`

**Comment by nwebson** [comment]
I would suggest using `REBROWSER_PATCHES_RUNTIME_FIX_MODE=alwaysIsolated` as it's more secure and stable.

📣 I just made a post how to access main world objects from isolated context, please read it here: [How to Access Main Context Objects from Isolated Context in Puppeteer & Playwright](https://rebrowser.net/blog/how-to-access-main-context-objects-from-isolated-context-in-puppeteer-and-playwright-23741)

ℹ️ TLDR: use `page.evaluateOnNewDocument` to listen for window messages and eval code, use `page.evaluate` to send window message with your payload and get response from the main world.
It worked just fine for several clients of mine, please let me know (discord or here) if it doesn't work for you.

**Comment by jarmo-fi** [comment]
@nwebson Thanks for the article! This looks very interesting. I will check and test how to use this logic.

**Comment by jarmo-fi** [comment]
@nwebson This works nicely. Thanks!

@zfcsoftware So no need for me REBROWSER_PATCHES_RUNTIME_FIX_MODE=enableDisable

Are Events safer than somewhat simpler BroadcastChannel for bot detection?

**Comment by pwnz22** [comment]
@nwebson I'm new to this and didn't understand how to use your approach to get `window.__NUXT__`. Can you please give some examples.

**Comment by nwebson** [comment]
@jarmo-fi I'm glad it worked! 🎉 

@pwnz22 just use the code from the article, but instead of
```
await page.evaluate(() => window.evaluateMain(() => document.getElementsByClassName('div'))
```
use 
```
await page.evaluate(() => window.evaluateMain(() => window.__NUXT__)
```

**Comment by pwnz22** [comment]
@nwebson It's working. Many Thanks)
