### ISSUE TITLE
Accessing iFrame Content only works with"'--disable-web-security'".

### ISSUE THREAD

**Issue by Omar4GH** [zfcsoftware/puppeteer-real-browser#175]
Accessing iFrame content with code like 
`const frameHandle = await page.waitForSelector("iframe.credit-card-iframe");`
  `const frame = await frameHandle.contentFrame();`
  `const cvvInput = await frame.waitForSelector("#cvNumber"); `
  
The Same code works with normal Puppeteer. But not using this library.
  
The ONLY way i got to access the content of the iFrame is using this method : 
`  await page.evaluate(() => {`
 `   const iframe = document.querySelector("iframe.credit-card-iframe");`
  `  const innerDoc = iframe.contentDocument || iframe.contentWindow.document;`
  `  const cvvInput = innerDoc.querySelector("#cvNumber");`
  `  if (cvvInput) {`
  `    cvvInput.value = "123";`
  `  }`
 ` });`  
  
 Which is fine, but it ONLY works with the flag "'--disable-web-security'".
 
 Any way to make this work without '--disable-web-security' ? or Make it work with contentFrame() ?

**Comment by zfcsoftware** [comment]
Since it's the same problem as here and it's older, I turn it on and turn this one off. Thank you for the problem. I will investigate this issue, for now you can access it with the chrome plugin.
https://github.com/zfcsoftware/puppeteer-real-browser/issues/154
