### ISSUE TITLE
Isssue when closing page or browser

### ISSUE THREAD

**Issue by RubberArchind** [zfcsoftware/puppeteer-real-browser#177]
**Describe the bug**
Can't close page or browser when using a proxy, it always throw error even with minimal code

**To Reproduce**
import { connect } from "puppeteer-real-browser";

const { page, browser } = await connect({
    args: ['--no-sandbox', "--start-maximized"],
    connectOption: {
        defaultViewport: null,
    },
    proxy: {
        host: "gw.dataimpulse.com",
        port: 823,
        username: "myusername",
        password: "mypassword"
    }
})

await page.goto('http://google.com/');
browser.close()

**Expected behavior**
successfully close the page and browser without error

**Screenshots**
![image](https://github.com/user-attachments/assets/54e24eed-fd93-42b7-ac4a-12c51ed91d58)

**Desktop (please complete the following information):**
 - OS:  Ubuntu 
 - Browser Google Chrome 129.0.6668.58 (installed via apt install google-chrome-stable)
 - Version 20.04.6 LTS

**Additional context**
this just happened in linux, i try this in windows and it run perfectly

**Comment by zfcsoftware** [comment]
Can you check with the latest version?

**Comment by RubberArchind** [comment]
Of course, I will try it after this and give you the result here.

**Comment by RubberArchind** [comment]
Ok, the last commit seems to fix the problem, it works fine now. Thanks a lot @zfcsoftware
