### ISSUE TITLE
Auto proxy not working

### ISSUE THREAD

**Issue by barutlift** [zfcsoftware/puppeteer-real-browser#178]
why its not working but when i fill proxy with manuel its working but not automaticly

const { connect } = require("puppeteer-real-browser");
const fs = require("fs");

async function delay(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function getRandomProxy() {
    const proxies = fs.readFileSync("proxies.txt", "utf-8").trim().split("\n");
    const randomProxy = proxies[Math.floor(Math.random() * proxies.length)].split(":");
    return {
        host: randomProxy[0],
        port: parseInt(randomProxy[1]),
        username: randomProxy[2],
        password: randomProxy[3]
    };
}

async function test() {
    const { host, port, username, password } = await getRandomProxy();
    
    const { browser, page } = await connect({
        headless: false,
        args: [],
        customConfig: {},
        turnstile: true,
        connectOption: {},
        disableXvfb: false,
        ignoreAllFlags: false,
        proxy: {
            host: host,
            port: port,
            username: username,
            password: password
        }
    });

**Comment by zfcsoftware** [comment]
This is probably caused by characters like \r or \t in the text in the txt. puppeteer-real-browser is not the problem so I'm turning it off. you can clean it with a code like text.replace(/\r/g,'').replace(/\t/g,'').
