### ISSUE TITLE
flawless

### ISSUE THREAD

**Issue by hfzi** [zfcsoftware/puppeteer-real-browser#179]
**Describe the bug**
Nothing

It's a really excellent package, it works very well to bypass cloudflare and get cookies. I'm wondering one small thing, is it possible to make a google recaptcha solver, recaptcha bypass services are very expensive.

I'm using for crawl serp and shbndn.com

Good job knks.

**Comment by zfcsoftware** [comment]
Hello,
For recaptcha v2 you need an image recognition api. For Recaptcha v3 this library is suitable.
https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#httpsantcptcomscore_detector-recaptcha-v3-detects-me-what-should-i-do
You can get 0.9 points from recaptcha v3 by following the detail here. However, I'm not planning to build a new library on top of this at the moment, maybe in the future. 

If you want to create and use it yourself, you can get 0.9 points by adding the user-data-dir flag.

**Comment by hfzi** [comment]
I think my identity will be contaminated when I use user data. The proxy ip's I use have a dirty history. Thanks
