### ISSUE TITLE
Compilation error when using with Typesript

### ISSUE THREAD

**Issue by jarmo-fi** [zfcsoftware/puppeteer-real-browser#180]
### Description

There is compilation error when importing connect from puppeteer-real-browser
Cannot find module 'puppeteer-core-patch' or its corresponding type declarations.

pointing to the second line in typings.d.ts:
declare module "puppeteer-real-browser" {
	import type { Browser, Page } from "puppeteer-core-patch";

I wonder if this is correct import in the puppeteer-real-browser and if yes, then I guess the puppeteer-core-patch should be listed in puppeteer-real-browser dependencies

### Full steps to reproduce the issue

Just import the connect routine in ts-file
import { connect } from 'puppeteer-real-browser';

### Issue Type

Bug, Build/Install

### Operating System

Linux, Mac OS

### Do you use Docker?

None

**Comment by zfcsoftware** [comment]
Can you try again with the latest version?

**Comment by seongbeom** [comment]
after update then
```
src/index.ts:473:21 - error TS2339: Property 'realCursor' does not exist on type 'Page'.
src/index.ts:474:21 - error TS2339: Property 'realClick' does not exist on type 'Page'.
```
happened

**Comment by jarmo-fi** [comment]
> Can you try again with the latest version?

Original error disappeared, but other errors now:
node_modules/ghost-cursor/lib/mouse-helper.d.ts:1:27 - error TS2307: Cannot find module 'puppeteer' or its corresponding type declarations.

1 import type { Page } from 'puppeteer';
                            ~~~~~~~~~~~

node_modules/ghost-cursor/lib/spoof.d.ts:1:50 - error TS2307: Cannot find module 'puppeteer' or its corresponding type declarations.

1 import { ElementHandle, Page, BoundingBox } from 'puppeteer';
                                                   ~~~~~~~~~~~

node_modules/puppeteer-extra/dist/index.d.ts:2:31 - error TS2307: Cannot find module 'puppeteer' or its corresponding type declarations.

2 import { PuppeteerNode } from 'puppeteer';
                                ~~~~~~~~~~~


Found 3 errors in 3 files.

Errors  Files
     1  node_modules/ghost-cursor/lib/mouse-helper.d.ts:1
     1  node_modules/ghost-cursor/lib/spoof.d.ts:1
     1  node_modules/puppeteer-extra/dist/index.d.ts:2

**Comment by wim-web** [comment]
I was in the same situation, but it was fixed after updating to the latest version

**Comment by jarmo-fi** [comment]
I tried with latest version, it did not help. Installing puppeteer in addition to puppeteer-real-browser helps.

But if puppeteer is demanded, I guess it should be listed in dependencies?

My prev error is related to do simple scrolling with mouse
			await page.mouse.wheel({ deltaY: 200 });

**Comment by rogerfar** [comment]
I tried the latest version, and added puppeteer to the project, but I get:

```
node_modules/puppeteer-real-browser/typings.d.ts:20:25 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("chrome-launcher")' call instead.

20   customConfig?: import("chrome-launcher").Options;
                           ~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/puppeteer-real-browser/typings.d.ts:20
```

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/ezlink-scraper
You can examine a sample project working with Typescript from the link above.
