### ISSUE TITLE
ERROR: Missing X server or $DISPLAY

### ISSUE THREAD

**Issue by vince166** [zfcsoftware/puppeteer-real-browser#182]
### Description

Issue: Error when running a script on RHEL 8.8 without Docker

Environment:
- Operating System: RHEL 8.8
- X Server: xvfb installed
- Execution: From a Windows SSH terminal with Exceed enabled

Error Message:
```
LH:ChromeLauncher:error [112261:112261:0927/144838.261739:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
```

Observed Behavior:
1. `node test.js`:
   - Always launches the browser in a visible X window 
   - Behavior is consistent regardless of `disableXvfb` setting (In another word, I can't test xvfb is working or not.) 

2. `DISPLAY= node test.js`:
   - Results in the error message mentioned above
   
3. Commenting out ` 'DISPLAY': process.env.DISPLAY,` from launching arguments did not help. 

Workaround:
- Modifying the library code to pass `xvfb._display` as an environment variable to the Chrome launcher resolves the issue

Problem:
- The library code seems to be missing logic that links the `display` chosen by xvfb to the `display` used to launch Chrome
- Modifying the library code for each use is not a desirable solution

### Full steps to reproduce the issue

```javascript
const { connect } = require('puppeteer-real-browser');
const fs = require('fs/promises');
const fsSync = require('fs');
const path = require('path');

const tempProfilePath = fsSync.mkdtempSync(path.join(process.env.TMPDIR, 'puppeteer-profile-'));

async function setupBrowser() {
    const { browser, page } = await connect({
        headless: false,
        args: [
            '--start-maximized'
        ],
        customConfig: {
            chromePath: '/home/xxx/puppeteer/.local-chromium/chrome/linux-117.0.5938.92/chrome-linux64/chrome',
            userDataDir: tempProfilePath,
            envVars: {
                'DISPLAY': process.env.DISPLAY,
                'HOME': process.env.HOME,
                'LD_LIBRARY_PATH': '/lib:/lib64:/usr/lib:/usr/lib64',
                'TMPDIR': process.env.TMPDIR
            },
            logLevel: 'verbose'
        },
        connectOption: {
            defaultViewport: null
        },
        disableXvfb: false
    });
    return { browser, page };
}

async function logToFile(message) {
    const timestamp = new Date().toLocaleString();
    const logMessage = `${timestamp} - ${message}\n`;
    await fs.appendFile('scraper.log', logMessage);
    console.log(logMessage);
}

async function main() {
    let browser, page;
    try {
        ({ browser, page } = await setupBrowser());

        // Navigate to example.com
        await page.goto('https://www.example.com', { waitUntil: 'networkidle0' });
        await logToFile('Navigated to https://www.example.com');

    } catch (error) {
        console.error('An error occurred:', error);
        await logToFile(`Error: ${error.message}`);
    } finally {
        if (browser) await browser.close();
        await logToFile('Browser closed');
    }
}

main().catch(console.error);
```

### Issue Type

Bug

### Operating System

Linux

### Do you use Docker?

I don't use Docker

**Comment by rainb3rry** [comment]
Have you tried with `process.env.DISPLAY = :10.0`

**Comment by zfcsoftware** [comment]
The library currently only supports ubuntu and windows operating systems. Thank you for this detailed problem, but I cannot reproduce this error. On ubuntu, xfvb and the browser connect by themselves.
