### ISSUE TITLE
How to start with a profile

### ISSUE THREAD

**Issue by HamiguaLu** [zfcsoftware/puppeteer-real-browser#183]
Hi
It works great for me
Only one issue,  I want to start the browser with a given profile, I passed the below option to args in connect 
` '--user-data-dir=D:\\proj2022\\social_media\\twitter_auto\\bw_profiles\\wentao',`

But it seems doesn't work

**Comment by rainb3rry** [comment]
```
customConfig: {
userDataDir: `D:\\proj2022\\social_media\\twitter_auto\\bw_profiles\\wentao`
}
```

**Comment by HamiguaLu** [comment]
> ```
> customConfig: {
> userDataDir: `D:\\proj2022\\social_media\\twitter_auto\\bw_profiles\\wentao`
> }
> ```

Thanks, this works for me

**Comment by HamiguaLu** [comment]
Done
