### ISSUE TITLE
Using puppeteer-real-browser with puppeteer-cluster

### ISSUE THREAD

**Issue by captainjackrana** [zfcsoftware/puppeteer-real-browser#194]
Is there any documented example of how to run this with [puppeteer-cluster](https://www.npmjs.com/package/puppeteer-cluster)

Documentation says you can pass the `puppeteer` instance in the init method. 
https://github.com/thomasdondorf/puppeteer-cluster/blob/HEAD/examples/different-puppeteer-library.js
```
const cluster = await Cluster.launch({
        concurrency: Cluster.CONCURRENCY_CONTEXT,
        maxConcurrency: 2,

        // provide the puppeteer-core library
        puppeteer,
        // and provide executable path (in this case for a Chrome installation in Ubuntu)
        puppeteerOptions: {
            executablePath: 'google-chrome-stable',
        },
    });
```
However, `puppeteer-real-browser` doesn't actually give us the puppeteer instance post initialization.

**Comment by nonstopdevelopment** [comment]
This wraps Chrome Launcher and have been trying to get this to work but struggling with cloudflare part to function with the specific page manager it runs.

**Comment by zfcsoftware** [comment]
This library works differently with Puppeteer, so you may have problems combining the two. You can try to open this issue in the Puppeteer-cluster library.
