### ISSUE TITLE
Getting white window.

### ISSUE THREAD

**Issue by CovertCode** [zfcsoftware/puppeteer-real-browser#198]
I used it 2 times and chrome window did opened. But after my 3rd attempt I started getting white window with no chrome showing in taskbar but its running in task manager.
I checked my chrome executable which was being used, it also working perfectly. I tried to use that same executable with playwright, it worked.

Would you suggest a specific chrome version that should be used with this?

OS: Windows 11
Node: v20.17.0

Update:
I added code to take screenshot. it says `chrome headless`. Although I have set headless to false
![image](https://github.com/user-attachments/assets/0e0eeada-6e1f-48de-9d28-86a433928271)

Code:
```
async function test() {
    // let proxyData = await fetchProxy()

    // const proxyUrl = proxyData.url;
    // const proxyPort = proxyData.port;
    // const proxyUsername = proxyData.username;
    // const proxyPassword = proxyData.password;
    const { browser, page } = await connect({
        headless: false,
        args: ["--start-maximized"],

        customConfig: {},

        turnstile: true,

        connectOption: {},

        disableXvfb: false,
        ignoreAllFlags: false,
        // proxy:{
        //     host:proxyUrl,
        //     port:proxyPort,
        //     username:proxyUsername,
        //     password:proxyPassword
        // }

    })
    await page.goto('https://browserscan.net')
    console.log(await page.title())
    await page.screenshot({ path: 'example.png', fullPage: true });
}
```

**Comment by zfcsoftware** [comment]
I'm closing this issue because you didn't fill in important information such as the operating system. If you decide to edit it according to the issue template and report it after editing, I can try to recreate the issue and provide a solution.

**Comment by CovertCode** [comment]
> I'm closing this issue because you didn't fill in important information such as the operating system. If you decide to edit it according to the issue template and report it after editing, I can try to recreate the issue and provide a solution.

I have edited the details. Please check it again.

**Comment by zfcsoftware** [comment]
> > I'm closing this issue because you didn't fill in important information such as the operating system. If you decide to edit it according to the issue template and report it after editing, I can try to recreate the issue and provide a solution.
> 
> I have edited the details. Please check it again.

Can you add a link to which site this is?

![image](https://github.com/user-attachments/assets/cf92e1d2-4bac-43b2-9975-804d37cc46e0)

**Comment by CovertCode** [comment]
> > > I'm closing this issue because you didn't fill in important information such as the operating system. If you decide to edit it according to the issue template and report it after editing, I can try to recreate the issue and provide a solution.
> > 
> > 
> > I have edited the details. Please check it again.
> 
> Can you add a link to which site this is?
> 
> ![image](https://private-user-images.githubusercontent.com/123484092/376590847-cf92e1d2-4bac-43b2-9975-804d37cc46e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTI5NjMsIm5iZiI6MTcyODk5MjY2MywicGF0aCI6Ii8xMjM0ODQwOTIvMzc2NTkwODQ3LWNmOTJlMWQyLTRiYWMtNDNiMi05OTc1LTgwNGQzN2NjNDZlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxMTQ0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWQzYzM4ZjdiZTdiMDFiYjY3NjdhOTJiYTcwNDk0NTUxNDI0ZjE1MmE1NzM0NmQyMGM5MzI2NTE4YTA4OWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.blZtXRx1N0kVjL4oLK9tC88h52EXQic7A3RH8MyJ4BY)

[browserscan](https://www.browserscan.net/)
