### ISSUE TITLE
The method introduced in branch access-window does not work for anti-bot websites.

### ISSUE THREAD

**Issue by Biogasbottle** [zfcsoftware/puppeteer-real-browser#199]
### Description

Literally, the test case can pass, but for commercial websites, it is immediately detected and risk controlled.

### Full steps to reproduce the issue

- step 1:  git clone
- step 2:  change urls and simplify the code in success2.js.

const { connect } = require('puppeteer-real-browser');
const test = require('node:test');
const assert = require('node:assert');

test('Test Window Function', async () =>
{

    const { RequestInterceptionManager } = await import('puppeteer-intercept-and-modify-requests')

    const { page, browser } = await connect({
        args: ["--start-maximized"],
        turnstile: true,
        headless: false,
        disableXvfb: true,
        connectOption: { defaultViewport: null }
    })
    const client = await page.target().createCDPSession()
    const interceptManager = new RequestInterceptionManager(client)
    await interceptManager.intercept(
        {
            urlPattern: `https://www.dangdang.com/`,
            resourceType: 'Document',
            modifyResponse({ body })
            {
                return {
                    body: body.replace('</body>', `<script>
                            async function win(params) {

                               var c = document.createElement('div')
                                c.classList = 'zfc-token'
                                c.textContent  = 'window test'
                                document.body.appendChild(c)
                            }

                            win()
                        </script></body>`),
                }
            },
        }
    )

    await page.goto('https://www.dangdang.com/', {
        waitUntil: 'domcontentloaded'
    })
    await new Promise(resolve => setTimeout(resolve, 3000));
    console.log(await page.content());
    await page.waitForSelector('.zfc-token');
    const result = await page.evaluate(() =>
    {
        return document.querySelector('.zfc-token').textContent
    })
    console.log('Build Id: ', result);
    await browser.close()
    assert((result && result.length > 0), 'Unable to access function in Window object')
})

- step3 : npm run success2_test.
- step4:  yes Test case passed.

_<div class="zfc-token">window test</div></body></html>
Build Id:  window test
✔ Test Window Function_ 

  **but, check the browser, i see a page All garbled.**

- step5: remove the intercept part, the page get back to normal.

This method may work for ordinary websites, but it does not work for anti-bot websites. I tested several other online shopping malls and they were all detected and controlled.

### Issue Type

Bug

### Operating System

Windows 10

### Do you use Docker?

None

**Comment by nwebson** [comment]
Try to use different approach described here: [How to Access Main Context Objects from Isolated Context in Puppeteer & Playwright](https://rebrowser.net/blog/how-to-access-main-context-objects-from-isolated-context-in-puppeteer-and-playwright-23741)

**Comment by nwebson** [comment]
I added a new approach in the new version of [rebrowser-patches](https://github.com/rebrowser/rebrowser-patches).
Please use the latest version and `REBROWSER_PATCHES_RUNTIME_FIX_MODE=addBinding`.

**Comment by pwnz22** [comment]
@nwebson Give please some example of this new approach...

**Comment by zfcsoftware** [comment]
This problem should be solved with the new rebrowser update. If the problem persists, please report it here.
