### ISSUE TITLE
FingerPrint is not changing

### ISSUE THREAD

**Issue by alshahabrezvi** [zfcsoftware/puppeteer-real-browser#202]
### Description

Hi, whenever the browser opens, the fingerprint does not change. it shows my real fingerprint. Can you fix it or give me any suggestions for changing the fingerprint? I am facing so many problems with it. I hope you help me.

### Full steps to reproduce the issue

Hi, whenever the browser opens, the fingerprint does not change. it shows my real fingerprint. Can you fix it or give me any suggestions for changing the fingerprint? I am facing so many problems with it. I hope you help me.

### Issue Type

Support

### Operating System

Windows 10, Other

### Do you use Docker?

I don't use Docker

**Comment by zfcsoftware** [comment]
This library does not support fingerprint swapping. It is interested in starting a real browser. You can use libraries like fingerprint-suite for this.
