### ISSUE TITLE
https://antoinevastel.com/bots/ flags for webdriver!

### ISSUE THREAD

**Issue by Skorchekd** [zfcsoftware/puppeteer-real-browser#203]
### Description

![image](https://github.com/user-attachments/assets/86ebeb09-61f7-4af2-8fcf-c32e807c9b8f)

### Full steps to reproduce the issue

navigate to https://antoinevastel.com/bots/ scroll down and see incosistence on webdriver argument. 

### Issue Type

Support

### Operating System

Windows 10

### Do you use Docker?

I don't use Docker

**Comment by zfcsoftware** [comment]
Try it in your own chrome browser and you will see that it detects webdriver. That test does not work.

**Comment by Skorchekd** [comment]
> Try it in your own chrome browser and you will see that it detects webdriver. That test does not work.

i tried it does work. 
![image](https://github.com/user-attachments/assets/150c0b3a-9f10-4f4b-8948-3a6ef78f1150)
 all test pass on my own browser.

**Comment by zfcsoftware** [comment]
> > Try it in your own chrome browser and you will see that it detects webdriver. That test does not work.
> 
> i tried it does work. ![image](https://private-user-images.githubusercontent.com/171265152/380225762-150c0b3a-9f10-4f4b-8948-3a6ef78f1150.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NzAyNTUsIm5iZiI6MTcyOTg2OTk1NSwicGF0aCI6Ii8xNzEyNjUxNTIvMzgwMjI1NzYyLTE1MGMwYjNhLTlmMTAtNGY0Yi04OTQ4LTNhNmVmNzhmMTE1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxNTI1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjRiODNkYTFiYzA1YjU4NjdjYTVlN2M1MTlmZmZlMWYzMGI5ZTU2N2JjMTdiNzhkZGU0MDY4ZWQyZWIyYWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c20rT5BYhSkwl41F4vCAxLcaKgUYAknCxIySWr-Jing) all test pass on my own browser.

![image](https://github.com/user-attachments/assets/3b34d696-9079-4955-b8cb-a2190f2b554a)

**Comment by RubberArchind** [comment]
![image](https://github.com/user-attachments/assets/f2cf25b5-a468-4354-985b-d06eb74d8f2b)

i can confirm that i got Inconsistent result on the webdriver with my own chrome

but i got consistent if i try open it on firefox

![image](https://github.com/user-attachments/assets/db94b966-42d6-49cf-a966-5348a8f6102d)
