### ISSUE TITLE
fingerprinting issue

### ISSUE THREAD

**Issue by Skorchekd** [zfcsoftware/puppeteer-real-browser#205]
### Description

like the other issue a repetivie fingerprinting issue is occuring. the browser is being flagged with a bot fingerprint. the browser version 1.3 chrome doesnt match the version the chrome browser is saying. 

### Full steps to reproduce the issue

fix browser mismatch 

### Do you use Docker?

None

**Comment by Skorchekd** [comment]
https://bot-detector.rebrowser.net/
https://bot-detector.rebrowser.net/ 
you can verify here!

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/puppeteer-real-browser/issues/202#issuecomment-2440160430

![image](https://github.com/user-attachments/assets/79beeaf2-c567-44a4-ad2b-91deb3499d1e)
