### ISSUE TITLE
how to use other browsers?

### ISSUE THREAD

**Issue by Skorchekd** [zfcsoftware/puppeteer-real-browser#206]
### Description

is it possible for us to use firefox? 

### Full steps to reproduce the issue

how can we use firefox or other browsers. 

### Issue Type

Support, Feature Request

### Operating System

Windows 10

### Do you use Docker?

None

**Comment by zfcsoftware** [comment]
Currently only Chrome is supported. Chrome-launcher library is used. Other browsers are not currently supported. You can try Rebrowser.

**Comment by andyiyass** [comment]
can I use chromium or brave and if so how do I change it?

**Comment by RubberArchind** [comment]
> can I use chromium or brave and if so how do I change it?

You can try set chromePath in customConfig

`customConfig: {chromePath:"THE_PATH_HERE"}`

**Comment by andyiyass** [comment]
> > can I use chromium or brave and if so how do I change it?
> 
> You can try set chromePath in customConfig
> 
> `customConfig: {chromePath:"THE_EXECUTABLE_PATH_HERE"}`
> 
> But there is no guarantee that it will worked normally on other browser

thanks this works, but how to switch to another profile?
 i tried like this but not work
![puppet](https://github.com/user-attachments/assets/928fbc9c-a5c5-42e7-b69f-638e5bf4e552)

**Comment by RubberArchind** [comment]
> > > can I use chromium or brave and if so how do I change it?
> > 
> > 
> > You can try set chromePath in customConfig
> > `customConfig: {chromePath:"THE_EXECUTABLE_PATH_HERE"}`
> > But there is no guarantee that it will worked normally on other browser
> 
> thanks this works, but how to switch to another profile? i tried like this but not work ![puppet](https://private-user-images.githubusercontent.com/37761526/382288529-928fbc9c-a5c5-42e7-b69f-638e5bf4e552.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDUxMTYsIm5iZiI6MTczMDU0NDgxNiwicGF0aCI6Ii8zNzc2MTUyNi8zODIyODg1MjktOTI4ZmJjOWMtYTVjNS00MmU3LWI2OWYtNjM4ZTViZjRlNTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDEwNTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZGJhOWZmMWJlYTBhYWQ3ZmJiMTk5MGUzODZmNWUxMWMxNzM1OThlMmQ3MjE1Nzc1MmE1ODBmYjIxZWZiNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RtqLcxqdFNTKzobvcMj7NNAt5kvBTH_4-dox3YzfmJk)

you dont need to spesify the Default, if you want to swtich between profiles just add --profile-directory argument in args, here is how i use it

![image](https://github.com/user-attachments/assets/4e613e36-c5d8-46dc-9b03-73addec5561d)
