### ISSUE TITLE
Not able to build w/ dockerfile

### ISSUE THREAD

**Issue by aumeshm** [zfcsoftware/puppeteer-real-browser#207]
My dockerfile is the same as the one in the repo except I have: `FROM node:22.1.0` at the top.

I am using an M2 Mac.

I keep getting this error:
```
6.870 W: https://dl.google.com/linux/chrome/deb/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
6.873 
6.873 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
6.873 
6.875 Reading package lists...
7.121 Building dependency tree...
7.189 Reading state information...
7.194 E: Unable to locate package google-chrome-stable
------
failed to solve: process "/bin/sh -c wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo \"deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google.list     && apt update     && apt install -y google-chrome-stable chromium     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
```

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/cf-clearance-scraper/blob/main/Dockerfile
The library is not guaranteed to be macOS compatible as there are no macOS devices I can test. You can try with the Dockerfile above.

**Comment by aumeshm** [comment]
@zfcsoftware I believe this is incorrectly closed. Dockerizing applications should make it so that the application will run regardless of what device you are on. The issue here is that you cannot download `google-stable-chrome` to the docker image.

**Comment by aumeshm** [comment]
Apologies on my part, I stand corrected - I am trying building the image while specifying --platform=linux/amd64, as M1+ Mac's used arm64. Will follow up here if that works.

**Comment by aumeshm** [comment]
@zfcsoftware adding `platform: linux/amd64` to my docker-compose file worked. May be worth adding that in the readme to make sure others who run this on a mac avoid those issues.
