### ISSUE TITLE
detected by discord and cloudflare

### ISSUE THREAD

**Issue by Skorchekd** [zfcsoftware/puppeteer-real-browser#208]
### Description

recently from my own testing and a friends this library has become detected by cloudfare and also discord. 

### Full steps to reproduce the issue

attempt to register an account discord.gg/register or discord.com using the emulated browser. the account is instantly disabled if email verified and such. 

### Issue Type

Performance

### Operating System

Windows 10

### Do you use Docker?

None

**Comment by Skorchekd** [comment]
discords anti bot detection is cloudflares anti bot detection

**Comment by zfcsoftware** [comment]
Your account may be suspended due to the e-mail, proxy you are using. Since we cannot determine whether it is directly caused by the library or not, I am closing it. You can try using better quality mails, proxy and fingerprint-suite.

**Comment by Skorchekd** [comment]
> Your account may be suspended due to the e-mail, proxy you are using. Since we cannot determine whether it is directly caused by the library or not, I am closing it. You can try using better quality mails, proxy and fingerprint-suite.

i did try the above but it does seem like a detection within the library. if you can confirm by testing it yourself would appecirate it thanks.
