### ISSUE TITLE
TF = true isnt detecting CF Turnstile

### ISSUE THREAD

**Issue by ledean** [zfcsoftware/puppeteer-real-browser#21]
Greetings,

when I use tf = true its not detecting Turnstile at all, when I turn it off it does detect turnstile but it cannot pass the captcha

PS: I just used the example script from your starting page, nothing else added

**Comment by zfcsoftware** [comment]
please attach your code with the site you are testing.

**Comment by ledean** [comment]
import { connect } from 'puppeteer-real-browser'

connect({

    headless: 'false',

    args: [],

    customConfig: {},

    skipTarget: [],

    fingerprint: true,

    turnstile: true,

    connectOption: {},

    tf: true,

    // proxy:{
    //     host:'<proxy-host>',
    //     port:'<proxy-port>',
    //     username:'<proxy-username>',
    //     password:'<proxy-password>'
    // }

})
.then(async response => {
    const {browser, page} = response
    await page.goto('https://www.metin2pserver.info/vote-os2mid.htm')
    
})
.catch(error=>{
    console.log(error.message)
})

**Comment by ledean** [comment]
When the browser opens is also said "not supportet command flag --disable-setuid-sandbox

**Comment by zfcsoftware** [comment]
> import { connect } from 'puppeteer-real-browser'
> 
> connect({
> 
> ```
> headless: 'false',
> 
> args: [],
> 
> customConfig: {},
> 
> skipTarget: [],
> 
> fingerprint: true,
> 
> turnstile: true,
> 
> connectOption: {},
> 
> tf: true,
> 
> // proxy:{
> //     host:'<proxy-host>',
> //     port:'<proxy-port>',
> //     username:'<proxy-username>',
> //     password:'<proxy-password>'
> // }
> ```
> 
> }) .then(async response => { const {browser, page} = response await page.goto('https://www.metin2pserver.info/vote-os2mid.htm')
> 
> }) .catch(error=>{ console.log(error.message) })

The library has been updated, please try again with the latest version 1.2.9.

**Comment by ledean** [comment]
Its working now, thank you!
