### ISSUE TITLE
Bypass Error 1015

### ISSUE THREAD

**Issue by pwnz22** [zfcsoftware/puppeteer-real-browser#211]
### Description

Bypass of error 1015
<img width="718" alt="Screenshot 2024-10-31 at 02 04 04" src="https://github.com/user-attachments/assets/2d8a4ed4-c8a8-4c1b-b869-23bfe1a0061c">

### Full steps to reproduce the issue

-

### Issue Type

Feature Request

### Operating System

Linux, Mac OS

### Do you use Docker?

I don't use Docker

**Comment by zfcsoftware** [comment]
The rate limit error is caused by your ip address being blocked for a while when you send too many requests in a row. It is not a problem with the library.
