### ISSUE TITLE
Can't solve turnstile in headless mode

### ISSUE THREAD

**Issue by warpunish** [zfcsoftware/puppeteer-real-browser#213]
### Description

It seems it can't solve turnstile in headless mode. It was taking too long to to load the page so I suspected this might be the issue and I took some screenshots if it takes too long. After 5 minutes of loading all my screenshots was showing it is stuck on verification.

Example Screenshot
![image](https://github.com/user-attachments/assets/c7ecc596-33b8-454c-8c95-ee8c24844f9b)

### Full steps to reproduce the issue

```
 const { browser, page } = await connect({
        headless: true,
        customConfig:{

            chromePath: './chromeData/win64-130.0.6723.69/chrome-win64/chrome.exe',
        },
        args: [],
        turnstile: true,
        connectOption: {},
        disableXvfb: false,
        ignoreAllFlags: false,
        proxy: {
            host: server,
            port: port,
            username: username,
            password: password
        }
    });
```

### Issue Type

Bug

### Operating System

Windows 10, Linux

### Do you use Docker?

I don't use Docker

**Comment by zfcsoftware** [comment]
headless: bot bypass is not guaranteed in headless modes other than false. As mentioned in the readme file, false is recommended.
