### ISSUE TITLE
Chrome does not shut down when running error code

### ISSUE THREAD

**Issue by bauhuynhdev** [zfcsoftware/puppeteer-real-browser#215]
### Description

When I run a non-existent proxy the code stops and Chrome stays open. The expectation is that it will shut down when an error occurs.

### Full steps to reproduce the issue

When I run a non-existent proxy the code stops and Chrome stays open

### Issue Type

Bug

### Do you use Docker?

None

**Comment by zfcsoftware** [comment]
This error is not related to the library. This should be the case with Puppeteer. Even if it gives a 407 error, the browser will remain open.

**Comment by RubberArchind** [comment]
Just an advice, its always good idea to wrap your code with

try{
     //your code here
}catch(){
     //handle the error
}finally{
    //you should always check and close the browser here if it still open to be safe
}

**Comment by bauhuynhdev** [comment]
> This error is not related to the library. This should be the case with Puppeteer. Even if it gives a 407 error, the browser will remain open.

I tried with Puppeteer then Chrome closes when there is an error
