### ISSUE TITLE
Bug with recpatchav2

### ISSUE THREAD

**Issue by ledean** [zfcsoftware/puppeteer-real-browser#22]
Hey,

sorry me again, when it detects an recaptchav2 its starts clicking it and then pressing only the first picture.
Maybe you could add an support for capsolver/capmonster to solve this kind of captchas, that would be awesome

**Comment by zfcsoftware** [comment]
> Hey,
> 
> sorry me again, when it detects an recaptchav2 its starts clicking it and then pressing only the first picture. Maybe you could add an support for capsolver/capmonster to solve this kind of captchas, that would be awesome

Error resolved please try again using the latest version.
