### ISSUE TITLE
Question. How to leave a process running on a remote server.

### ISSUE THREAD

**Issue by qSerkl** [zfcsoftware/puppeteer-real-browser#23]
Hello. I have a problem, I want to leave running a process on a remote server with ubuntu, after some time after disconnecting the ssh connection xvfb dies and puppeteer-real-browser stops working. Is there any solution to this?

**Comment by zfcsoftware** [comment]
Hello, have you used pm2 and docker? When I test with pm2 it stays on all the time.

**Comment by qSerkl** [comment]
I keep it running using pm2, the nodejs script keeps running, but I get an error. 

Error: connect ECONNREFUSED 127.0.0.1:43069
at puppeteer-real-browser/src/module/chromium.js:110:19

Is Docker going to be the solution? I've never used it

**Comment by zfcsoftware** [comment]
> > Hello, have you used pm2 and docker? When I test with pm2 it stays on all the time.
> 
> I keep it running using pm2, the nodejs script keeps running, but I get an error.
> 
> Error: connect ECONNREFUSED 127.0.0.1:43069 at puppeteer-real-browser/src/module/chromium.js:110:19
> 
> Is Docker going to be the solution? I've never used it

This error will happen on screenless servers due to Chromium issues. Docker gives you a solution. You can try using docker as described in the readme file.

**Comment by qSerkl** [comment]
> > > Hello, have you used pm2 and docker? When I test with pm2 it stays on all the time.
> > 
> > 
> > I keep it running using pm2, the nodejs script keeps running, but I get an error.
> > Error: connect ECONNREFUSED 127.0.0.1:43069 at puppeteer-real-browser/src/module/chromium.js:110:19
> > Is Docker going to be the solution? I've never used it
> 
> This error will happen on screenless servers due to Chromium issues. Docker gives you a solution. You can try using docker as described in the readme file.

Thank you, that solved my problem. I don't know if it was necessary to install pm2 inside the docker and run the script through it, probably unnecessary, but I did that too...

**Comment by iliyaZelenko** [comment]
Also you can get "Error: connect ECONNREFUSED" error if for some reason the browser failed to start. In my case, `--load-extension=` was specified incorrectly.
