### ISSUE TITLE
bunjs support

### ISSUE THREAD

**Issue by punjasin** [zfcsoftware/puppeteer-real-browser#25]
i try but it open chrome and do nottng 🥲

**Comment by zfcsoftware** [comment]
I haven't worked with bunjs before. I'll try to add the support. Thanks.

**Comment by punjasin** [comment]
thank you it work like charm on node

**Comment by zfcsoftware** [comment]
Bunjs currently does not support many features like proxy. Since we will wait until it becomes stable, I am turning it off for now.
