### ISSUE TITLE
A question on xvfb and running in Google cloud functions

### ISSUE THREAD

**Issue by humanismusic** [zfcsoftware/puppeteer-real-browser#26]
Great work with this library @zfcsoftware.

I see xvfb is a requirement. Does this mean there's no chance at all that we can run this using Google cloud functions, not even with headless = true?

**Comment by zfcsoftware** [comment]
xvfb is absolutely necessary to avoid detection when opened incognito. It creates a virtual screen. For this reason, you can run it anywhere with container support.
**Tested many times with Google cloud run.** 
https://github.com/zfcsoftware/puppeteer-real-browser/blob/main/Dockerfile
Using the dockerfile in the home directory, you can run it on Google Cloud Run without any problems. However, it cannot be run in non-container functions.

**Comment by humanismusic** [comment]
Thank you. I've got it working when I create a new project/folder and use this code:

```
(async () => {
  const { connect } = await import('puppeteer-real-browser');


  connect({
      tf: true, // If a feature you want to use at startup is not working, you can initialize the tf variable false and update it later.
      turnstile: true
  })
  .then(async response => {
          const { page, browser, setTarget } = response

          page.goto('https://nopecha.com/demo/cloudflare', {
              waitUntil: 'domcontentloaded'
          })

          setTarget({ status: false })

          let page2 = await browser.newPage();

          setTarget({ status: true })

          await page2.goto('https://nopecha.com/demo/cloudflare');
  })
  
  // Use connect as needed here
})();
```


But when trying to implement it in an existing project (in addition to chrome-aws-lambda which I currently use) I get an error:

```
var response = !!target.url()
                            ^
TypeError: target.url is not a function
```

I added a console.log before this line and in the existing project it shows:

```
target:  {
  targetId: '7665528686C39479243B434C8669808C',
  type: 'page',
  title: 'about:blank',
  url: 'about:blank',
  attached: true,
  canAccessOpener: false,
  browserContextId: '8B0D38451DDF4A5431CF6C4DCFCB806A'
}
``` 


While in the new project is shows:

```
target:  CdpTarget {
  _initializedDeferred: Deferred {},
  _isClosedDeferred: Deferred {},
  _targetId: '84a3c50a-aa77-45cc-8bf3-17dec5ab7c0d'
}
target:  CdpTarget {
  _initializedDeferred: Deferred {},
  _isClosedDeferred: Deferred {},
  _targetId: '865AA8E483FA9DD16AB482B73A7FEC2F'
}

(and more of the same)
```

Exact same code example just in different folders. May the dependencies of my existing project be conflicting?


And one more question. Can we use async rather than the .then method provided in the example? For example, like this:

```
async function connectToRealBrowser() {
  const { connect } = await import('puppeteer-real-browser');
  return connect;
}

// later
let connect = await connectToRealBrowser();
const response = await connect({
   headless: 'auto', args: [], customConfig: {}, skipTarget: [],
   fingerprint: true, turnstile: true, connectOption: {}
});

let { page, browser setTarget } = response;

page.goto('https://nopecha.com/demo/cloudflare', {
   waitUntil: 'domcontentloaded'
})
```

Thanks again.

**Comment by zfcsoftware** [comment]
```
  var response = null
    try{
      response = !!target.url()
    }catch{
      return false
    }
```
You can try to use it this way. I have not encountered this error before, but I am looking for a different solution instead of targetFilter.

For your 2nd question, yes you can use it. There will be no problem. 

targetFilter is causing a lot of problems. Currently most of the active issues are caused by targetFilter. I will definitely try to find a different solution for this problem in the future. 

You are welcome

**Comment by zfcsoftware** [comment]
> Thank you. I've got it working when I create a new project/folder and use this code:
> 
> ```
> (async () => {
>   const { connect } = await import('puppeteer-real-browser');
> 
> 
>   connect({
>       tf: true, // If a feature you want to use at startup is not working, you can initialize the tf variable false and update it later.
>       turnstile: true
>   })
>   .then(async response => {
>           const { page, browser, setTarget } = response
> 
>           page.goto('https://nopecha.com/demo/cloudflare', {
>               waitUntil: 'domcontentloaded'
>           })
> 
>           setTarget({ status: false })
> 
>           let page2 = await browser.newPage();
> 
>           setTarget({ status: true })
> 
>           await page2.goto('https://nopecha.com/demo/cloudflare');
>   })
>   
>   // Use connect as needed here
> })();
> ```
> 
> But when trying to implement it in an existing project (in addition to chrome-aws-lambda which I currently use) I get an error:
> 
> ```
> var response = !!target.url()
>                             ^
> TypeError: target.url is not a function
> ```
> 
> I added a console.log before this line and in the existing project it shows:
> 
> ```
> target:  {
>   targetId: '7665528686C39479243B434C8669808C',
>   type: 'page',
>   title: 'about:blank',
>   url: 'about:blank',
>   attached: true,
>   canAccessOpener: false,
>   browserContextId: '8B0D38451DDF4A5431CF6C4DCFCB806A'
> }
> ```
> 
> While in the new project is shows:
> 
> ```
> target:  CdpTarget {
>   _initializedDeferred: Deferred {},
>   _isClosedDeferred: Deferred {},
>   _targetId: '84a3c50a-aa77-45cc-8bf3-17dec5ab7c0d'
> }
> target:  CdpTarget {
>   _initializedDeferred: Deferred {},
>   _isClosedDeferred: Deferred {},
>   _targetId: '865AA8E483FA9DD16AB482B73A7FEC2F'
> }
> 
> (and more of the same)
> ```
> 
> Exact same code example just in different folders. May the dependencies of my existing project be conflicting?
> 
> And one more question. Can we use async rather than the .then method provided in the example? For example, like this:
> 
> ```
> async function connectToRealBrowser() {
>   const { connect } = await import('puppeteer-real-browser');
>   return connect;
> }
> 
> // later
> let connect = await connectToRealBrowser();
> const response = await connect({
>    headless: 'auto', args: [], customConfig: {}, skipTarget: [],
>    fingerprint: true, turnstile: true, connectOption: {}
> });
> 
> let { page, browser setTarget } = response;
> 
> page.goto('https://nopecha.com/demo/cloudflare', {
>    waitUntil: 'domcontentloaded'
> })
> ```
> 
> Thanks again.

```
  var response = null
    try{
      response = !!target.url()
    }catch{
      return false
    }
```
You can try to use it this way. I have not encountered this error before, but I am looking for a different solution instead of targetFilter.

For your 2nd question, yes you can use it. There will be no problem. 

targetFilter is causing a lot of problems. Currently most of the active issues are caused by targetFilter. I will definitely try to find a different solution for this problem in the future. 

You are welcome

**Comment by robtec** [comment]
Just a followup question regarding `xvfb`, I've been trying to get this running on an aws lambda, with custom container image that has `xvfb` installed, sadly its not working. My guess is `xvfb` is not designed to work in server-less functions

**Comment by zfcsoftware** [comment]
> Just a followup question regarding `xvfb`, I've been trying to get this running on an aws lambda, with custom container image that has `xvfb` installed, sadly its not working. My guess is `xvfb` is not designed to work in server-less functions

https://github.com/zfcsoftware/puppeteer-real-browser/blob/main/Dockerfile
I haven't tried running it on Aws, but this dockerfile worked fine on my private servers and google cloud run. Aws may not allow xvfb to be installed correctly. I recommend using google cloud run. I will try and run it on aws when I have time.

**Comment by devanshug2910** [comment]
@humanismusic I'm currently encountering the exact same problem you're facing. Need to run a simple puppeteer script on cloud functions but cloudflare turnstile blocks me on login page.
Running the script in `headless:true` blocks me from accessing the page and `headless:false` is a no go without xvfb on cloud functions.
Any progress on the issue?

**Comment by humanismusic** [comment]
@devanshug2910  I have not had time to try with Google cloud run, but looks like that's the way to go. There's a few more steps vs cloud functions but nothing to complicated it seems: https://cloud.google.com/run/docs/deploying-source-code.

**Comment by robtec** [comment]
Running this on GCP, what am I doing wrong?

<img width="1447" alt="Screenshot 2024-04-08 at 01 13 26" src="https://github.com/zfcsoftware/puppeteer-real-browser/assets/8657653/e5453677-6a5c-4c58-9138-db89dcfdcc63">

**Comment by zfcsoftware** [comment]
> Running this on GCP, what am I doing wrong?
> 
> <img alt="Screenshot 2024-04-08 at 01 13 26" width="1447" src="https://private-user-images.githubusercontent.com/8657653/320323385-e5453677-6a5c-4c58-9138-db89dcfdcc63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1Mzc5MjEsIm5iZiI6MTcxMjUzNzYyMSwicGF0aCI6Ii84NjU3NjUzLzMyMDMyMzM4NS1lNTQ1MzY3Ny02YTVjLTRjNTgtOTEzOC1kYjg5ZGNmZGNjNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMDA1MzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWIzZTFhMDlhZGMwODhmMzVkYzBlN2QwNThlNGIzNjlkZjcyMzFiYjk3MmE3MWExNDY0ZDFiYzA0MmU2YmIxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iLUO7-5RXgKSoqV3ms4VgX5mwDph8nzyFPhc6NmPAgY">

https://github.com/zfcsoftware/puppeteer-real-browser/blob/main/Dockerfile
If you are running with Google Cloud run using this Dockerfile, the problem might be resource consumption. You should make request 1 per instance. You should make cpu 1 ram 1 per instance.

**Comment by robtec** [comment]
I forked your project, and edited the following to run on cloud run - https://github.com/robtec/puppeteer-real-browser/blob/main/src/test.js

I've set cpu to 1 and ram to 2gb

**Comment by zfcsoftware** [comment]
> I forked your project, and edited the following to run on cloud run - https://github.com/robtec/puppeteer-real-browser/blob/main/src/test.js
> 
> I've set cpu to 1 and ram to 2gb
You should not do it in while true. 
https://gist.github.com/zfcsoftware/0deded42bba6505b714bab0f185e0508
Please try the code above.

**Comment by robtec** [comment]
After a few tweaks it worked. Thank you for your help
