### ISSUE TITLE
Reuse "fingerprint"

### ISSUE THREAD

**Issue by joska1993** [zfcsoftware/puppeteer-real-browser#29]
Is there a possibility to save the used "fingerprint" for later use?

**Comment by zfcsoftware** [comment]
Hello,
We use the puppeteer-afp library created by @pavlealeksic. This library doesn't support this feature yet, but I plan to bring an update in the future.

**Comment by pavlealeksic** [comment]
@joska1993 @zfcsoftware Glad you like my library, its finally updated so it has options to save fingerprint in options, and to reuse it whenever, so check it out :)

**Comment by zfcsoftware** [comment]
> @joska1993 @zfcsoftware Glad you like my library, its finally updated so it has options to save fingerprint in options, and to reuse it whenever, so check it out :)

This is very good news, thank you for providing this wonderful library. I will update my library shortly to make the fingerprint recording feature available.
