### ISSUE TITLE
Does this work on headless mode

### ISSUE THREAD

**Issue by Toolsclub** [zfcsoftware/puppeteer-real-browser#3]
For me it's not, it got timeout all the time, i guess headless mode can't pass cloudflare, is it just me or it's universal, thanks

```
send({
    url: domain,            
})
.then(resp=>{
    return res.status(200).json(resp);
})
 
 
const send = ({ url = '', proxy = {} }) => {
    return new Promise(async (resolve, reject) => {
        try {
            var { puppeteerRealBrowser } = await import('puppeteer-real-browser')
            var data = {}
            if (proxy && proxy.host && proxy.host.length > 0) {
                data.proxy = proxy
            }
            data.headless = true;                       👈👈🏻👈🏼👈🏽👈🏾👈🏿 headless here
 
            puppeteerRealBrowser = await puppeteerRealBrowser(data)
            var browser = puppeteerRealBrowser.browser
            var page = puppeteerRealBrowser.page
 
            try {
                var st = setTimeout( async () => {
                    await browser.close();
                    resolve({
                        code: 504,
                        message: 'Time Out'
                    })
 
                }, 55000);
 
                await page.goto(url, { waitUntil: 'domcontentloaded' })
                ......
            }
        }
    }
})
```

**Comment by zfcsoftware** [comment]
Hello, it can also pass in headless mode without any problem. You may not be able to click on the captcha. You can use the code above for this. 
It was tried on Ubuntu 22 and windows server operating systems and no problem was experienced.

Can you add the code and take continuous screenshots and post a video of what is happening?



`setInterval(() => {
	page.screenshot({ path: `./scrapingbee_homepage.jpg` });
}, 200);`


https://github.com/zfcsoftware/youtube_lessons_resources/blob/main/puppeteer_cloudflare_bypass/index.js

**Comment by zfcsoftware** [comment]
@Toolsclub 
The bookshelf has been updated. Please try again with the updated documentation. Tests in Windows environment did not show any problems.
