### ISSUE TITLE
Puppeteer-real-browser as headless: "true"

### ISSUE THREAD

**Issue by devanshu-gupta2002** [zfcsoftware/puppeteer-real-browser#30]
I've been trying to run puppeteer-headless-browser as `headless:true"` but the browser still opens as `headless:false`. On `headless:auto` the browser launches as `headless:false`.
Below are the connect params i'm passing
```
connect({
    headless: 'true',
    args: [],
    customConfig: {},
    skipTarget: [],
    fingerprint: true,
    turnstile: true,
    connectOption: {},
    tf: true,
})
```
How to launch the browser as `headless:true`.

**Comment by zfcsoftware** [comment]
false =>   headless: 'true', 
true =>   headless: true
The headless variable works the same as in puppeteer. you can send true, false, 'new' and 'auto' values. auto selects automatically according to your operating system.
