### ISSUE TITLE
Making a Cloudflare Proxy

### ISSUE THREAD

**Issue by TheRealStingo** [zfcsoftware/puppeteer-real-browser#31]
Im pretty sure most webscrapers use APIs to Scrape CF Challenge cookies to enable them to make requests to specific servers . My idea is since your project is very powerful and it evolves around the idea of bypassing cloudflare , you could try make webserver that accepts url and proxy as arguments and returns CF Page content , cookies and headers using your project . i think it would be very interesing since most libs now dont work .

**Comment by zfcsoftware** [comment]
Hello, thank you for your nice thoughts. I plan to make this project much more powerful. I will make it a library integrated into many services like Google Cloud Run, AWS ECS, etc. I will also add cf cookie rotation as you mentioned. But the library is currently very little popular. This does not provide motivation for development. When it becomes more popular and the existing problems are solved, I will start making such improvements. 

I am determined to keep the library free and constantly updated. An api that returns Cloudflare cookies can be added to the library. It can be run with Google Cloud run. It will cost very little. This is in my plans. I will definitely add it.

**Comment by TheRealStingo** [comment]
> An api that returns Cloudflare cookies can be added to the library. It can be run with Google Cloud run. It will cost very little. This is in my plans. I will definitely add it.

This is definitely a feature that me personally im waiting for and would even love to contribute , if you have any near plans to make it just let us know , we dont need to repo to be that popular to make such things to make beautiful things and i think new users would be happier to find such a crucial feature , also love the fact that you are keeping it for free . could you please share a donation link . to show support for such talents

**Comment by zfcsoftware** [comment]
> > An api that returns Cloudflare cookies can be added to the library. It can be run with Google Cloud run. It will cost very little. This is in my plans. I will definitely add it.
> 
> This is definitely a feature that me personally im waiting for and would even love to contribute , if you have any near plans to make it just let us know , we dont need to repo to be that popular to make such things to make beautiful things and i think new users would be happier to find such a crucial feature , also love the fact that you are keeping it for free . could you please share a donation link . to show support for such talents

Thank you very much. I'm starting to update. I'll add a donation link etc. when I update the library.
