### ISSUE TITLE
How to use docker file ?

### ISSUE THREAD

**Issue by myagizmaktav** [zfcsoftware/puppeteer-real-browser#34]
Hello I wondering how to use docker file ?

**Comment by eindrawan** [comment]
There is a guide in the README page:

```
git clone https://github.com/zfcsoftware/puppeteer-real-browser
cd puppeteer-real-browser
```
and you can simply change the start command in package json to point to you start file,
then build and start the docker.
```
docker build -t puppeteer-real-browser-project .
docker run -p 8080:3000 puppeteer-real-browser-project
```
tough I dont know why he exposed the 3000 port

**Comment by zfcsoftware** [comment]
You can create a normal docker project and use puppeteer-real-browser in it. Then you need to modify the dockerfile in the project's home directory and run your project with this dockerfile. It is no different from any docker project, only some dependencies like chrome, xvfb need to be installed.  This is done by the dockerfile in the project home directory.
