### ISSUE TITLE
Error: require() of ES Module ./node_modules/puppeteer-real-browser/src/index.js from ./server.ts not supported. Instead change the require of index.js in ./server.ts to a dynamic import() which is available in all CommonJS modules.

### ISSUE THREAD

**Issue by jhonatabonadio1** [zfcsoftware/puppeteer-real-browser#36]
When trying to run the application, the following error appears:

Error: require() of ES module /Users/jhonatabonadio/stfnoticias/node_modules/puppeteer-real-browser/src/index.js from /Users/jhonatabonadio/stfnoticias/server.ts not supported.
Instead, change the require from index.js in /Users/jhonatabonadio/stfnoticias/server.ts to a dynamic import() that is available in all CommonJS modules.

server.ts

```

import dotenv from 'dotenv'
import { connect } from 'puppeteer-real-browser'

dotenv.config()

puppeteer.use(StealthPlugin())

async function consultarProcesso(cpf: string) {
  connect({
    turnstile: true,
    fingerprint: true,
    headless: 'auto',
  }).then(async (response: any) => {
    const { page, browser } = response

    await page.goto('https://nopecha.com/demo/cloudflare')
  })
}
```

**Comment by zfcsoftware** [comment]
Hello, @CrispyyBaconx coded the typescript side. Since it is an old version, it may not be usable with the new settings. https://github.com/zfcsoftware/puppeteer-real-browser/tree/Type-Script I suggest you try the old version.
