### ISSUE TITLE
WEBRTC problem

### ISSUE THREAD

**Issue by alshahabrezvi** [zfcsoftware/puppeteer-real-browser#38]
![Screenshot 2024-04-18 150633](https://github.com/zfcsoftware/puppeteer-real-browser/assets/74756943/668cd31c-f595-438e-bd9a-c4b70d354deb)

not properly set WEBRTC whoer.net

**Comment by alshahabrezvi** [comment]
I have also tried this solution. This is best package but if you fix problem of webrtc in fingerprints true option. I thing it going to be best plugin...

**Comment by pavlealeksic** [comment]
Hey @zfcsoftware @alshahabrezvi Yeah, the plugin at the moment kills off the webrtc so it cannot be detected. Newest version has an option now for webrtcprotect which if you used false here would get it to green

**Comment by alshahabrezvi** [comment]
> Hey @zfcsoftware @alshahabrezvi Yeah, the plugin at the moment kills off the webrtc so it cannot be detected. Newest version has an option now for webrtcprotect which if you used false here would get it to green

Can you assist me?

**Comment by pavlealeksic** [comment]
Well, @zfcsoftware needs to update my plugin to the latest version, and then you will have an option to do it easily

**Comment by zfcsoftware** [comment]
> Hey @zfcsoftware @alshahabrezvi Yeah, the plugin at the moment kills off the webrtc so it cannot be detected. Newest version has an option now for webrtcprotect which if you used false here would get it to green

> Well, @zfcsoftware needs to update my plugin to the latest version, and then you will have an option to do it easily
Thank you very much for your support and updates. The library needs to be updated as the library code is added manually. I am currently working on an update that fixes most of the existing issues, and I will have integrated the latest version of your library. Your library has been very helpful in the growth of this library. Thank you very much. Sincerely yours.


> > Hey @zfcsoftware @alshahabrezvi Yeah, the plugin at the moment kills off the webrtc so it cannot be detected. Newest version has an option now for webrtcprotect which if you used false here would get it to green
> 
> Can you assist me?
Hello, for now you can include the puppeteer-afp library later by sending fingerprint false. I will make an update on this issue shortly.

**Comment by zfcsoftware** [comment]
> > Hey @zfcsoftware @alshahabrezvi Yeah, the plugin at the moment kills off the webrtc so it cannot be detected. Newest version has an option now for webrtcprotect which if you used false here would get it to green
> 
> Can you assist me?

The library has been updated, please check again.
