### ISSUE TITLE
how to set custom viewport size?

### ISSUE THREAD

**Issue by manishiitg** [zfcsoftware/puppeteer-real-browser#39]

**Comment by zfcsoftware** [comment]
You can use it as follows. It is already set in the library with this method.

```
    await page.setViewport({
            width: 1920,
            height: 1080
        });
```


![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/7369ca22-0dd5-4908-a39b-b5c73ea21e2b)
