### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ibrahimmus** [zfcsoftware/puppeteer-real-browser#40]
It is failing the online test for reCAPTCHA 3 score, https://antcpt.com/eng/information/demo-form/recaptcha-3-test-score.html

**Comment by zfcsoftware** [comment]
I suggest you turn off fingerprint and turnstile plugins and try it.

![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/077a28b4-aeb8-4f6a-9ab2-538d4d018d6d)

**Comment by ibrahimmus** [comment]
The best I can get is 0.3 with this configuration :/

**Comment by zfcsoftware** [comment]
Hello, unfortunately it catches because of the CDP session. I will try to hide the CDP session. This error is something I have been investigating for a long time.

**Comment by kaliiiiiiiiii** [comment]
> Hello, unfortunately it catches because of the CDP session. I will try to hide the CDP session. This error is something I have been investigating for a long time.

see https://github.com/kaliiiiiiiiii/brotector?tab=readme-ov-file#detections

workarounds can be
- using a custom compilled chromium to patch that detection
- make puppeteer not use `Runtime.enable` (will induce bugs, which have to be patched)

**Comment by zfcsoftware** [comment]
@ibrahimmus You can create and use the scanner with the scanner creation code in the file below. Recaptcha score is very good. Soon the library will initialize the scanner as in the file below.
https://github.com/zfcsoftware/cf-clearance-scraper/blob/main/module/browser.js

**Comment by zfcsoftware** [comment]
The library has been updated and this problem has been solved. It now gets 0.9 points.
