### ISSUE TITLE
Unable to automatically click the cloudflare captcha box

### ISSUE THREAD

**Issue by winktool** [zfcsoftware/puppeteer-real-browser#42]

**Comment by zfcsoftware** [comment]
Which site?

**Comment by winktool** [comment]
And
Can't pass the cloudflare captcha test when you have ```args: ["--auto-open-devtools-for-tabs"],

      customConfig: {
        devtools: true,
      },``` turned on

**Comment by winktool** [comment]
https://www.premint.xyz/login/?next=/dashboard/projects/

**Comment by winktool** [comment]
can use ```playwright``` instead of ```puppeteer```?

**Comment by zfcsoftware** [comment]
> And Can't pass the cloudflare captcha test when you have
> 
> ```
> args: ["--auto-open-devtools-for-tabs"],
>       customConfig: {
>         devtools: true,
>       }
> ```
> 
> turned on


Hello, it solves it without any problem as in the video. I have attached the code I used below, can you please test it? It will mostly not allow it on your normal computer when devtools is open. Opening developer tools is not a normal user action.


https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/5c0607a2-e546-4e8a-82b8-da8dd14ecef7

```
import { connect } from 'puppeteer-real-browser'

connect({
    turnstile: true,
})
    .then(async response => {
        const { browser, page } = response
        setInterval(() => {
            try { page.screenshot({ path: 'screenshot.png' }) } catch (e) { console.log(e.message);}
        }, 1000);
        await page.goto('https://www.premint.xyz/login/?next=/dashboard/projects/',{
            waitUntil: 'domcontentloaded'
        })
        for (let i = 0; i < 10; i++) {
            try {
                await page.reload({ waitUntil: 'domcontentloaded' })
            } catch (e) {
                console.log(e)
            }
        }
    })
    .catch(error => {
        console.log(error.message)
    })

```
