### ISSUE TITLE
Adding TypeScript Support.

### ISSUE THREAD

**Issue by TheRealStingo** [zfcsoftware/puppeteer-real-browser#43]
It will be very nice if we can get typescript support for a nice autocomplete and also because it cant be used in TS with modifying tsconfig file 
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/118802680/305158ec-c7de-4ee9-bca1-a39416a04a17)

**Comment by zfcsoftware** [comment]
Hello, unfortunately we can't add typescript support at the moment, but there is an old version with typescript support coded by @CrispyyBaconx, you can try it.

**Comment by elitan** [comment]
Here's what I did to get TypeScript to play nicely with this package:

1. Add a `./types/puppeteer-real-browser.d.ts` file:

```ts
import { Browser, Page } from "puppeteer";

declare module "puppeteer-real-browser" {
  export interface ConnectOptions {
    args?: string[];
    headless?: string;
    customConfig?: Record<string, any>;
    proxy?: {
      username?: string;
      password?: string;
    };
    skipTarget?: string[];
    fingerprint?: boolean;
    turnstile?: boolean;
    connectOption?: Record<string, any>;
    fpconfig?: Record<string, any>;
  }

  export interface ConnectResult {
    browser: Browser;
    page: Page;
    xvfbsession: any;
    cdpSession: any;
    chrome: any;
    setTarget: (options: { status: boolean }) => void;
  }

  export function connect(options: ConnectOptions): Promise<ConnectResult>;
}
```

2. Update the `tsconfig.json` file.

This will ensure that our `./types/puppeteer-real-browser.d.ts` file is considered by TypeScript.

```json
    "typeRoots": ["./types"],
```

For reference, here's my fill `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "ESNext",
    "moduleResolution": "node",
    "rootDir": "./src",
    "typeRoots": ["./types"],
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "include": ["./src/**/*"]
}
```

Hope it helps.
