### ISSUE TITLE
Question related Puppeteer-real-browser 

### ISSUE THREAD

**Issue by ptthien1012** [zfcsoftware/puppeteer-real-browser#44]
Hi, I really love your work.
I have some problems in login google in 3rd site. When click the button, it show to popup(new browser). 

![Uploading image (1).png…]()

**Comment by ptthien1012** [comment]
https://ibb.co/myTHSxr

**Comment by zfcsoftware** [comment]
Hello, thank you. This is google's own feature not related to our browser. When it opens in the new segment you can select it with browser.pages or click on the account with a chrome plugin.

**Comment by BopPham** [comment]
Hello, thanks for reply.
The image above that i do it manual.
This is result I use lib to running. It not view the login page to choose the account.
https://ibb.co/jghDTzQ

**Comment by BopPham** [comment]
Thanks you i will cose the issues

**Comment by BopPham** [comment]
Thank you. Please close this issue. I appreciate the work you've done.
