### ISSUE TITLE
Custom User data directory

### ISSUE THREAD

**Issue by PhucDao-PLab** [zfcsoftware/puppeteer-real-browser#46]
Hi everyone!
I try to use puppeteer with existing browser, but my profile does not load properly!
Here is my code

> 

> const { page, browser } = await connect({
>         executablePath: "D:\\GPMLogin\\gpm_browser\\gpm_browser_chromium_core_119\\chrome.exe",
>         headless: 'false',
>         args: [
>             '--user-data-dir=D:\\GPM\\9eea9e17-d2e9-400a-bd0f-249c49a0a7b4-3624',
>             '--window-size=640,640',
>          ],
>         customConfig: {},
>         skipTarget: [],
>         fingerprint: true,
>         turnstile: true,
>         connectOption: {}
>     })

Thank you so much!

**Comment by zfcsoftware** [comment]
Hello, there doesn't seem to be a problem. Could you have entered the wrong directory? Can you try / instead of \?


https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/409439ab-e2ee-45fe-80da-b9c4ec770e9b

```

(async () => {
    var { connect } = await import(__dirname + '/node_modules/puppeteer-real-browser/src/index.js')
    const { page, browser } = await connect({
    headless: 'auto',
    args: [
        `--user-data-dir=${__dirname}/9eea9e17-d2e9-400a-bd0f-249c49a0a7b4-3624`,
    ],
    customConfig: {},
    skipTarget: [],
    fingerprint: false,
    turnstile: true,
    connectOption: {},
    fpconfig: {},
    })
    
    try {
        setInterval(() => {
            page.screenshot({ path: 'screenshot.png' });
        }, 1000);
        await page.goto('https://jobnib.com/book/i-am-the-luna-chapter-32');
        console.log('OK');
        await page.waitForTimeout(30000);
    
    } catch (error) {
        console.error('Lỗi:', error);
    } finally {
        // await browser.close();
        // pool.end();
        // process.exit(1); 
    }
    })();
```

**Comment by MoonDoggie97** [comment]
I even tried using that script exactly it screenshotted the page but no directories were created.

**Comment by zfcsoftware** [comment]
> This was closed but it also doesnt work for me



> I even tried using that script exactly it screenshotted the page but no directories were created.


Please try this.
```

const fs = require('fs');
const path = require('path');

function createDirectoryIfNotExists(dirPath) {
    if (!fs.existsSync(dirPath)) {
        fs.mkdirSync(dirPath, { recursive: true });
    }
}

async function test() {
    const { connect } = await import('puppeteer-real-browser');
    createDirectoryIfNotExists(path.join(__dirname, 'zfc'));
    connect({

        customConfig: {
            userDataDir: './zfc',
        },
    })
        .then(async response => {
            const { browser, page } = response


            await page.goto('https://google.com')
            setInterval(() => {
                page.screenshot({ path: 'example.png' }).catch(error => { console.log(error.message) })
            }, 1000);
        })
        .catch(error => {
            console.log(error.message)
        })
}

test()

```
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/49f84f0d-71d9-4c9f-801b-618b7c439ce3)

**Comment by MoonAlt97** [comment]
It changes nothing the path already existed. When used with customconfig the page just opens as about:blank and it won’t go to any pages I tried using your fix for that from another issue (set target) but it did nothing

**Comment by MoonDoggie97** [comment]
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/105922597/726e6668-fe6c-4bf8-8b5d-3dae7bb130f5)
This is all that happens with your code it uses the directory but than it wont load any pages at all i copy pasted your code directly and made no change it created the directory opened chrome and than wouldnt go farther

**Comment by MoonDoggie97** [comment]
it also only puts three files in the directory the rest of the userdata like cookies etc isnt there.

**Comment by MoonDoggie97** [comment]
??

**Comment by MoonDoggie97** [comment]
This doesnt work man im not trying to be rude but its an issue and you claim it works fine but me and others all have the same issue

**Comment by zfcsoftware** [comment]
> This doesnt work man im not trying to be rude but its an issue and you claim it works fine but me and others all have the same issue


This is an open source project. As the readme file says, you can't make aggressive and demanding requests like this. I'm running Ubuntu and I had no problems when I tested it. I'll start a windows virtual machine and test it when I can. 

https://github.com/zfcsoftware/cf-clearance-scraper/blob/main/module/browser.js

You can try to open a browser and use it as in these codes. Please do not continue spamming. 

https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/e7a8482a-3aa0-4ffd-94a6-5b57f7a3aa58

**Comment by MoonDoggie97** [comment]
Look man im not spamming im trying to make you aware that the issue isnt "Solved" its an ongoing issue, im also not demanding anything, my posts were unacknowledged so i was unsure if you were taking the issue as an actual issue or just thinking its user error, i am on windows though and maybe that is why it works for you but not me i will try the code in browser.js and i will also try on linux and let you know if it works fine there vs windows

**Comment by sharpanimes** [comment]
Use normal puppeter once to initialize the directory which you want, then switch to puppeter-real-browser. I think there is an issue with initializing the user directory in this real-browser. Also use the customconfig parameter to specify the directory.

**Comment by MoonAlt97** [comment]
I’ve done both of those things  that did not fix it.

**Comment by xheatcodes** [comment]
> Use normal puppeter once to initialize the directory which you want, then switch to puppeter-real-browser. I think there is an issue with initializing the user directory in this real-browser. Also use the customconfig parameter to specify the directory.

It doesn't work because I tested if I save the data to ```localStorage``` by running it through puppeteer or just opening it as ```# chrome.exe --user-data-dir=... ```, and then through ```puppeteer-real-browser```, the data is not contained there, which means that ```puppeteer-real-browser``` uses a different directory

**Comment by xheatcodes** [comment]
It worked for me to specify the full path of the pre-created directory
```Javascript
customConfig: {
    userDataDir: full_path_created_directory,
}
```

P.S. The error on Windows is not in the `puppeteer-real-browser` module, but in the `chrome-launcher` module, the full path is not used there, because a temporary directory of user data is created

**Comment by GitCrypt091** [comment]
> > This was closed but it also doesnt work for me
> 
> > I even tried using that script exactly it screenshotted the page but no directories were created.
> 
> Please try this.
> 
> ```
> 
> const fs = require('fs');
> const path = require('path');
> 
> function createDirectoryIfNotExists(dirPath) {
>     if (!fs.existsSync(dirPath)) {
>         fs.mkdirSync(dirPath, { recursive: true });
>     }
> }
> 
> async function test() {
>     const { connect } = await import('puppeteer-real-browser');
>     createDirectoryIfNotExists(path.join(__dirname, 'zfc'));
>     connect({
> 
>         customConfig: {
>             userDataDir: './zfc',
>         },
>     })
>         .then(async response => {
>             const { browser, page } = response
> 
> 
>             await page.goto('https://google.com')
>             setInterval(() => {
>                 page.screenshot({ path: 'example.png' }).catch(error => { console.log(error.message) })
>             }, 1000);
>         })
>         .catch(error => {
>             console.log(error.message)
>         })
> }
> 
> test()
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/123484092/338161937-49f84f0d-71d9-4c9f-801b-618b7c439ce3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTMyNzEsIm5iZiI6MTcxOTkxMjk3MSwicGF0aCI6Ii8xMjM0ODQwOTIvMzM4MTYxOTM3LTQ5Zjg0ZjBkLTcxZDktNGM5Zi04MDFiLTYxOGI3YzQzOWNlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwOTM2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDlkNzRlNWM1MjE1N2NjMWEzYzc1Nzg4NjMwNDBlODg0M2UwNWNjNGM1Mzc0MDkxMWU4ZGE1YTZhYjhhYzY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oJWKAJ1MGleC7cg7xLjahuUug1fOJfduh03TKn9AYr8)

customConfig worked for me, thanks so much I searched forever. my solution:

`    const { page, browser } = await connect({
        // Specify the profile directory
        customConfig: {
            userDataDir: './User Data',
        },
        headless: false,
        executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chromes.exe',
        args: [

            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-features-ImprovedCookieControls',
            '--disable-extensions-except=C:\\dev\\app\\moonshot\\extension',
            '--load-extension=C:\\dev\\app\\project\\extension',
            '--user-data-dir=C:\\dev\\app\\project\\User Data',
            '--profile-directory=Profile 2'

        ],
        // Other options you may need
    });
    return { page, browser };`

**Comment by zfcsoftware** [comment]
The library has been updated. This problem should be solved. Can you try again now?

**Comment by xheatcodes** [comment]
It's working now, thanks

> The library has been updated. This problem should be solved. Can you try again now?
