### ISSUE TITLE
Update chromium

### ISSUE THREAD

**Issue by rtritto** [zfcsoftware/puppeteer-real-browser#5]
Current _chromium_ verison: 3.2171.3008 - published: 2016/04/27
Latest _chromium_ version: 3.0.3 - published: 2021/10/18 (latest publish)

Change `package.json`:
```diff
  "dependencies": {
-    "chromium": "^3.0.3",
+    "chromium": "3.0.3",
  }
```

I got this error on start:
```console
/node_modules/chromium/Chromium.js:2
  if(global.__TINT.Chromium) {
                   ^

TypeError: Cannot read properties of undefined (reading 'Chromium')

```

**Comment by zfcsoftware** [comment]
Hello,
- What exactly is it you want to do, upgrade the chrome version? Did you just change the version of the chromium package from "^3.0.3" to "3.0.3" in package.json?
- Which operating system are you using?

**Comment by rtritto** [comment]
Hello, I'm using Windows and yarn berry.
yarn with `^3.0.3` installs, as semantic version, the latest version of _3.x_ that is _3.2171.3008_, but _3.2171.3008_ is older than _3.0.3_.
When with the package manager is used install command, the _latest_ tag is used from _npm_ registry. Latest tag currently is _3.0.3_.

**Comment by rtritto** [comment]
Hello, I'm using Windows and yarn berry (`tarn add puppeteer-real-browser`).
yarn with `^3.0.3` installs, as semantic version, the latest version of _3.x_ that is _3.2171.3008_, but _3.2171.3008_ is older than _3.0.3_.
When with the package manager is used install command, the _latest_ tag is used from _npm_ registry. Latest tag currently is _3.0.3_.

**Comment by rtritto** [comment]
An alternative is to replace `chromium` with `@sparticuz/chromium`

**Comment by zfcsoftware** [comment]
@rtritto Thank you for taking care of the matter. I have only performed tests in the npm environment, please allow me to test the issue on 2 operating systems using yarn. It may take some time.  Thank you.

**Comment by rtritto** [comment]
You can simply check the generated _lock_ file.

Repro:
`yarn init -y`
`yarn set version berry` (optional)
`yarn add puppeteer-real-browser`

Also _npm_ have same default behavior of _yarn_.

_pnpm_ install lowest version in _package.json_.

---

The error is releted to the Windows OS.

---

Anyway `@sparticuz/chromium` is a maintained project, currently uses a newest Chromium version (119.x).
For the migration `127.0.0.1` needs to be replaced with `localhost` (see #4).

**Comment by zfcsoftware** [comment]
> You can simply check the generated _lock_ file.
> 
> Repro: `yarn init -y` `yarn set version berry` (optional) `yarn add puppeteer-real-browser`
> 
> Also _npm_ have same default behavior of _yarn_.
> 
> _pnpm_ install the lowest version in _package.json_.
> 
> The error is related to the Windows OS and can be fixed updating the Chromium version.
> 
> Anyway `@sparticuz/chromium` is a maintained project, currently uses a newest Chromium version (119.x). For the migration `127.0.0.1` needs to be replaced with `localhost` (see #4).

library has been updated as you specified. Please check it. Thank you for your contributions.

**Comment by rtritto** [comment]
I tested and it works, thanks!

**Comment by zfcsoftware** [comment]
thank you for your contribution
