### ISSUE TITLE
popup / new tab issue

### ISSUE THREAD

**Issue by Freevizion** [zfcsoftware/puppeteer-real-browser#50]
whenever I click on a url that opens a pop up or I "control" + click to open in a new tab
it doesn't open the url but shows about:blank

any idea how to fix this?

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#usage
setTarget You can solve this error with the function.

![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/0014e06f-ff62-4098-9e7f-791c115f24fd)

**Comment by Freevizion** [comment]
The problem with this is that now I can't pass cloudflare captcha it just reloads non stop and also now I have to enter proxy username and password manually

**Comment by zfcsoftware** [comment]
If you run setTarget({ status: true }) after you are done, you can pass it again. I can be more supportive if you add your code.

**Comment by Freevizion** [comment]
I was missing that you're right now it does pass captcha and ip works but I still have the same problem.
I click on a element which in turn opens a popup that popup is empty url is "about:blank" tried many things did my research no clue how to fix it.

![popup](https://github.com/zfcsoftware/puppeteer-real-browser/assets/7411392/34f44ba4-16d7-47ad-9075-c603cabf7ec5)
