### ISSUE TITLE
Question for viewport

### ISSUE THREAD

**Issue by ibrahimmus** [zfcsoftware/puppeteer-real-browser#51]
Any specific reason why you have width and height hard coded?

        await page.setViewport({
            width: 1920,
            height: 1080
        });

**Comment by zfcsoftware** [comment]
No there is not, the general width and height value is given so that the page is fully visible on the screen. You can change them.

**Comment by ibrahimmus** [comment]
Just to be sure that I am not missing any property that can be passed to connect method --

I can change these values with patching the existing solution, right? I am having really hard time to allign --window-size and this viewPort option..
