### ISSUE TITLE
CF looping

### ISSUE THREAD

**Issue by ledean** [zfcsoftware/puppeteer-real-browser#52]
Greetings,

when using an extension to generate new UA+Headers sometimes cloudflare seems to flag it and then its looping(solving again and again)
Is there a way to make an check so that it only trys 1-3 times to solve cloudflare and afterwards its closes and gives an error?

**Comment by zfcsoftware** [comment]
Hello, it is probably detected because the user agent and fingerprint information do not match. The library is stable as long as the user agent is not changed. Changing user agent is a topic I am following. I will update this topic when an update is available.

**Comment by andyiyass** [comment]
yeps.. i'm waiting for next update to fix useragent problem.. thanks

**Comment by ledean** [comment]
Maybe you can implement fingerprint suite into your script

**Comment by zfcsoftware** [comment]
This issue has been resolved thanks to @TheFalloutOf76. The library has been updated and tested on a Linux server. There should not be any problems now.
If you continue to experience this issue, please open a new one.

https://github.com/TheFalloutOf76/CDP-bug-MouseEvent-.screenX-.screenY-patcher

https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#docker
