### ISSUE TITLE
Enable ad blocking feature

### ISSUE THREAD

**Issue by alextran317** [zfcsoftware/puppeteer-real-browser#55]
Can you add ad-blocking feature to puppeteer-real-browser? Thank you for creating such an awesome library.

**Comment by zfcsoftware** [comment]
Thanks for using the library and providing feedback. This will be possible with an update in the near future.

**Comment by alextran317** [comment]
I tried following the instructions but was unsuccessful. Could you please add an ad-blocking feature and provide user-friendly guidance for configuration? Thank you very much for the package

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/puppeteer-real-browser/issues/32#issuecomment-2198113458
