### ISSUE TITLE
Creating a new page hangs.

### ISSUE THREAD

**Issue by JortsEnjoyer0** [zfcsoftware/puppeteer-real-browser#59]
I'm not sure if I'm doing something wrong, but creating a 2nd page other than the first one after calling puppeteer.connect() just hangs until the timeout triggers.

**Comment by JortsEnjoyer0** [comment]
I found that you must use setTarget({status:false}) before creating a new page then set it back to true after, but it's not clear what this does.

**Comment by zfcsoftware** [comment]
> I found that you must use setTarget({status:false}) before creating a new page then set it back to true after, but it's not clear what this does.

To avoid getting caught, targetFilter is used and puppeteer is disabled in some places. Some places also include the function to open a new tab. There is an example for this in the readme file. Please use it.
