### ISSUE TITLE
Huge Stealth Improvment.

### ISSUE THREAD

**Issue by TheRealStingo** [zfcsoftware/puppeteer-real-browser#61]
Instead of using Runtime.enable() to execute the cloudfalre click , why dont you intercept the request of cloudflare and modify the challenge response body with a click (  ll attach it down here ) that will execute by itself rather than using Runtime which is easilty detectable , example of click is in this lib https://github.com/Akmal-CloudFreed/CloudFreed-CloudFlare-bypass

**Comment by zfcsoftware** [comment]
The library has been updated and the CDP session has been completely removed. Recaptcha v3 detects it anyway. In the future this library will be updated to create a browser like the browser.js file below.
https://github.com/zfcsoftware/cf-clearance-scraper/blob/main/module/browser.js
