### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by MoonDoggie97** [zfcsoftware/puppeteer-real-browser#62]
userDataDir: "./userdata" doesnt seem to work whats the proper way to get userDataDir to work?

Also setting the viewport doesnt seem to work how do we do that?

**Comment by MoonDoggie97** [comment]
Cool thanks for the answer.

**Comment by zfcsoftware** [comment]
> userDataDir: "./userdata" doesnt seem to work whats the proper way to get userDataDir to work?
> 
> Also setting the viewport doesnt seem to work how do we do that?


Please try this.

https://github.com/zfcsoftware/puppeteer-real-browser/issues/46#issuecomment-2158069120
