### ISSUE TITLE
 npm i puppeteer-real-browser doesnt work

### ISSUE THREAD

**Issue by anil-turk** [zfcsoftware/puppeteer-real-browser#63]
OS: Windows 11
```
 npm i puppeteer-real-browser
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

```

**Comment by zfcsoftware** [comment]
This is not caused by the library. It is probably due to git not being installed on your computer.
download: https://git-scm.com/download/win

run: `npm cache clean --force`

Can you give it a try?

**Comment by anil-turk** [comment]
I installed git which it should had that already.  and after cleaning the cache gave the same error.

**Comment by zfcsoftware** [comment]
> npm ERR! code ENOENT
> npm ERR! syscall spawn git
> npm ERR! path git
> npm ERR! errno -4058
> npm ERR! enoent An unknown git error occurred
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent

https://stackoverflow.com/questions/56987664/npm-err-enoent-undefined-when-running-npm-install

You may not have git active in your terminal, restart your computer, if the problem persists, you can add git as a path with the following path. Can you check if the git --version command is active in that terminal? If not, you can try with a new terminal. If the problem persists, you can try the following steps.

Open the Start Menu, search for "Environment Variables," and select "Edit the system environment variables."
In the System Properties window, click on the "Environment Variables" button.
In the Environment Variables window, find the "Path" variable in the "System variables" section and select it. Click "Edit."
In the Edit Environment Variable window, click "New" and add the path to your Git bin and cmd folders. This is usually C:\Program Files\Git\bin and C:\Program Files\Git\cmd.
Click "OK" to close all windows.

**Comment by anil-turk** [comment]
it worked after using git cmd terminal.
by the way the thing is it opens the browser and redirects successfully to the page. but on terminal we only see the codes of cloudflare page it doesnt bring the code after it.
`connect({
          turnstile: true
      })
          .then(async response => {
              const { page, browser, setTarget } = response

              page.goto('https://you.com/api/streamingSearch?q=${encodeURIComponent(query)}&page=${pageNumber}&count=10&domain=youchat', {
                  waitUntil: 'domcontentloaded'
              })

              setTarget({ status: false })
              const content = await page.content();
              console.log(content);

          })`

**Comment by zfcsoftware** [comment]
> it worked after using git cmd terminal. by the way the thing is it opens the browser and redirects successfully to the page. but on terminal we only see the codes of cloudflare page it doesnt bring the code after it.
> 
> ```
> connect({
>           turnstile: true
>       })
>           .then(async response => {
>               const { page, browser, setTarget } = response
> 
>               page.goto('https://you.com/api/streamingSearch?q=${encodeURIComponent(query)}&page=${pageNumber}&count=10&domain=youchat', {
>                   waitUntil: 'domcontentloaded'
>               })
> 
>               setTarget({ status: false })
>               const content = await page.content();
>               console.log(content);
> 
>           })
> ```

domcontentloaded is completed when the dom load event is triggered. This is triggered when the page is finished loading, even if it is cloudflare. Instead, you can wait for an html element in the incoming html content after cloudflare after the goto function.
```
connect({
    turnstile: true
})
    .then(async response => {
        const { page, browser, setTarget } = response

        page.goto('https://you.com/api/streamingSearch?q=${encodeURIComponent(query)}&page=${pageNumber}&count=10&domain=youchat', {
            waitUntil: 'domcontentloaded'
        })
        await page.waitForSelector('pre')
        setTarget({ status: false })
        const content = await page.content();
        console.log(content);

    })
```

**Comment by anil-turk** [comment]
it does not wait for response. normally after this response it starts to give token answers but browser doesnt wait for it 
 ```

event: thirdPartySearchResults
data: {"ranked_apps": [], "top_ranked_apps": [], "meta_ranking_info": {}, "search": {"third_party_related_results": [], "third_party_places_results": [], "third_party_search_results": [], "third_party_image_results": [], "third_pa
rty_video_results": [], "third_party_news_results": [], "third_party_computation_results": {}, "third_party_translations_results": {}, "third_party_timezone_results": {}, "third_party_entity_results": [], "rankings": {}, "estimate
d_matches": 0, "query_context": {}, "relevance_filter_context": {}, "mainline_ranked_apps": [], "sideline_ranked_apps": [], "pre_rerank_mainline_ranked_apps": [], "pre_rerank_sideline_ranked_apps": [], "meta_ranking_info": {}}, "t
ime": 1718826016.4298623, "query": "prompt"}

event: youChatIntent
data: {"llm_intent": "Creative Writing", "llm_intent_prob_map": {"Creative Writing": 0.38, "General Information Search": 0.365, "Request For Rewriting": 0.17, "Computation, Conversions, and Calculations": 0.033, "Linguistic Quiz":
 0.013, "Correct Previous Response": 0.013, "News and Current Events": 0.008, "Request To Continue": 0.005, "Request For Code": 0.004, "Casual Chitchat": 0.002}, "is_personalizable_query": false, "is_search_required_intent": false, "question_language": "en"}

event: appRankings
data: {"mainline_ranked_apps": ["youchat"], "sideline_ranked_apps": [], "meta_ranking_info": {}, "llm_apps": null, "heuristic_apps": null, "high_ranked_apps": null, "low_ranked_apps": null, "pre_rerank_mainline_ranked_apps": [], "pre_rerank_sideline_ranked_apps": []}

event: youChatAppRankings
data: ["youChatResponse"]

event: relatedSearches
data: {"relatedSearches": []}

</pre></body></html>

[INFO] [PUPPETEER-REAL-BROWSER] | Browser Disconnected
```

Missing part is: 
```
event: youChatAppRankings
data: ["youChatResponse"]

event: youChatToken
data: {"youChatToken": ""}

event: youChatToken
data: {"youChatToken": "I"}

event: youChatToken
data: {"youChatToken": "'m"}

event: youChatToken
data: {"youChatToken": " sorry"}

event: youChatToken
data: {"youChatToken": ","}

event: youChatToken
data: {"youChatToken": " I"}

event: youChatToken
data: {"youChatToken": " cannot"}

event: youChatToken
data: {"youChatToken": " fulfill"}

event: youChatToken
data: {"youChatToken": " that"}

event: youChatToken
data: {"youChatToken": " request"}

event: youChatToken
data: {"youChatToken": "."}

event: abTestSlices
data: {"exactAbTestSlices": {"abUseHybridSnippets": "neither"}}

event: done
data: I'm Mr. Meeseeks. Look at me.
```
