### ISSUE TITLE
captcha issue

### ISSUE THREAD

**Issue by akwin1234** [zfcsoftware/puppeteer-real-browser#64]
i am making some automation project it needs to login in certain website.
when i try to login it keeps saying captcha modules are not initiated in the website i am trying to login into.

my code:

        const { page, browser, setTarget } = response
        const { width, height } = await page.evaluate(() => {
            return {
                width: window.screen.width,
                height: window.screen.height
            };
        });

        await page.setViewport({ width, height });
        await loadCookies(browser);
        setTarget({ status: true });
        await page.goto('https://stake.com/', {
            waitUntil: 'domcontentloaded'
        })
        
        await sleep(7000);
        setTarget({ status: false });
        await page.reload(); // tried to remove this too nothing worked.

        await sleep(7000);
        setTarget({ status: false });
        
      
      
      I have tried setTarget({ status: false }); and etc. but nothing is working. How do i make puppeteer-real-browser not to alter website once captcha solving or cdn bypassing has been done?

**Comment by zfcsoftware** [comment]
The sample site doesn't open and I don't understand the problem you are having. Can you show it with a video?
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/1279049b-4818-4414-816a-bb9b9b3752bb)
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/0f407e82-fe8c-44f8-b0e3-bbf6e76c5913)

**Comment by akwin1234** [comment]
> The sample site doesn't open and I don't understand the problem you are having. Can you show it with a video? 
Sure here is the video & my code

`import { connect } from 'puppeteer-real-browser';
import fs from 'fs';

async function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}


connect({
    turnstile: false,
    fingerprint: false
})
.then(async response => {
        const { page, browser, setTarget } = response
        const { width, height } = await page.evaluate(() => {
            return {
                width: window.screen.width,
                height: window.screen.height
            };
        });
    

        await page.setViewport({ width, height });
 
        setTarget({ status: true });
        await page.goto('https://stake.com/', {
            waitUntil: 'domcontentloaded'
        })
        
        await sleep(7000);
        setTarget({ status: false });  
        await page.reload();
    
        await sleep(7000);
        setTarget({ status: false }); // this code doesnt help me load captchas even if i wait around. same error comes.
 

})
`

https://github.com/zfcsoftware/puppeteer-real-browser/assets/15890770/274d3bc5-501a-47ff-b26e-1c5d229e33e2

**Comment by sharpanimes** [comment]
Use dev tools to check the network tab and check which scripts are failing to load...

**Comment by zfcsoftware** [comment]
This issue has been resolved thanks to @TheFalloutOf76. The library has been updated and tested on a Linux server. There should not be any problems now.
If you continue to experience this issue, please open a new one.

https://github.com/TheFalloutOf76/CDP-bug-MouseEvent-.screenX-.screenY-patcher

https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#docker
