### ISSUE TITLE
StealthPlugin don't work with puppeteer-real-browser

### ISSUE THREAD

**Issue by moygospadin** [zfcsoftware/puppeteer-real-browser#66]
StealthPlugin don't work with puppeteer-real-browser

I'm tried connect StealthPlugin in different ways. 

1. Before puppeteer-real-browser dynamic import
2. On function root
3. On puppeteer-real-browser code base
It don't give any results. 
ENV
 "puppeteer-extra-plugin-stealth": "^2.11.2",
  "puppeteer-real-browser": "^1.2.18",
  "puppeteer-extra": "^3.3.6",
OS: Linux

Attached 2 screenshoots, it's different browsers launch, but UA is the same.

![error_screen0 650467975599125error](https://github.com/zfcsoftware/puppeteer-real-browser/assets/60549587/56258bfe-cee5-4df6-b9a3-246ba5a6efd6)
![error_screen0 5429763813137751error](https://github.com/zfcsoftware/puppeteer-real-browser/assets/60549587/c6e15072-3cf5-4ee3-b0f2-a762670fb093)

**Comment by Kill6r** [comment]
You find an solution?

**Comment by moygospadin** [comment]
> You find an solution?
Yes, you can read following 
https://github.com/zfcsoftware/puppeteer-real-browser/issues/32
BTW i think that it will not help, the better solution to bypass bot detection is launch chrome production browser mannually with startpage(which you need), after some botdetection request you can connect via CDP, and do what you want

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/puppeteer-real-browser/issues/32#issuecomment-2198113458
