### ISSUE TITLE
Error when Connecting to puppeteer-real-browser

### ISSUE THREAD

**Issue by TheRealStingo** [zfcsoftware/puppeteer-real-browser#70]
When sometimes i loop to open multple instances i get these errors

 Error: read ECONNRESET
     at file:///root/stingolverjs/node_modules/puppeteer-real-browser/src/module/chromium.js:95:19
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 Error: connect ECONNREFUSED 127.0.0.1:37405
     at file:///root/stingolverjs/node_modules/puppeteer-real-browser/src/module/chromium.js:85:27
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async file:///root/stingolverjs/node_modules/puppeteer-real-browser/src/module/chromium.js:76:33
 You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: connect ECONNREFUSED 127.0.0.1:37405
    at file:///root/stingolverjs/node_modules/puppeteer-real-browser/src/module/chromium.js:95:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 Error: read ECONNRESET
    at file:///root/stingolverjs/node_modules/puppeteer-real-browser/src/module/chromium.js:85:27
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///root/stingolverjs/node_modules/puppeteer-real-browser/src/module/chromium.js:76:33
 You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:

**Comment by sharpanimes** [comment]
Any chance you are using proxy?

**Comment by TheRealStingo** [comment]
> Any chance you are using proxy?

Yes , i am , did you face similar issue ?

**Comment by sharpanimes** [comment]
Yeah, it probably happens when some site refuses to work with the given proxy. Happens randomly for me.. I just restart my app every 15mins regardless of failure so that it works continuously...

**Comment by zfcsoftware** [comment]
This issue should be resolved, can you check again?

**Comment by zfcsoftware** [comment]
I am closing this issue for now. If the problem persists, you can write a message to this issue.
