### ISSUE TITLE
How to hide "Browser Disconnected" logs

### ISSUE THREAD

**Issue by AlekseyMelikov** [zfcsoftware/puppeteer-real-browser#71]
Is there a way to disable logs "[INFO] [PUPPETEER-REAL-BROWSER] | Browser Disconnected"  when browser.close()?

**Comment by alshahabrezvi** [comment]
> Is there a way to disable logs "[INFO] [PUPPETEER-REAL-BROWSER] | Browser Disconnected"  when browser.close()?

I also want to know

**Comment by agarpolices** [comment]
> > Is there a way to disable logs "[INFO] [PUPPETEER-REAL-BROWSER] | Browser Disconnected"  when browser.close()?
> 
> I also want to know

edit the package

**Comment by zfcsoftware** [comment]
This problem has been solved. Please check again with the latest version.
