### ISSUE TITLE
Request for new feature 

### ISSUE THREAD

**Issue by alshahabrezvi** [zfcsoftware/puppeteer-real-browser#72]
Hi,  at first you have done really nice work..i am using it in my daily use  But i need a feature. I think it will make this package more useful. Can you add headless browser hidden option in windows also? After developed bot It's annoying to see browser is opened.. And working.. 

I think you will read this and work on this topic. Thanks in advance😊

**Comment by zfcsoftware** [comment]
Hello, thank you. On Linux it is hidden thanks to xvfb, but I don't know the alternative on windows. You can run it on wsl on Windows using the Dockerfile in the library home directory.
