### ISSUE TITLE
Missing Sec-CH-UA headers, no audio devices, some built-in Google Chrome functions missing

### ISSUE THREAD

**Issue by cottnn** [zfcsoftware/puppeteer-real-browser#73]
I've ran some tests via https://bot.incolumitas.com/ using puppeteer-real-browser on a Debian Linux VPS and compared it with test results on Linux Mint using Google Chrome (Flatpak), both have version 126.0.6478.114

There were some differences that could be used in detection, namely:
- puppeteer-real-browser was missing some Sec-CH-UA hints, in particular: `"sec-ch-ua": "\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\", \"Google Chrome\";v=\"126\""`
`"sec-ch-ua-mobile": "?0"`
`"sec-ch-ua-platform": "\"Linux\""`
- both "speakers" and "micros" were 0, which is rather untypical
- Some built-in functions were missing, mostly ad-related stuff, like `joinAdInterestGroup`, `updateAdInterestGroups`, etc

I attached a diff of the test results on the VPS and on the Linux Mint VM
[diff.txt](https://github.com/user-attachments/files/15946135/diff.txt)

**Comment by zfcsoftware** [comment]
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.
