### ISSUE TITLE
Not input data to form

### ISSUE THREAD

**Issue by vietnux** [zfcsoftware/puppeteer-real-browser#75]
Why when I turn on the browser, here is a login form, the data does not fill in automatically but has to wait until I turn on deptool (f12) to start working. If I don't turn it on, the tool stays in a waiting state. like that and do nothing?

await page.goto('https://www.redbubble.com/auth/login', { waitUntil: 'networkidle2' });  => done
await page.waitForSelector("#ReduxFormInput1"); **=> wait a here, not fill data until f12 is pressed**
await page.type('#ReduxFormInput1', email);
...

**Comment by zfcsoftware** [comment]
Can you try again? This problem should be fixed.

**Comment by vietnux** [comment]
> Can you try again? This problem should be fixed.

i runned. but i has problem with zazzle.com, captcha of zazzle i can not bypass
please help my
