### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by LeninZapata** [zfcsoftware/puppeteer-real-browser#79]
When installing I have this error. It seems like a version thing. How can I solve it? 
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/42600954/bcb7202d-767a-4d8b-b4c4-f31f868f15ce)

**Comment by zfcsoftware** [comment]
This issue should be resolved, can you check again?

**Comment by zfcsoftware** [comment]
If the problem persists, please update with a message here. Closing for now.
