### ISSUE TITLE
Unable to complete the Cloudflare challenge when using a proxy

### ISSUE THREAD

**Issue by Snadjim** [zfcsoftware/puppeteer-real-browser#80]
Hello, 

A few days ago I noticed that you can no longer bypass cloudflare when using a proxy. You can see that the checkbox is ticked but then it comes up again and again.

Is there a way of solving this problem? 

Regards,

Nad

**Comment by EgglezosK** [comment]
Facing the same issue, will investigate also the solution

**Comment by Snadjim** [comment]
Ok thank you. In the past I had this problem with selenium and to solve the problem I opened a second tab with the page where there is cloudflare and it worked. But here I can't open a second tab....

**Comment by chlwodud77** [comment]
I also faced with the same issue and tested with several times but same result.
Selecting checking cloudflare checkbox by selector is no more available to bypass..
Also same with sending press key `tab + spacebar` to avoid block.

I think should change bypass solution by moving mouse pointer to checkbox and click.

**Comment by zfcsoftware** [comment]
I just tested with free and corporate plan Captcha with proxies from Webshare and had no problems. You can try sending the fingerprint variable false and changing the proxy.

**Comment by Snadjim** [comment]
Hi @zfcsoftware, 

I also try with my webshare proxy and still doesn't work. And howI can find the fake variable fingerprint and change the proxy?

**Comment by EgglezosK** [comment]
> I just tested with free and corporate plan Captcha with proxies from Webshare and had no problems. You can try sending the fingerprint variable false and changing the proxy.

I just test it with proxies (Webshare) the result is this: 

[https://gyazo.com/14046e9a2b82506524a56131cef3ee93](url)

this is the testing code: 

`import { connect } from 'puppeteer-real-browser'
const proxy_uname = '-';
const proxy_pass = '-';
const proxy_ip = "-";

connect({
  headless: 'auto',
  args: [],
  customConfig: {},
  skipTarget: [],
  fingerprint: false,
  turnstile: true,
  connectOption: {},
  fpconfig: {},
  proxy: {
    host: "-",
    port: "-",
    username: '-',
    password: '-'
  }

})
  .then(async response => {
    const { browser, page } = response
    await page.goto('https://nopecha.com/demo/cloudflare')
  })
  .catch(error => {
    console.log(error.message)
  })`

**Comment by zfcsoftware** [comment]
> > I just tested with free and corporate plan Captcha with proxies from Webshare and had no problems. You can try sending the fingerprint variable false and changing the proxy.
> 
> I just test it with proxies (Webshare) the result is this:
> 
> https://gyazo.com/14046e9a2b82506524a56131cef3ee93
> 
> this is the testing code:
> 
> `import { connect } from 'puppeteer-real-browser' const proxy_uname = '-'; const proxy_pass = '-'; const proxy_ip = "-";
> 
> connect({ headless: 'auto', args: [], customConfig: {}, skipTarget: [], fingerprint: false, turnstile: true, connectOption: {}, fpconfig: {}, proxy: { host: "-", port: "-", username: '-', password: '-' }
> 
> }) .then(async response => { const { browser, page } = response await page.goto('https://nopecha.com/demo/cloudflare') }) .catch(error => { console.log(error.message) })`
> 
> UPDATE
> 
> I give a try with turnstile:false and proxies and manually hit the tick button and access it normally. turbstile somehow being detected?

I've just tested it on windows and linux and it's impossible for it not to work.

```
git clone https://github.com/zfcsoftware/puppeteer-real-browser
cd puppeteer-real-browser
npm install
node src/test.js
```
This way you can run the test.

**Comment by EgglezosK** [comment]
> > > I just tested with free and corporate plan Captcha with proxies from Webshare and had no problems. You can try sending the fingerprint variable false and changing the proxy.
> > 
> > 
> > I just test it with proxies (Webshare) the result is this:
> > https://gyazo.com/14046e9a2b82506524a56131cef3ee93
> > this is the testing code:
> > `import { connect } from 'puppeteer-real-browser' const proxy_uname = '-'; const proxy_pass = '-'; const proxy_ip = "-";
> > connect({ headless: 'auto', args: [], customConfig: {}, skipTarget: [], fingerprint: false, turnstile: true, connectOption: {}, fpconfig: {}, proxy: { host: "-", port: "-", username: '-', password: '-' }
> > }) .then(async response => { const { browser, page } = response await page.goto('https://nopecha.com/demo/cloudflare') }) .catch(error => { console.log(error.message) })`
> > UPDATE
> > I give a try with turnstile:false and proxies and manually hit the tick button and access it normally. turbstile somehow being detected?
> 
> I've just tested it on windows and linux and it's impossible for it not to work.
> 
> ```
> git clone https://github.com/zfcsoftware/puppeteer-real-browser
> cd puppeteer-real-browser
> npm install
> node src/test.js
> ```
> 
> This way you can run the test.

I just run it, with out proxies working well, but while enable proxies ( Webshare ) it keeps reloading and the logs of the terminal is like this: 

Start of test.js
Connected to browser
Navigated to page

until get timeout ( 60s )

Somehow trunstile detected

**Comment by zfcsoftware** [comment]
> > > > I just tested with free and corporate plan Captcha with proxies from Webshare and had no problems. You can try sending the fingerprint variable false and changing the proxy.
> > > 
> > > 
> > > I just test it with proxies (Webshare) the result is this:
> > > https://gyazo.com/14046e9a2b82506524a56131cef3ee93
> > > this is the testing code:
> > > `import { connect } from 'puppeteer-real-browser' const proxy_uname = '-'; const proxy_pass = '-'; const proxy_ip = "-"; connect({ headless: 'auto', args: [], customConfig: {}, skipTarget: [], fingerprint: false, turnstile: true, connectOption: {}, fpconfig: {}, proxy: { host: "-", port: "-", username: '-', password: '-' } }) .then(async response => { const { browser, page } = response await page.goto('https://nopecha.com/demo/cloudflare') }) .catch(error => { console.log(error.message) })`
> > > UPDATE
> > > I give a try with turnstile:false and proxies and manually hit the tick button and access it normally. turbstile somehow being detected?
> > 
> > 
> > I've just tested it on windows and linux and it's impossible for it not to work.
> > ```
> > git clone https://github.com/zfcsoftware/puppeteer-real-browser
> > cd puppeteer-real-browser
> > npm install
> > node src/test.js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This way you can run the test.
> 
> I just run it, with out proxies working well, but while enable proxies ( Webshare ) it keeps reloading and the logs of the terminal is like this:
> 
> Start of test.js Connected to browser Navigated to page
> 
> until get timeout ( 60s )
> 
> Somehow trunstile detected

zfcsoftware@gmail.com
Can you send your anydesk id to my mail?
https://anydesk.com/en

**Comment by ziaq** [comment]
Emulate real mouse movement and a click on the checkbox - it works without even trying to mimic human behavior. Just teleport the cursor to the checkbox and click immediately. 

Here's a simple Autohotkey script:
```
#Requires AutoHotkey v2.0
CoordMode("Mouse", "Window")  ; Sets the mouse coordinates relative to the active window

x := A_Args[1]  ; Takes the first argument as the x-coordinate
y := A_Args[2]  ; Takes the second argument as the y-coordinate

MouseMove x, y, 50  ; 50 is speed
Click  ;

ExitApp  ;
```

Pass the coordinates of the checkbox to it and run it using exec:
```
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const cloudflareBypassScriptPath = path.join(__dirname, 'cloudflare-bypass-script.ahk');

async function clickInCloudflareCheckbox(page: Page): Promise<void> {
  try {
    const elements = await page.$$('iframe');

    for (const element of elements) {
      const iframeSrcURL = await element.evaluate(node => node.src);
      if (!iframeSrcURL.includes('turnstile')) continue;

      const box = await element.boundingBox();
      if (!box) continue;

      const x = box.x * 2.4; // Manually curated adjustment coefficient
      const y = box.y * 3.8; // Manually curated adjustment coefficient
      
      exec(`"${cloudflareBypassScriptPath}" ${x} ${y}`);
      return;
    }
  } catch (error) {
    throw new Error(`Error in clickInCloudflareCheckbox. Error: ${error}`);
  }
}
```

**Comment by EgglezosK** [comment]
> Emulate real mouse movement and a click on the checkbox - it works without even trying to mimic human behavior. Just teleport the cursor to the checkbox and click immediately.
> 
> Here's a simple Autohotkey script:
> 
> ```
> #Requires AutoHotkey v2.0
> CoordMode("Mouse", "Window")  ; Sets the mouse coordinates relative to the active window
> 
> x := A_Args[1]  ; Takes the first argument as the x-coordinate
> y := A_Args[2]  ; Takes the second argument as the y-coordinate
> 
> MouseMove x, y, 50  ; 50 is speed
> Click  ;
> 
> ExitApp  ;
> ```
> 
> Pass the coordinates of the checkbox to it and run it using exec:
> 
> ```
> const __dirname = path.dirname(fileURLToPath(import.meta.url));
> const cloudflareBypassScriptPath = path.join(__dirname, 'cloudflare-bypass-script.ahk');
> 
> async function clickInCloudflareCheckbox(page: Page): Promise<void> {
>   try {
>     const elements = await page.$$('iframe');
> 
>     for (const element of elements) {
>       const iframeSrcURL = await element.evaluate(node => node.src);
>       if (!iframeSrcURL.includes('turnstile')) continue;
> 
>       const box = await element.boundingBox();
>       if (!box) continue;
> 
>       const x = box.x * 2.4; // Manually curated adjustment coefficient
>       const y = box.y * 3.8; // Manually curated adjustment coefficient
>       
>       exec(`"${cloudflareBypassScriptPath}" ${x} ${y}`);
>       return;
>     }
>   } catch (error) {
>     throw new Error(`Error in clickInCloudflareCheckbox. Error: ${error}`);
>   }
> }
> ```

Can you give a full example please?

**Comment by ziaq** [comment]
If this post gets 10 likes, I'll share how to get Autohotkey working on a VPS 😄

**Comment by chlwodud77** [comment]
@ziaq It seems AutoHotKey works on windows, then your script doesn't work on linux?

**Comment by ziaq** [comment]
> @ziaq It seems AutoHotKey works on windows, then your script doesn't work on linux?

Yes, this solution is specifically for Windows, but I believe there are similar tools available for Linux with GUI too.

**Comment by zfcsoftware** [comment]
> > @ziaq It seems AutoHotKey works on windows, then your script doesn't work on linux?
> 
> Yes, this solution is specifically for Windows, but I believe there are similar tools available for Linux with GUI too.

In an open source project you cannot stipulate conditions for sharing information. 

I have examined the problem. I have tried many ways like windows, ubuntu, docker etc. and I have no problem. I think the problem is caused by the proxy country and the browser language not matching. 

 
corporate plan works fine on Cloudflare as in the video. Proxy used.

https://github.com/zfcsoftware/puppeteer-real-browser/assets/123484092/f767f947-2112-41b0-a840-3f5d61f9e5bd

**Comment by EgglezosK** [comment]
> > > @ziaq It seems AutoHotKey works on windows, then your script doesn't work on linux?
> > 
> > 
> > Yes, this solution is specifically for Windows, but I believe there are similar tools available for Linux with GUI too.
> 
> In an open source project you cannot stipulate conditions for sharing information.
> 
> I have examined the problem. I have tried many ways like windows, ubuntu, docker etc. and I have no problem. I think the problem is caused by the proxy country and the browser language not matching.
> 
> corporate plan works fine on Cloudflare as in the video. Proxy used.
> 
>  2024-07-04.11-31-41.mp4

Hello @zfcsoftware , i am not sure about the language because i test it out with same country as my browser language and same origin website. Without proxy can bypass the cloudflare, with proxies from my country origin ( same as browser language ) still facing issue. 

Any idea?

**Comment by EgglezosK** [comment]
> > > > > @ziaq It seems AutoHotKey works on windows, then your script doesn't work on linux?
> > > > 
> > > > 
> > > > Yes, this solution is specifically for Windows, but I believe there are similar tools available for Linux with GUI too.
> > > 
> > > 
> > > In an open source project you cannot stipulate conditions for sharing information.
> > > I have examined the problem. I have tried many ways like windows, ubuntu, docker etc. and I have no problem. I think the problem is caused by the proxy country and the browser language not matching.
> > > corporate plan works fine on Cloudflare as in the video. Proxy used.
> > > 2024-07-04.11-31-41.mp4
> > 
> > 
> > Hello @zfcsoftware , i am not sure about the language because i test it out with same country as my browser language and same origin website. Without proxy can bypass the cloudflare, with proxies from my country origin ( same as browser language ) still facing issue.
> > Any idea?
> 
> Maybe it's webrtc, but in that case it shouldn't work for me either. Interesting problem. Could you please test with docker on wsl? https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#docker

@zfcsoftware no luck at all, 
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/24476482/a52803bd-1d0d-44f2-a5dc-dc36893f84ee)

facing the same issue.

maybe can i give you anydesk, and try with your proxy in my system to check the results?

**Comment by zfcsoftware** [comment]
> > > > > > @ziaq It seems AutoHotKey works on windows, then your script doesn't work on linux?
> > > > > 
> > > > > 
> > > > > Yes, this solution is specifically for Windows, but I believe there are similar tools available for Linux with GUI too.
> > > > 
> > > > 
> > > > In an open source project you cannot stipulate conditions for sharing information.
> > > > I have examined the problem. I have tried many ways like windows, ubuntu, docker etc. and I have no problem. I think the problem is caused by the proxy country and the browser language not matching.
> > > > corporate plan works fine on Cloudflare as in the video. Proxy used.
> > > > 2024-07-04.11-31-41.mp4
> > > 
> > > 
> > > Hello @zfcsoftware , i am not sure about the language because i test it out with same country as my browser language and same origin website. Without proxy can bypass the cloudflare, with proxies from my country origin ( same as browser language ) still facing issue.
> > > Any idea?
> > 
> > 
> > Maybe it's webrtc, but in that case it shouldn't work for me either. Interesting problem. Could you please test with docker on wsl? https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#docker
> 
> @zfcsoftware no luck at all, ![image](https://private-user-images.githubusercontent.com/24476482/346067482-a52803bd-1d0d-44f2-a5dc-dc36893f84ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzEzMTksIm5iZiI6MTcyMDE3MTAxOSwicGF0aCI6Ii8yNDQ3NjQ4Mi8zNDYwNjc0ODItYTUyODAzYmQtMWQwZC00NGYyLWE1ZGMtZGMzNjg5M2Y4NGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA5MTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMDE1MWU3YTE4YTI4YTI1ZDA5NzlhMWQ1MDE0YzQ2Y2FhM2FiMzhiMTQyZDg1Mzc0YTllMjhlYmJjY2FhYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q4FfP_qTdhBSM_r3OLMdJ1l5vS4_vfHJKXFNWB_JZyc)
> 
> facing the same issue.
> 
> maybe can i give you anydesk, and try with your proxy in my system to check the results?

Sounds like a problem with your computer. Can you rent a vps from a server provider like Vultr and test it?

**Comment by EgglezosK** [comment]
@zfcsoftware I don't think its my computer problem, i test it out on two laptops , one desktop and two VPS with Ubuntu 18.04 and 22.04.4 with same results. Maybe something wrong with my installation? Who knows.... 

**### Good News!**

After 3 days with a lot of research and tries, using your library @zfcsoftware and the main idea of @ziaq i think that i figure out how to make it work with VPS on Ubuntu and Windows while using proxies. 

I am going to make a try of my installation on a clean VPS to make sure that my solutions is working and its robust and i will post here step by step guide how to do the same. 


https://github.com/zfcsoftware/puppeteer-real-browser/assets/24476482/f8dd22b2-a65f-4ec3-95ed-e6a036e56116

**Comment by EgglezosK** [comment]
Okay, so you can use this code: 

**For windows get this code for AutoHotKey v2**

File name: cloudflare-bypass-script.ahk
`
#Requires AutoHotkey v2.0
CoordMode("Mouse", "Window")  ; Sets the mouse coordinates relative to the active window

x := A_Args[1]  ; Takes the first argument as the x-coordinate
y := A_Args[2]  ; Takes the second argument as the y-coordinate

MouseMove x, y, 10  ; 10 is speed
Click  ;

ExitApp  ;
`


**For Ubuntu xdotool:**
File name: cloudflare-bypass-script.sh

** Do not forget to set: sudo chmod +x on cloudflare-bypass-script.sh**

`

#!/bin/bash

x=$1
y=$2
speed=50

# Move the mouse to the specified coordinates
xdotool mousemove --sync $x $y

# Click the mouse
xdotool click 1

`

**And for the NodeJS** 

`

import { connect } from './index.js'
import path from 'path';
import { fileURLToPath } from 'url';
import { exec } from 'child_process';
import xvfb from 'xvfb';

// Function to wait for a specified amount of time
function wait(ms) {
  //console.log('waiting');
  return new Promise(resolve => setTimeout(resolve, ms));
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const cloudflareBypassScriptPath = path.join(__dirname, 'cloudflare-bypass-script.sh');

async function clickInCloudflareCheckbox(page) {
  
  try {
    const elements = await page.$$('iframe');
  
    for (const element of elements) {
      const iframeSrcURL = await element.evaluate(node => node.src);
      
      if (!iframeSrcURL.includes('turnstile')) {
        console.log('there is no turnstile');
        continue;
      }

      const box = await element.boundingBox();
      if (!box) {
        console.log('There is no BOX');
        continue;
      }

      const x = box.x * 1.3; // Manually curated adjustment coefficient
      const y = box.y * 1.7; // Manually curated adjustment coefficient
      
      exec(`"${cloudflareBypassScriptPath}" ${x} ${y}`);
      await wait(2000);
      exec(`"${cloudflareBypassScriptPath}" ${x} ${y}`);
      
      return;
    }
  } catch (error) {
    console.log(`Error in clickInCloudflareCheckbox. Error: ${error}`);
  }
}

async function ByPassCloudFlare(number, proxy) {
  return new Promise((resolve, reject) => {
    const xvfbInstance = new xvfb({
      displayNum: number,
      reuse: true,
      silent: true,
    });

    xvfbInstance.start(async (error) => {
      if (error) {
        reject(error);
        return;
      }

      try {
        console.log(proxy);
        const proxynew = proxy.split(":");
        console.log(`Start of test.js ${number}`);

        const { page, browser } = await connect({
          headless: 'auto',
          args: ['--no-sandbox', '--disable-setuid-sandbox'],
          customConfig: {},
          skipTarget: [],
          fingerprint: false,
          turnstile: false,
          connectOption: {},
          proxy: {
            host: proxynew[0], 
            port: proxynew[1], 
            username: "-",
            password: "-"
          },
          englezos_custom: 5
        });

        //console.log('Cookies loaded');
        console.log('Connected to browser');

        await page.goto('https://nopecha.com/demo/cloudflare', {
          waitUntil: 'domcontentloaded'
        });

        const page_title = await page.title();

        if (page_title.includes('Just a') || page_title.includes('Cloudflare')) {
          await wait(6000);
          //await page.screenshot({ path: `example_cloudflare_${number}.png` });
          await clickInCloudflareCheckbox(page);
          //await page.screenshot({ path: `example_cloudflare_after_click_${number}.png` });
        }

        console.log('Navigated to page');

        try {
          await page.waitForSelector('.link_row', {
            timeout: 60000
        })
        } catch {
          await browser.close();
          xvfbInstance.stop(() => {
            console.log('XVFB stopped');
          });
          resolve(null);
          return;
        }

        //await page.screenshot({ path: `example_${number}.png` });

        const cookies = await page.cookies();
        const userAgent = await page.evaluate(() => navigator.userAgent);

        await browser.close();
        xvfbInstance.stop(() => {
          console.log('XVFB stopped');
        });


        const result = {
          "proxy":proxy,
          "cookies":cookies,
          "agent": userAgent
        }
        resolve(result);
      } catch (err) {
        xvfbInstance.stop(() => {
          console.log('XVFB stopped');
        });
        reject(err);
      }
    });
  });
}

await ByPassCloudFlare(99,'127.0.0.1');

`


Hope in the future to find something more robust and quick!

**Comment by CValeron** [comment]
@EgglezosK hi,

I do receive " Error: net::ERR_NO_SUPPORTED_PROXIES " error with sample code you provided.  How I can resolve this ? 

Thank you

**Comment by EgglezosK** [comment]
> @EgglezosK hi,
> 
> I do receive " Error: net::ERR_NO_SUPPORTED_PROXIES " error with sample code you provided. How I can resolve this ?
> 
> Thank you

Make sure you have change the proxy from example with your own. ( Webshare for example ) 

```
await ByPassCloudFlare(ANY_INT_NUMBER,'127.0.0.1:5555');

```

in case you don't want to use proxies, you have to comment this part of the code: 

```

proxy: {
            host: proxynew[0], 
            port: proxynew[1], 
            username: "-",
            password: "-"
          },


```

**Comment by CValeron** [comment]
Thank you solved it, but not I cannot use xdotool in my amazon linux instance. Is it event possible to click mouse with aws instance ?

**Comment by TheRealStingo** [comment]
> > @EgglezosK hi,
> > I do receive " Error: net::ERR_NO_SUPPORTED_PROXIES " error with sample code you provided. How I can resolve this ?
> > Thank you
> 
> Make sure you have change the proxy from example with your own. ( Webshare for example )
> 
> ```
> await ByPassCloudFlare(ANY_INT_NUMBER,'127.0.0.1:5555');
> ```
> 
> in case you don't want to use proxies, you have to comment this part of the code:
> 
> ```
> 
> proxy: {
>             host: proxynew[0], 
>             port: proxynew[1], 
>             username: "-",
>             password: "-"
>           },
> ```

Tried your code on windows , it didnt want to work , doesnt click , tried to investigate a bit found that 
`const elements = await page.$$("iframe");
    console.log(elements)`
    returns an empty array for some reason , 
    
    this is my windows code `import { connect } from "puppeteer-real-browser";
import path from "path";
import { fileURLToPath } from "url";
import { exec } from "child_process";

// Function to wait for a specified amount of time
function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const cloudflareBypassScriptPath = path.join(__dirname, "click.ahk");

async function clickInCloudflareCheckbox(page) {
  console.log("Clicking function");
  try {
    const elements = await page.$$("iframe");
    console.log(elements);

    for (const element of elements) {
      const iframeSrcURL = await element.evaluate((node) => node.src);

      if (!iframeSrcURL.includes("turnstile")) {
        console.log("there is no turnstile");
        continue;
      }

      const box = await element.boundingBox();
      if (!box) {
        console.log("There is no BOX");
        continue;
      }

      const x = box.x * 1.3; // Manually curated adjustment coefficient
      const y = box.y * 1.7; // Manually curated adjustment coefficient
      console.log({ x, y });

      exec(`"${cloudflareBypassScriptPath}" ${x} ${y}`);
      await wait(2000);
      exec(`"${cloudflareBypassScriptPath}" ${x} ${y}`);

      return;
    }
  } catch (error) {
    console.log(`Error in clickInCloudflareCheckbox. Error: ${error}`);
  }
}

async function ByPassCloudFlare(number) {
  try {
    const { page, browser } = await connect({
      headless: "auto",
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
      customConfig: {},
      skipTarget: [],
      fingerprint: false,
      turnstile: false,
      connectOption: {},
      englezos_custom: 5,
    });

    console.log("Connected to browser");

    await page.goto("https://nopecha.com/demo/cloudflare", {
      waitUntil: "domcontentloaded",
    });

    const page_title = await page.title();

    if (page_title.includes("Just a") || page_title.includes("Cloudflare")) {
      await wait(6000);
      console.log("Clicking");
      await clickInCloudflareCheckbox(page);
    }

    console.log("Navigated to page");

    try {
      await page.waitForSelector(".link_row", {
        timeout: 60000,
      });
    } catch {
      await browser.close();
      return null;
    }

    const cookies = await page.cookies();
    const userAgent = await page.evaluate(() => navigator.userAgent);

    await browser.close();

    return {
      cookies: cookies,
      agent: userAgent,
    };
  } catch (err) {
    console.error(`Error in ByPassCloudFlare: ${err}`);
    return null;
  }
}

// Call the function
ByPassCloudFlare(99)
  .then((result) => {
    console.log(result);
  })
  .catch((err) => {
    console.error(err);
  });
`
Setup : 
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/118802680/76834021-cd60-4960-9bad-f74d6f1ea46b)

**Comment by EgglezosK** [comment]
> > > @EgglezosK hi,
> > > I do receive " Error: net::ERR_NO_SUPPORTED_PROXIES " error with sample code you provided. How I can resolve this ?
> > > Thank you
> > 
> > 
> > Make sure you have change the proxy from example with your own. ( Webshare for example )
> > ```
> > await ByPassCloudFlare(ANY_INT_NUMBER,'127.0.0.1:5555');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in case you don't want to use proxies, you have to comment this part of the code:
> > ```
> > 
> > proxy: {
> >             host: proxynew[0], 
> >             port: proxynew[1], 
> >             username: "-",
> >             password: "-"
> >           },
> > ```
> 
> Tried your code on windows , it didnt want to work , doesnt click , tried to investigate a bit found that `const elements = await page.$$("iframe"); console.log(elements)`
> 
> returns an empty array for some reason
> 
> Here is my code on Windows :
> 
> ```
> import { connect } from "puppeteer-real-browser";
> import path from "path";
> import { fileURLToPath } from "url";
> import { exec } from "child_process";
> 
> // Function to wait for a specified amount of time
> function wait(ms) {
>   return new Promise((resolve) => setTimeout(resolve, ms));
> }
> 
> const __dirname = path.dirname(fileURLToPath(import.meta.url));
> const cloudflareBypassScriptPath = path.join(__dirname, "click.ahk");
> 
> async function clickInCloudflareCheckbox(page) {
>   console.log("Clicking function");
>   try {
>     const elements = await page.$$("iframe");
>     console.log(elements);
> 
>     for (const element of elements) {
>       const iframeSrcURL = await element.evaluate((node) => node.src);
> 
>       if (!iframeSrcURL.includes("turnstile")) {
>         console.log("there is no turnstile");
>         continue;
>       }
> 
>       const box = await element.boundingBox();
>       if (!box) {
>         console.log("There is no BOX");
>         continue;
>       }
> 
>       const x = box.x * 1.3; // Manually curated adjustment coefficient
>       const y = box.y * 1.7; // Manually curated adjustment coefficient
>       console.log({ x, y });
> 
>       exec(`"${cloudflareBypassScriptPath}" ${x} ${y}`);
>       await wait(2000);
>       exec(`"${cloudflareBypassScriptPath}" ${x} ${y}`);
> 
>       return;
>     }
>   } catch (error) {
>     console.log(`Error in clickInCloudflareCheckbox. Error: ${error}`);
>   }
> }
> 
> async function ByPassCloudFlare(number) {
>   try {
>     const { page, browser } = await connect({
>       headless: "auto",
>       args: ["--no-sandbox", "--disable-setuid-sandbox"],
>       customConfig: {},
>       skipTarget: [],
>       fingerprint: false,
>       turnstile: false,
>       connectOption: {},
>       englezos_custom: 5,
>     });
> 
>     console.log("Connected to browser");
> 
>     await page.goto("https://nopecha.com/demo/cloudflare", {
>       waitUntil: "domcontentloaded",
>     });
> 
>     const page_title = await page.title();
> 
>     if (page_title.includes("Just a") || page_title.includes("Cloudflare")) {
>       await wait(6000);
>       console.log("Clicking");
>       await clickInCloudflareCheckbox(page);
>     }
> 
>     console.log("Navigated to page");
> 
>     try {
>       await page.waitForSelector(".link_row", {
>         timeout: 60000,
>       });
>     } catch {
>       await browser.close();
>       return null;
>     }
> 
>     const cookies = await page.cookies();
>     const userAgent = await page.evaluate(() => navigator.userAgent);
> 
>     await browser.close();
> 
>     return {
>       cookies: cookies,
>       agent: userAgent,
>     };
>   } catch (err) {
>     console.error(`Error in ByPassCloudFlare: ${err}`);
>     return null;
>   }
> }
> 
> // Call the function
> ByPassCloudFlare(99)
>   .then((result) => {
>     console.log(result);
>   })
>   .catch((err) => {
>     console.error(err);
>   });
> ```
> 
> Setup : ![image](https://private-user-images.githubusercontent.com/118802680/346625944-76834021-cd60-4960-9bad-f74d6f1ea46b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTcwNDAsIm5iZiI6MTcyMDUxNjc0MCwicGF0aCI6Ii8xMTg4MDI2ODAvMzQ2NjI1OTQ0LTc2ODM0MDIxLWNkNjAtNDk2MC05YmFkLWY3NGQ2ZjFlYTQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwOTE5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmRjNjU0MTQwMTYxNDFhNDY4ZTdkYjQ2ODNkZDgzOGM3ZmQzMTVkYWI1MjUxYjgwMjUyN2RlMTEwMzQ3ZmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YaPCYJieLHa-WlII5ILbZFzKHimI4ekyTeD1-u8KOmU)

yesterday cf change their iframe shadow and its been not detectable, thanks to zcdsowatre try this: 


```


async function clickInCloudflareCheckbox(page) {

  const elements = await page.$$('.cf-turnstile-wrapper');

            if (elements.length <= 0){
              console.log('still no box');
            }

            for (const element of elements) {
                try {
                    const box = await element.boundingBox();

                    const x = box.x + box.width / 2;
                    const y = box.y + box.height / 2;
                    console.log(x + ' The X of the box');

                    await wait(3000);
                    console.log('now click');
                    exec(`"${cloudflareBypassScriptPath}" ${x-50} ${y*1.55}`);
                } catch (err) { }
            }
}

```

**Comment by zfcsoftware** [comment]
Can you please try again with the latest version of the library?

**Comment by EgglezosK** [comment]
> Can you please try again with the latest version of the library?

Thanks for the recent update! I face the same problem while using proxies, without them working like a charm.

**Comment by DivMode** [comment]
Same issue here, it works with my residential ip but with webshare proxies im failing 90% of the time now.

Was wondering is there a way to detect when the turnstile captcha has failed and close the browser instead of waiting for the timeout? With the recent captcha failures its keeping my lambda up until it times out and closes the broser increasing my costs.

**Comment by punjasin** [comment]
i just run this strait from my vps and it failed work fine locally i think cloudflare detect server IP and required user click to solve it only

**Comment by zfcsoftware** [comment]
This issue has been resolved thanks to @TheFalloutOf76. The library has been updated and tested on a Linux server. There should not be any problems now.
If you continue to experience this issue, please open a new one.

https://github.com/TheFalloutOf76/CDP-bug-MouseEvent-.screenX-.screenY-patcher

https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#docker
