### ISSUE TITLE
Turnstile autoClick not working anymore

### ISSUE THREAD

**Issue by waelbenmustapha** [zfcsoftware/puppeteer-real-browser#83]
Not sure why , but i had a code that have been working perfectly for a week , 
today randomly it stopped working , turned out the Turnstile , cloudflare checkbox is not being clicked anymore , if i click it manually all good , but the browser can't auto click it anymore .

is it just me ?

**Comment by waelbenmustapha** [comment]
so im currently digging into it , and seems like the 
`   const elements = await page.$$('iframe');`

in the checkStat function , doesn't detect the iframe , it always returns 0 iframes when in the cloudflare screen

**Comment by waelbenmustapha** [comment]
still digging and i think the iframe is not getting targeted because of #shadow-root (closed)
![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/49254321/1938f1ae-8a8c-4a3e-a52c-5c2a26aa56b0)

**Comment by EgglezosK** [comment]
@waelbenmustapha First of all try this to check if the automate click is working

[ https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2205737725]( https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2205737725)

**Comment by waelbenmustapha** [comment]
> @waelbenmustapha First of all try this to check if the automate click is working
> 
> [ https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2205737725](https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2205737725)

I tried and i faced same issue .

**Comment by EgglezosK** [comment]
> > @waelbenmustapha First of all try this to check if the automate click is working
> > [ https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2205737725](https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2205737725)
> 
> I tried and i faced same issue .

[https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2211829757](https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2211829757)

**Comment by TheRealStingo** [comment]
> > @waelbenmustapha First of all try this to check if the automate click is working
> > [ https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2205737725](https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2205737725)
> 
> I tried and i faced same issue .

Did  you find a solution for the your issue ?

**Comment by waelbenmustapha** [comment]
> > > @waelbenmustapha First of all try this to check if the automate click is working
> > > [ https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2205737725](https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2205737725)
> > 
> > 
> > I tried and i faced same issue .
> 
> Did you find a solution for the your issue ?

for me i kinda followed the idea they had but simpler solution , for me it's just one page that i need scrapping and the captcha always appear at the same screen , 

so i just added a mouse click like this 
```
    page.setViewport({ width: 800, height:  1000 });
    ...
    await page.mouse.move(55, 325);
    // Click at the desired coordinates
    await page.mouse.click(55, 325);
  
```

**Comment by waelbenmustapha** [comment]
> > > @waelbenmustapha First of all try this to check if the automate click is working
> > > [ https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2205737725](https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2205737725)
> > 
> > 
> > I tried and i faced same issue .
> 
> [#80 (comment)](https://github.com/zfcsoftware/puppeteer-real-browser/issues/80#issuecomment-2211829757)

also btw , i did a small trick that might help you , 
pretty much change the closed shadow root to open shadow root , which allows us to get the checkbox and click it , 

but i faced few issues with it , that when you click it it doesn't work anymore , it gets stuck the captcha , 

i just wanted to share the idea

**Comment by EgglezosK** [comment]
> hat when you click it it doesn't work

Have you Discord or something? to figure it out together and proceed to a solution ?

**Comment by zfcsoftware** [comment]
The problem should be solved. Please test with the latest version.

**Comment by waelbenmustapha** [comment]
> The problem should be solved. Please test with the latest version.

Thank you , good solution you did there
