### ISSUE TITLE
Can't bypass CF at ubuntu server

### ISSUE THREAD

**Issue by JimKarvo** [zfcsoftware/puppeteer-real-browser#85]
Hello,

Trying the demo script, at my ARM ubuntu server.

I have the browser opened, try to bypass the CF, presses the checbox, but never goes through.

![image](https://github.com/zfcsoftware/puppeteer-real-browser/assets/84914040/d5f346df-1a1d-4b1f-b0ce-e43c09ba57a4)

**I just get infinitive loop at Turnstile**

Tried the server IP, proxies, and my home IP without success.

Tried different User Agent, no luck.

Same code at windows machine works!

**Comment by bsantos09** [comment]
Having the same issue.

**Comment by DollarNoob** [comment]
Also facing infinite loop issue on MacOS. Disabling turnstile and manually clicking the checkbox appears to pass the captcha box.

**Comment by zfcsoftware** [comment]
Could you please try again now with the latest version? If the problem persists, it's probably xvfb catching. I am waiting to hear back from you.

**Comment by JimKarvo** [comment]
Hello @zfcsoftware, thank you for your reply!

Just tryied the updated code, also downloaded the git and run the test.js, no luck

The problem is there, it is like infinity loop. The checkbox is clicked, but somewhow seems like the script is detected!

**Comment by zfcsoftware** [comment]
It seems to pass on devices with a screen and not on those without. xfvb It may be detected. I am looking into it.

**Comment by minhdev2017** [comment]
hi @zfcsoftware
I install latest version but got error:

`286 silly packumentCache full:https://registry.npmjs.org/tr46 cache-miss
287 silly fetch manifest webidl-conversions@^3.0.0
288 silly packumentCache full:https://registry.npmjs.org/webidl-conversions cache-miss
289 http fetch GET 200 https://registry.npmjs.org/tr46 11ms (cache hit)
290 silly packumentCache full:https://registry.npmjs.org/tr46 set size:41044 disposed:false
291 http fetch GET 200 https://registry.npmjs.org/webidl-conversions 11ms (cache hit)
292 silly packumentCache full:https://registry.npmjs.org/webidl-conversions set size:41857 disposed:false
293 silly placeDep ROOT tr46@0.0.3 OK for: whatwg-url@5.0.0 want: ~0.0.3
294 silly placeDep ROOT webidl-conversions@3.0.1 OK for: whatwg-url@5.0.0 want: ^3.0.0
295 silly placeDep ROOT mkdirp-classic@0.5.3 OK for: tar-fs@3.0.4 want: ^0.5.2
296 verbose stack Error: An unknown git error occurred
296 verbose stack     at makeError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\make-error.js:28:13)
296 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\spawn.js:37:26
296 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`


1 info using npm@10.8.1
2 info using node@v20.15.1
I using Window server 2016
how to fix them pls

**Comment by rahulkarmakaritobuz** [comment]
I also faced the same issue when I tried to solve Cloudflare in EC2, even after waiting 1min for each solving 
<img width="777" alt="Screenshot 2024-07-11 at 1 31 46 PM" src="https://github.com/zfcsoftware/puppeteer-real-browser/assets/123539674/afb477e4-65b0-4718-816c-4f7d1deadb6f">

**Comment by JimKarvo** [comment]
Maybe this is not a problem with xvfb.
Just tried from the windows machine with nordvpn, and I got the same problem.

If I open a normal Chrome windows and click the checkbox I can bypass the turnstile 

Seems like the script is detected, but I can't understand why.

Some other libraries writes that the CF detects also the mouse movements

**Comment by Hartyshow26** [comment]
Personnally the "turnstile: true" attribute doesn't change anything on bypass, no click is done on the "not a robot" checkbox.

**Comment by 14790897** [comment]
> Personnally the "turnstile: true" attribute doesn't change anything on bypass, no click is done on the "not a robot" checkbox.

yes

**Comment by bsantos09** [comment]
Anyone was able to come up with a solution?

**Comment by zfcsoftware** [comment]
This issue has been resolved thanks to @TheFalloutOf76. The library has been updated and tested on a Linux server. There should not be any problems now.
If you continue to experience this issue, please open a new one.

https://github.com/TheFalloutOf76/CDP-bug-MouseEvent-.screenX-.screenY-patcher

https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#docker
