### ISSUE TITLE
Problem on turnstile and cf_clearance

### ISSUE THREAD

**Issue by Hartyshow26** [zfcsoftware/puppeteer-real-browser#89]
Hi,

I have a problem on the site Stake.games to go through CloudFlare challenge. My code is the following :

`const { page, browser } = await connect({ turnstile: true, fingerprint: true });`

And the browser is just stuck in CloudFlare screen and can't click on the checkbox :
![image](https://github.com/user-attachments/assets/deee3cc3-6c25-4b71-9b6c-0e30b91922b8)

And some times the challenge is directly passed successfully but if I ask for cookies, I don't have any cf_clearance token... Is this normal ? I have used this solution for weeks without any problem and now for 1 week I can't get any new cf_clearance tokens !

Thanks in advance for your help !

**Comment by CValeron** [comment]
Same here, After I got last update, I have passed cf for a couple of days and now cannot pass cloudfare

**Comment by TheFalloutOf76** [comment]
https://github.com/TheFalloutOf76/CDP-bug-MouseEvent-.screenX-.screenY-patcher

**Comment by Hartyshow26** [comment]
Ok that work with your extension @TheFalloutOf76 thank you !

For the cf_clearance token problem, do you have a solution ?

**Comment by TheFalloutOf76** [comment]
what is the problem?

**Comment by Hartyshow26** [comment]
Well, I can't get any cf_clearance token even after passing through CloudFlare in the site https://stake.bet/. And if I succeed to get a cf_clearance token in my browser, putting it into cookies part of puppeteer doesn't change anything, it doesn't bypass anything

**Comment by zfcsoftware** [comment]
This issue has been resolved thanks to @TheFalloutOf76. The library has been updated and tested on a Linux server. There should not be any problems now.
If you continue to experience this issue, please open a new one.

https://github.com/TheFalloutOf76/CDP-bug-MouseEvent-.screenX-.screenY-patcher

https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#docker
