### ISSUE TITLE
CloudFlare captcha reloading

### ISSUE THREAD

**Issue by sajt** [zfcsoftware/puppeteer-real-browser#91]
I tried the example what is in the README.md and the cloudflare captcja asking agaun and again after the bot checked it. 

I made a little project to show: https://github.com/sajt/puppeteer-real-browser-test

I think this problem occurs about 1 month ago.

**Comment by punjasin** [comment]
they have ip blocking now it work fine with local machine but not work on cloud provider IMO all my VM just stop working except one i run locally

**Comment by zfcsoftware** [comment]
This issue has been resolved thanks to @TheFalloutOf76. The library has been updated and tested on a Linux server. There should not be any problems now.
If you continue to experience this issue, please open a new one.

https://github.com/TheFalloutOf76/CDP-bug-MouseEvent-.screenX-.screenY-patcher

https://github.com/zfcsoftware/puppeteer-real-browser?tab=readme-ov-file#docker
