### ISSUE TITLE
ws affected by a DoS when handling a request with many HTTP headers?

### ISSUE THREAD

**Issue by Skarzyll** [zfcsoftware/puppeteer-real-browser#92]
npm warn deprecated puppeteer@21.11.0: < 22.6.4 is no longer supported

added 57 packages, and audited 173 packages in 26s

13 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

**Comment by zfcsoftware** [comment]
The library has been updated. This problem should be solved. Can you try again now?

**Comment by Skarzyll** [comment]
yes, thanks!
