### ISSUE TITLE
unable to click turnstile

### ISSUE THREAD

**Issue by 14790897** [zfcsoftware/puppeteer-real-browser#93]
https://github.com/user-attachments/assets/918cf406-9889-4714-b0d5-3f7f2ccdac6d

**Comment by zfcsoftware** [comment]
this problem should be solved, can you check again?

**Comment by DivMode** [comment]
Updated to latest version but having the same issue.

**Comment by zfcsoftware** [comment]
> Updated to latest version but having the same issue.

Use with docker. Tested with a linux server and docker run file. Works without any problems.

**Comment by binge1993** [comment]
both in windows server and windows10, 1.2.31 also can not auto click, can you test again？

**Comment by 14790897** [comment]
same, can't click
