### ISSUE TITLE
TimeoutError: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!

### ISSUE THREAD

**Issue by Avsy** [zfcsoftware/puppeteer-real-browser#96]
TimeoutError: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!
    at ChromeLauncher.launch (file:///root/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:121:23)
    at async file:///root/node_modules/puppeteer-real-browser/src/module/chromium.js:68:29
file:///root/node_modules/puppeteer-real-browser/src/module/chromium.js:98
            throw new Error(err.message)
                  ^

Version
1.2.24

**Comment by zfcsoftware** [comment]
I updated. Can you try again with the latest version?

**Comment by Avsy** [comment]
> I updated. Can you try again with the latest version?

The error is still the same after start src/test.js

Version
1.2.29

**Comment by Avsy** [comment]
The problem was in import.meta.dirname

const EXTENSION_PATH = `${__dirname}/extension/`; >> undefined/extension/

**Comment by zfcsoftware** [comment]
> The problem was in import.meta.dirname added in: v21.2.0, v20.11.0
> 
> `${__dirname}/extension/` > `undefined/extension/`

I have now tested it on 2 operating systems and there seems to be no problem. Can you please provide information to reproduce the error? Which operating system? Which code?

Windows Server Test:
https://github.com/user-attachments/assets/b1c4dca1-db48-4692-ac67-fc399d11e009

Ubuntu 24 test:
https://github.com/user-attachments/assets/b1040e6a-9d8d-4fed-910a-52cabbd82130

**Comment by xheatcodes** [comment]
same too on ubuntu 22.04, installin via npm. I have rolled back to the previous version

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/puppeteer-real-browser/issues/97
This problem has just been resolved. Can you try again with the latest version?

**Comment by Avsy** [comment]
I use Node v18.20.2 
Problem with import.meta.dirname because support by Node v21.2.0, v20.11.0

**Comment by xheatcodes** [comment]
> #97 This problem has just been resolved. Can you try again with the latest version?

It works great, thank you so much

**Comment by zfcsoftware** [comment]
> I use Node v18.20.2 Problem with import.meta.dirname because support by Node v21.2.0, v20.11.0

With the last update, it should now work. If the problem persists, I can open it again if you update this issue by writing a message.



> > #97 This problem has just been resolved. Can you try again with the latest version?
> 
> It works great, thank you so much

Thank you for testing it.

**Comment by Avsy** [comment]
It works great, thank you!
