### ISSUE TITLE
Error Loading Extension 

### ISSUE THREAD

**Issue by SattyaP** [zfcsoftware/puppeteer-real-browser#97]
![image](https://github.com/user-attachments/assets/64167363-b430-49cb-8bdc-727d9fd907b5)

What kind of error is that? 
I mean everything works but when I start the program it pops up and bothers me a bit.

**Comment by zfcsoftware** [comment]
https://github.com/zfcsoftware/puppeteer-real-browser/tree/main/src/module/extension
an error explaining that the extension that updates the mouse position cannot be installed. Can you post your operating system and the code you are running?

**Comment by zfcsoftware** [comment]
Windows Server Test:
https://github.com/user-attachments/assets/b1c4dca1-db48-4692-ac67-fc399d11e009

Ubuntu 24 test:
https://github.com/user-attachments/assets/b1040e6a-9d8d-4fed-910a-52cabbd82130

**Comment by mrizkypk** [comment]
I got the same error message.
I run sample code from README - Usage.

Macbook Pro M1 Pro
MacOS Sonoma 14.5

**Comment by zfcsoftware** [comment]
> I got the same error message. I run sample code from README - Usage.
> 
> Macbook Pro M1 Pro MacOS Sonoma 14.5

I don't use a Mackbook and I don't have a system I can test in that environment. Sorry. I suggest you rent a Linux server and use it.

**Comment by mrizkypk** [comment]
> > I got the same error message. I run sample code from README - Usage.
> > Macbook Pro M1 Pro MacOS Sonoma 14.5
> 
> I don't use a Macbook and I don't have a system I can test in that environment. Sorry. I suggest you rent a Linux server and use it.

I just try the same code on my windows RDP and it runs smoothly. Thanks.

**Comment by zfcsoftware** [comment]
> > > I got the same error message. I run sample code from README - Usage.
> > > Macbook Pro M1 Pro MacOS Sonoma 14.5
> > 
> > 
> > I don't use a Macbook and I don't have a system I can test in that environment. Sorry. I suggest you rent a Linux server and use it.
> 
> I just try the same code on my windows RDP and it runs smoothly. Thanks.

I've posted an update, it should work for Macbook now can you test it?

**Comment by mrizkypk** [comment]
> > > > I got the same error message. I run sample code from README - Usage.
> > > > Macbook Pro M1 Pro MacOS Sonoma 14.5
> > > 
> > > 
> > > I don't use a Macbook and I don't have a system I can test in that environment. Sorry. I suggest you rent a Linux server and use it.
> > 
> > 
> > I just try the same code on my windows RDP and it runs smoothly. Thanks.
> 
> I've posted an update, it should work for Macbook now can you test it?
> 
> EDIT: Version: 1.2.31

Tested, it's works! 🔥

**Comment by SattyaP** [comment]
![image](https://github.com/user-attachments/assets/9f3bb36b-2a8b-464a-8fa5-28ce4ff0faee)

Hi thanks for responding
I am running the code on 

Windows 10

What's the solution for this, any suggest ?

**Comment by SattyaP** [comment]
> ![image](https://private-user-images.githubusercontent.com/100116558/352695656-9f3bb36b-2a8b-464a-8fa5-28ce4ff0faee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNTM1MjUsIm5iZiI6MTcyMjA1MzIyNSwicGF0aCI6Ii8xMDAxMTY1NTgvMzUyNjk1NjU2LTlmM2JiMzZiLTJhOGItNDY0YS04ZmE1LTI4Y2U0ZmYwZmFlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwNDA3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGM4NGU2ZDc0YWNmMzliYTJmZmE2NjUyMTdiNDBjM2I5OThjMTI2ZGNlYzg5NmMyOTM0MDc3ZGQyMjZkMDdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d7F2ysRYh5tOV1k-wNPvIqL3NYBrpGuqmemGnCY9QpI)
> 
> Hi thanks for responding I am running the code on
> 
> Windows 10
> 
> What's the solution for this, any suggest ?

OHH ITS DONE! 
I update to latest version thanks🤩

**Comment by zfcsoftware** [comment]
> ![image](https://private-user-images.githubusercontent.com/100116558/352695656-9f3bb36b-2a8b-464a-8fa5-28ce4ff0faee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjkyNTIsIm5iZiI6MTcyMjA2ODk1MiwicGF0aCI6Ii8xMDAxMTY1NTgvMzUyNjk1NjU2LTlmM2JiMzZiLTJhOGItNDY0YS04ZmE1LTI4Y2U0ZmYwZmFlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwODI5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDMyZWYzMTdiNTFkNmRlYjRjZTkwMzM4ZmNmNzNjODU1NzQzMWVmYzQ1MmE2YWY3ZjIxMmE4NDA3ZjBmNWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m28pl9EG_LFn-TcJisXu1oKmC1hMmJMcnCjQ7Yc_B7Q)
> 
> Hi thanks for responding I am running the code on
> 
> Windows 10
> 
> What's the solution for this, any suggest ?

This problem was solved yesterday. Are you sure you are using version 1.2.31? Windows, Linux and Macos tests were done.

**Comment by SattyaP** [comment]
> > ![image](https://private-user-images.githubusercontent.com/100116558/352695656-9f3bb36b-2a8b-464a-8fa5-28ce4ff0faee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjkyNTIsIm5iZiI6MTcyMjA2ODk1MiwicGF0aCI6Ii8xMDAxMTY1NTgvMzUyNjk1NjU2LTlmM2JiMzZiLTJhOGItNDY0YS04ZmE1LTI4Y2U0ZmYwZmFlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwODI5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDMyZWYzMTdiNTFkNmRlYjRjZTkwMzM4ZmNmNzNjODU1NzQzMWVmYzQ1MmE2YWY3ZjIxMmE4NDA3ZjBmNWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m28pl9EG_LFn-TcJisXu1oKmC1hMmJMcnCjQ7Yc_B7Q)
> > Hi thanks for responding I am running the code on
> > Windows 10
> > What's the solution for this, any suggest ?
> 
> This problem was solved yesterday. Are you sure you are using version 1.2.31? Windows, Linux and Macos tests were done.

Already solve i just need to configure manual the extension but its fine thanks
