### ISSUE TITLE
Error verison 1.2.31 in Ubuntu

### ISSUE THREAD

**Issue by alextran317** [zfcsoftware/puppeteer-real-browser#98]
Error verison 1.2.31 in Ubuntu:

Error: Failed to launch the browser process!
/root/.cache/puppeteer/chrome/linux-126.0.6478.182/chrome-linux64/chrome: 1: Syntax error: ")" unexpected

**Comment by zfcsoftware** [comment]
> Error verison 1.2.31 in Ubuntu:
> 
> Error: Failed to launch the browser process! /root/.cache/puppeteer/chrome/linux-126.0.6478.182/chrome-linux64/chrome: 1: Syntax error: ")" unexpected

If you are not using docker, you should use it with Dockerfile. It has many dependencies. It gives an error before loading.

**Comment by alextran317** [comment]
I don't use Docker; I installed it using commands on Ubuntu. Other versions worked fine until I used version 1.2.31, which gave me the error above. Is there any other way to solve this issue without having to install Docker?

**Comment by zfcsoftware** [comment]
> I don't use Docker; I installed it using commands on Ubuntu. Other versions worked fine until I used version 1.2.31, which gave me the error above. Is there any other way to solve this issue without having to install Docker?

You may have problems with some of the commands in the dockerfile. It is probably due to the failure to install dependencies. The only solution I can recommend for Linux is Docker.
